### ISSUE TITLE
Support for Disqus

### ISSUE THREAD

**Issue by mbollemeijer** [luizdepra/hugo-coder#10]
I was wondering if you have plans to support Discqus into your theme ?   
https://disqus.com/

**Comment by luizdepra** [comment]
Hmm... Not right now, I think.

But, It isn't that hard to add Disqus. I would appreciate if you add it and open a PR after. :smiley:

**Comment by mbollemeijer** [comment]
Yhe I was thinking of doing that, got some things on my shortlist that I want to do first.
So when I got the time I will start working on the integration, should not take that long.
