### ISSUE TITLE
style.coder.css

### ISSUE THREAD

**Issue by marxvr** [luizdepra/hugo-coder#104]
failed to transform "style.coder.css" (text/x-scss): this feature is not available in your current Hugo version（my ver is 4.9.2）

**Comment by khos2ow** [comment]
Did you mean `0.49.2`? Make sure you have Hugo extended, as this theme depends on extended version.

**Comment by luizdepra** [comment]
Remembering that this theme only needs the extended version if you will need to change or override a SCSS file.
