### ISSUE TITLE
Error on deploying the coder theme

### ISSUE THREAD

**Issue by saiKumarGanji** [luizdepra/hugo-coder#105]
$ hugo serve -D
Building sites … ERROR 2018/10/20 16:55:04 error: failed to transform resource: TOCSS: failed to transform "style.coder.css" (text/x-scss): this feature is not available in your current Hugo version
Total in 156 ms
Error: Error building site: logged 1 error(s)

Using Windows Hugo v0.49
I saw the solution on https://github.com/luizdepra/hugo-coder/issues/75, but it is specific to linux.
Please tell me how i can resolve this issue on windows.

**Comment by luizdepra** [comment]
Hey. It is the same issue. If you are changing one or more SCSS file you will need to the hugo extended version. 

[This](https://github.com/gohugoio/hugo/releases/download/v0.49.2/hugo_extended_0.49.2_Windows-64bit.zip) is the last version until now.

**Comment by saiKumarGanji** [comment]
Thanks, its working with the provided exe file.
