### ISSUE TITLE
Integrity Issue

### ISSUE THREAD

**Issue by chipsenkbeil** [luizdepra/hugo-coder#106]
This happens when I open my browser on my deployed website for the first time after the browser is started. The site is hosted via github and SSL provided via cloudflare.

Something about an integrity issue. Reloading the page resolves this, but I'm not sure what in the CSS is causing this and how I can fix it.

![integrity issue](https://user-images.githubusercontent.com/2481802/47259099-d631a600-d46a-11e8-8405-ee51a72cb0e4.gif)

**Comment by luizdepra** [comment]
I was unable to reproduce this issue.
Could you check if your site is being generated with `crossorigin="anonymous"` attribute inside the CSS file link tag?

**Comment by chipsenkbeil** [comment]
@luizdepra, I don't think I had that update on my site. Let me pull latest and see what happens.

**Comment by chipsenkbeil** [comment]
Think that fixed it. Not seeing it right now, anyway. I'll reopen if it appears again. Thanks!

**Comment by retiolus** [comment]
Hello, I am currently experiencing the same problem on my website: [retiolus.net](https://retiolus.net). I am using the latest version of hugo-coder :)
