### ISSUE TITLE
Talks page

### ISSUE THREAD

**Issue by qeef** [luizdepra/hugo-coder#11]
I am going to build my personal page with [hugo-coder](https://github.com/luizdepra/hugo-coder/). Sometimes I do talks so I want something for writing slides for presentations. Markdown is preferred and slides access from any computer is nice to have.

The proposal is for next pages called *Talks* similar to *Posts* with the full page scrolling functionality.

**Comment by luizdepra** [comment]
Hey! Sorry for taking too long to give a reply.

So, I tested your PR and it is good.
I just want to tell that I will merge your PR in a separated branch. I'll use your contribution as a base for a template refactor and I also will add tags, categories and series archetypes.

**Comment by qeef** [comment]
Great, thanks a lot! Looking forward to refactored version!

**Comment by khos2ow** [comment]
Fair enough. +1 on addition. If the _presentations_ you have in mind are not complex, the proposed feature will definitely work.

> I want the static one, generated by hugo, hosted as github page. ... I am going to share some notes (like blog) and some presentations (like talks). Multiple notes and multiple talks on one site.

I just want to point out that you still can achieve some complex scenarios within github pages relatively easy.

- have multiple standalone repos for revealjs-based full presentation (they will be accessible under `https://YOU_NAME.github.io/<repo-of-talk>`)
- have multiple directory in your hugo-coder based repo (e.g. `<repo>/talks/<revealjs-talks-folder>`) and with a little bit of scripting generate `hugo /talks/*` and put them in `static` folder then generate the root repo.

**Comment by luizdepra** [comment]
I'm wondering if there an option to create a slide page without using JS.

**Comment by khos2ow** [comment]
There seems to be [bunch of them](https://corpocrat.com/2015/12/09/20-cool-pure-css-sliders-without-jqueryjavascript/), or even the fullPage.js in question [without jQuery](https://github.com/alvarotrigo/fullPage.js/tree/master/pure%20javascript%20(Alpha)).

**Comment by luizdepra** [comment]
We can continue discussing this issue at #60.
