### ISSUE TITLE
How to add "rel=me" to social links?

### ISSUE THREAD

**Issue by jemostrom** [luizdepra/hugo-coder#116]
Some social sites uses a rel="me" tag to identify/link a user to a web site. For example Mastodon that suggests a link like this

`<a rel="me" href="https://mastodon.social/@xxxxxxx">Mastodon</a>`

Can I set up this in the config file?

**Comment by luizdepra** [comment]
No, you can only set the icon in the config file.
You will need to change the template code. But, this will apply the `rel="me"` to every social item.
