### ISSUE TITLE
Vertical Alignment of Homepage Content

### ISSUE THREAD

**Issue by josephting** [luizdepra/hugo-coder#122]
After #114, @khos2ow reported that the main content is no longer vertically centered on homepage.

I have #118 opened to fix this but some discussion is needed so I'm submitting this issue.

Basically, after removal of `display: flex` on body, the `.centered` class has to be rewritten. I've fixed the issue by using `justify-content: space-between` but without adding new class to the template (reuse `.wrapper`), this will get applied to all pages causing short content such as [Blog list](https://deploy-preview-118--hugo-coder.netlify.com/posts/) to be vertically centered.

Since this rule will apply to the `main.wrapper` element, I wonder if I should:

- Remove existing `.centered` and move it to `main.wrapper.centered` with new `justify-content` rule

OR

- Add new class and leave `.centered` alone (though it wouldn't work properly anymore)
  - Should the new class be something reusable like `.centered` (accepting suggestions)
  - Or should it be `.home`?

**Comment by luizdepra** [comment]
Fixed at #118.
