### ISSUE TITLE
Hugo Site Demo navigation links throw 404

### ISSUE THREAD

**Issue by onedrawingperday** [luizdepra/hugo-coder#132]
Hello @luizdepra and Happy New Year!

I am one of the maintainers of the Hugo Themes repository and today someone [posted](https://github.com/gohugoio/hugoThemes/issues/477#issuecomment-450809944) that this theme's demo has missing assets on the Hugo website.

I had a look and it seems that the demo's navigation links: `Projects` `Contact Me` and every navigation link once the Polish Language is selected throw a 404 because you have not provided content files for these links.

This has been going on since you merged https://github.com/luizdepra/hugo-coder/commit/f597d91e5556e5f13860a2b65042cee782553b89

Can you please either provide sample content for these menu links as well as sample Polish versions so that the demo's menu works properly?

Or if that is too much of a hassle then please remove the menu items that do not have corresponding pages.

Once you look into the above let me know.

Thanks.

cc @digitalcraftsman

**Comment by luizdepra** [comment]
Thank you, @onedrawingperday.
I just have added the missing content, so, these links should be fine now.
