### ISSUE TITLE
Help Wanted - Icons

### ISSUE THREAD

**Issue by M-Brody** [luizdepra/hugo-coder#135]
Hello!

Thank you for making such a clean theme for Hugo.

My question concerns icon links for social media websites. I'm new to all this but I was able to add a new link but can't seem to figure out how to change the icon. On my website I have a link to Strava and have an icon I would like to use, but I don't know which file it needs to reside in so I can reference it in the config file.

My site = mattbrody.io

Thanks for your help!

**Comment by josephting** [comment]
Please share your config file.

```
[[params.social]]
    name = "Github" # Just a label for your reference
    icon = "fab fa-github" # Fontawesome icon class
    weight = 1 # Order
    url = "https://github.com/johndoe/" # Destination URL
```

What you want to do here is to change the value of `icon`.

You can look for the icon you want on [Font Awesome](https://fontawesome.com/icons?d=gallery&s=brands).

The icon you probably want is [this](https://fontawesome.com/icons/strava?style=brands) and you want to set `icon` to `fab fa-strava`.

**Comment by luizdepra** [comment]
Thank you for answering, @josephting.

I think this issue is solved. So, closing.

**Comment by M-Brody** [comment]
Apologies for not responding. Yes, the above help was just want I needed. Thanks!

**Comment by jaredtconnor** [comment]
I seem to be getting a relatively same issue as above. I'm attempting to use a favicon to reference a `mailto:` link, to provide my email address. 

I have my social links specified as follows: 

``` 
# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/jaredtconnor/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/Jared_ThomasC/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/jaredconnor/"
[[params.social]]
    name = "Mail"
    icon = "fab fa-envelope fa-2x"
    weight = 4
    url = "mailto:jaredconnor301@gmail.com"
```

The icon and link is available on the page, but the icon is hidden. My other social links appear to work, and the `envelop` is a viable free icon. Any suggestions on a possible fix? 

Branch repo: [here](https://github.com/jaredtconnor/Personal-Site/tree/icon_fix_branch)

<img width="461" alt="Screen Shot 2019-06-23 at 9 00 29 PM" src="https://user-images.githubusercontent.com/23062816/59990922-f4533580-95f9-11e9-9d5a-5610ea7a3b83.png">

**Comment by luizdepra** [comment]
@jaredtconnor, you should use `fas` instead of `fab`. The `fab` classes are used only with brand icons, `fas` for other icons if you want them with solid style.

https://fontawesome.com/icons/envelope?style=solid

**Comment by jaredtconnor** [comment]
Gotcha, thank you.
