### ISSUE TITLE
Template not rendering files at the end of permlink templates

### ISSUE THREAD

**Issue by fbdo** [luizdepra/hugo-coder#137]
Hi! I was following this tutorial: http://blog.aws.andyfase.com/s3-backed-static-blog/index.html to use hugo to create a static web site and depIoy it to AWS S3 and I decided to use hugo-coder as my template, you can see the result here: http://www.fabiooliveira.me, and the code here: https://github.com/fbdo/site, so, I can't thank you enough for the amazing work!

Back to business... I tried to use the workaround described in the tutorial to bypass the AWS Cloudfront limitation of not being able to forward requests ending in slashes "/" to "/index.html", so basically I configured in config.toml the following:

[Permalinks]
  posts = "/:year/:month/:day/:title/index.html"

but no success. As you can see in the blog front page: http://www.fabiooliveira.me/posts/index.html, the link for my first post points to "http://www.fabiooliveira.me/2019/01/13/the-belonging-clues/index.html/", so not to the file itself but adds a final "/" what now the CDN interprets as another folder.

I checked the hugo documentation and looks like I am not doing anything wrong, so I guess it is a bug in the template while rendering paths.

**Comment by fbdo** [comment]
Hi! I was following this tutorial: http://blog.aws.andyfase.com/s3-backed-static-blog/index.html to use hugo to create a static web site and depIoy it to AWS S3 and I decided to use hugo-coder as my template, you can see the result here: http://www.fabiooliveira.me, and the code here: https://github.com/fbdo/site, so, I can't thank you enough for the amazing work!

Back to business... I tried to use the workaround described in the tutorial to bypass the AWS Cloudfront limitation of not being able to forward requests ending in slashes "/" to "/index.html", so basically I configured in config.toml the following:

[Permalinks]
  posts = "/:year/:month/:day/:title/index.html"

but no success. As you can see in the blog front page: http://www.fabiooliveira.me/posts/index.html, the link for my first post points to "http://www.fabiooliveira.me/2019/01/13/the-belonging-clues/index.html/", so not to the file itself but adds a final "/" what now the CDN interprets as another folder.

I checked the hugo documentation and looks like I am not doing anything wrong, so I guess it is a bug in the template while rendering paths.

**Comment by luizdepra** [comment]
I think Hugo have changed a bit how it handle permalinks and/or paths. The link to the post is `http://www.fabiooliveira.me/2019/01/13/the-belonging-clues/index.html/index.html`, so Hugo created a folder with the `index.html` name.

You can achiev something similar using `uglyURLs = true` in your `confix.toml` and changing the permalink config to:
```
[permalinks]
  posts = "/:year/:month/:day/:title/index"
```
But, `uglyURLs` will change your posts pages from `/posts/index.html` to `/posts.html`. Which isn't very nice.

Have you considered using [Netlify](www.netlify.com)? It's free for static sites and you can easy add HTTPS (no need to buy a cert). Also, it integrate with others generators, like jekyll, and the service will build your site when you push something to your repository. I'm using Netlify to serve my [personal website](luizdepra.com) and this theme PR previews.

**Comment by fbdo** [comment]
I am using hugo, I am using the CircleCI to automate the site build, and deploying it to AWS S3 (you can see the infra code using Terraform here: https://github.com/fbdo/aws-terraform-site). all in all I like the solution and the theme is great, only this AWS Cloudfront "issue" is making me crazy. There is a solution recommended by AWS using Lambdas@Edge (see https://aws.amazon.com/blogs/compute/implementing-default-directory-indexes-in-amazon-s3-backed-amazon-cloudfront-origins-using-lambdaedge/) but this solution will make me expend a few bucks more.

So, you are saying this is not a bug, but by design?

**Comment by luizdepra** [comment]
I don't thing this is a theme bug, maybe it is a Hugo one. It seems Hugo changed a bit how it handle permalinks and this kind of stuff.

If I were you I would ask for help in the (Hugo's forum)[https://discourse.gohugo.io/]. I think they can provide a better support on this problem.

**Comment by fbdo** [comment]
Thanks for your help, I will check them. I will close this issue.
