### ISSUE TITLE
Pagination Link Color

### ISSUE THREAD

**Issue by josephting** [luizdepra/hugo-coder#143]
I've noticed a probable unexpected changes made to the pagination link color introduced by #138, more specifically [here at L84](https://github.com/luizdepra/hugo-coder/pull/138/files#diff-989965b21d6c814dee9c58c26e7fb7c6).

**Before**

<img width="63" alt="2019-02-08 16 24 33" src="https://user-images.githubusercontent.com/1507016/52464475-62a0d980-2bbe-11e9-8983-1fe102dd12e5.png">

**After**

<img width="66" alt="2019-02-08 16 24 41" src="https://user-images.githubusercontent.com/1507016/52464476-63397000-2bbe-11e9-8674-40ce201feeb5.png">

I'm not sure if this is intended or not but I prefer the old look.

**Comment by luizdepra** [comment]
I'll take a look.

**Comment by luizdepra** [comment]
Ok, fixed it with #145.

The link color is as inteted, blue, like most of the links.
But a changed the font to the heading one.
