### ISSUE TITLE
Cannot deploy my site giving error

### ISSUE THREAD

**Issue by iamrajiv** [luizdepra/hugo-coder#155]
When I attempt to deploy my site I am getting an error
```
C:\Users\Rajiv\Desktop\site>hugo server

Building sites . ERROR 2019/03/09 03:22:44 error: failed to transform resource:
TOCSS: failed to transform "style.coder.css" (text/x-scss): this feature is not
available in your current Hugo version
Total in 18 ms
Error: Error building site: logged 1 error(s)
```

I am using Windows 7 Ultimate 64-bit OS
and I am using Hugo(v0.54)
```
Hugo Static Site Generator v0.54.0-B1A82C61 windows/amd64 BuildDate: 2019-02-01T
09:42:02Z

```

**Comment by sebnyberg** [comment]
Had the same issue.

You need to install hugo extended, available near the bottom of the [latest release](https://github.com/gohugoio/hugo/releases).

**Comment by iamrajiv** [comment]
![Capture](https://user-images.githubusercontent.com/42106787/54072322-57b19580-429f-11e9-8cbc-e4aa98a60389.PNG)

@sebnyberg are you talking of `hugo_extended_0.47.1_Windows-64bit.zip`

**Comment by sebnyberg** [comment]
Yeah. I'm on Linux so I'm not sure what the installation looks like for Windows, but that zip should do the trick.

**Comment by iamrajiv** [comment]
@sebnyberg yup I have solved my issue thank you
