### ISSUE TITLE
Inserting a New Post

### ISSUE THREAD

**Issue by cassiorampinelli** [luizdepra/hugo-coder#157]
Olá Luiz, primeiramente, obrigado por disponibilizar esta opção de site.

Quando eu utilizo o comando Addins->New Post no R Studio  para inserir um novo post, a página do Rmarkdown aparece direitinho, contudo, quando vou atualizar o site por meio do comando Addins->Serve Site, o novo post não aparece naquela página de visualização (viewer) no menu Blog  naquela lista dos posts (apenas os modelos que já existem aparecem lá). Você teria alguma ideia do que pode estar acontecendo?

Obrigado.

**Comment by luizdepra** [comment]
Olá, Cassio.
Eu nunca usei o R Studio, e nem sabia que ele tinha uma integração com o Hugo, então vou dar um chute no escuro aqui. Normalmente quando um post não aparece no site publicado é pq ele está em draft. Veja se o post não está com `draft = true` na frontmatter do post.

**Comment by cassiorampinelli** [comment]
Olá Luiz agradeço seu pronto feedback. Então, eu tentei inserir este draft=true ou draft:true no cabeçalho das páginas mas continuava dando erro. Aí observei que quando inserimos um post pelo Rstudio por meio do comando Addins->New Post, o arquivo Rmarkdown com o post estava sendo criado dentro de uma pasta chamada post. 

Contudo, observei que os seus posts modelos estavam dentro de uma outra pasta chamada posts (com "s") . O que fiz foi manualmente copiar o post que foi gerado na pasta post (sem "s") e inserir na pasta posts (com "s") e aí o novo post foi atualizado na página principal, juntamente com os outros modelos. Deve haver uma forma de automatizar isso, mas como não sou nenhum expert, por enquanto, esta “gambiarra” resolveu o meu problema. Mais a frente vou ver se dedico umas horinhas para entender melhor a raiz do problema e tentar automatizar isso.

Em relação ao uso do Rstudio, eu não entendo muito de html, ou Hugo, mas tenho uma certa noção de R e venho usando o Rstudio e o pacote Rmarkdown, aí descobri que com este pacote: https://bookdown.org/yihui/blogdown/ do R, via Rstudio é possível criar websites usando a estrutura do Rmarkdown, em vez de utilizar o Hugo ou HTML diretamente. Este pacote é relativamente novo, mas acredito que tem um enorme potencial de se expandir entre os usuários do R / Rstudio. 
Este vídeo é muito bacana https://www.youtube.com/watch?v=CjTLN-FXiFA e ajuda para quem tem uma certa familiaridade com o Rstudio e vem usando o pacote Rmarkdown para criar um website fazendo uso das capacidades do Hugo via interface Rstudio.

Obrigado mais uma vez pela atenção.

**Comment by luizdepra** [comment]
Interessante, vou dar uma olhada nesse projeto depois.
Mas, sobre a opção `draft` ela tem que estar como `false`. Ou seja, ela não é mais só um rascunho. E sobre a pasta, o correto é estar dentro de `posts` mesmo.
