### ISSUE TITLE
Multi Language Title Menu And post's not working propperly.

### ISSUE THREAD

**Issue by NicTanghe** [luizdepra/hugo-coder#159]
When i try to use multylangual mode the theme stops working.
I Have Multiple issues

*When i select a different language it only works for one selection.

*When i click the title it gives Me the following view.

https://i.imgur.com/Z5yhgXT.png

* when i select blog it gives me the standard FTP view

Name | Size | Date Modified
-- | -- | --
./ |   | 2019-03-11 21:54:50
../ |   | 2019-03-11 21:54:50
dummy/ |   | 2019-03-11 21:54:50

**Comment by luizdepra** [comment]
Can you share your configuration or repository?

**Comment by luizdepra** [comment]
No response. Closing.
