### ISSUE TITLE
not loading layouts and themes

### ISSUE THREAD

**Issue by iamrajiv** [luizdepra/hugo-coder#160]
After I use `hugo` command to generate the `index.html` in Public Folder and open the `index.html`  in Public Folder the site load as this
![1](https://user-images.githubusercontent.com/42106787/54493231-6b8a7680-48f3-11e9-9aff-836d9f600e63.JPG)

But in hugo server i.e. `http://localhost:1313/` the site load as this
![2](https://user-images.githubusercontent.com/42106787/54493246-9674ca80-48f3-11e9-9499-d116ce9c51bc.JPG)

Please help me on this issue

**Comment by josephting** [comment]
It's highly likely that `index.html` is trying to load the stylesheet from `http://localhost:1313/css/coder.css` depending on your `baseURL` in your site config.
If the server is not up and running, the stylesheet can't be loaded.

If `baseURL` is not set, it'll try to load `/css/coder.css` which could probably be `file:///css/coder.css`.

You want to first set your `baseURL` according to where you want to host your website at before you generate your site with `hugo`.

**Comment by iamrajiv** [comment]
@josephting are you talking about `base URL` in `config.toml` file. Means I have to make repo on GitHub and upload the `public` files in the repo and then set the `base URL` like `xyx.github.io` and then run the link will this work?

**Comment by josephting** [comment]
> are you talking about `base URL` in `config.toml` file. 

Yes.

> Means I have to make repo on GitHub and upload the `public` files in the repo and then set the `base URL` like `xyx.github.io` and then run the link will this work?

Not necessarily. It depends on where you want to deploy your site to. I'm just letting you know that the style may not get loaded properly if you're accessing your site using a different URL from the `baseURL` set in `config.toml`.

**Comment by luizdepra** [comment]
> Not necessarily. It depends on where you want to deploy your site to. I'm just letting you know that the style may not get loaded properly if you're accessing your site using a different URL from the `baseURL` set in `config.toml`.

Or accessing the site without a webserver, by opening the index.html file or so.

**Comment by sfrechette** [comment]
> It's highly likely that `index.html` is trying to load the stylesheet from `http://localhost:1313/css/coder.css` depending on your `baseURL` in your site config.
> If the server is not up and running, the stylesheet can't be loaded.
> 
> If `baseURL` is not set, it'll try to load `/css/coder.css` which could probably be `file:///css/coder.css`.
> 
> You want to first set your `baseURL` according to where you want to host your website at before you generate your site with `hugo`.



> > Not necessarily. It depends on where you want to deploy your site to. I'm just letting you know that the style may not get loaded properly if you're accessing your site using a different URL from the `baseURL` set in `config.toml`.
> 
> Or accessing the site without a webserver, by opening the index.html file or so.

I watched all videos online on youtube, tried all from different post online and still when published to GitHub pages the css looks like missing!!!! the format of the site is not working like on localhost:1313... and yes I have changes the baseurl in my config.toml still no avail...

**Comment by sfrechette** [comment]
> > It's highly likely that `index.html` is trying to load the stylesheet from `http://localhost:1313/css/coder.css` depending on your `baseURL` in your site config.
> > If the server is not up and running, the stylesheet can't be loaded.
> > If `baseURL` is not set, it'll try to load `/css/coder.css` which could probably be `file:///css/coder.css`.
> > You want to first set your `baseURL` according to where you want to host your website at before you generate your site with `hugo`.
> 
> > > Not necessarily. It depends on where you want to deploy your site to. I'm just letting you know that the style may not get loaded properly if you're accessing your site using a different URL from the `baseURL` set in `config.toml`.
> > 
> > 
> > Or accessing the site without a webserver, by opening the index.html file or so.
> 
> I watched all videos online on youtube, tried all from different post online and still when published to GitHub pages the css looks like missing!!!! the format of the site is not working like on localhost:1313... and yes I have changes the baseurl in my config.toml still no avail...

Got it working... make sure to put http**s**://xxxx.github.io in your baseurl!!!!

**Comment by iainsmith** [comment]
Is there any reason, these can't be relative links?

**Comment by iamrajiv** [comment]
@sfrechette Thankyou changing base URL to ` https://xxxx.github.io`  works for me earlier I was using different base URL as ` https://xxxx.github.io/repository name`
