### ISSUE TITLE
Changing Favicon

### ISSUE THREAD

**Issue by aaronkjones** [luizdepra/hugo-coder#163]
I cannot figure out how to change the favicon. I added the following line in the config.toml and added an image in the `static/img/` directory, but it does not change the favicon.

`favicon_16 = "/img/favicon-16x16.png"`

**Comment by luizdepra** [comment]
Try adding a 32x32 version of your favicon too.

`favicon_32 = "/img/favicon-32x32.png"`

Your browser is probably using the default 32x32 favicon.

**Comment by aaronkjones** [comment]
Thank you. That solved it.
