### ISSUE TITLE
Multi Language lang code

### ISSUE THREAD

**Issue by d-dandrew** [luizdepra/hugo-coder#165]
I found a problem the `<html lang="langcode">` doesn't work correctly for me 
It always show `<html lang="en">`
I use the theme in multi language mode 

Maybe the `<html lang="{{ .Site.LanguageCode }}">` from  /layouts/_default/baseof.html should be `<html lang="{{ .Site.Language.Lang }}">` 

according to the [hugo document](https://gohugo.io/variables/site/#site-variables-list)

And this will change the lang attribute globally according to what lang of the page you are viewing
this issue can also be found in the demo site:  
view-source:https://themes.gohugo.io//theme/hugo-coder/pt-br/
the `html lang` shows "en" instead of "pt-br"

**Comment by luizdepra** [comment]
Hmm... interesting.
Can you make a PR to fix it?

**Comment by d-dandrew** [comment]
fixed
