### ISSUE TITLE
how to link to custom heading with social icons

### ISSUE THREAD

**Issue by peterbeck** [luizdepra/hugo-coder#167]
I'd like to add a contact icon with [params.social] which links to a heading on a page.
adding "url = /about" (which is a page) works fine, but adding /about/#contact (which is a heading inside the page) doesn't work. Am i missing anything ?

**Comment by luizdepra** [comment]
I don't know if this theme or Hugo supports this feature. I never tried.
Have you come across another theme that does what you want?
If I have an example I can use it as a base.

**Comment by luizdepra** [comment]
I don't know if you are still looking for a solution, but I found [this question](https://discourse.gohugo.io/t/creating-anchors-in-hugo-pages-solved/9552/7).
