### ISSUE TITLE
Homepage doesn't render in ie11

### ISSUE THREAD

**Issue by bjnoel** [luizdepra/hugo-coder#170]
All the homepage content is bunched up in ie11:

http://puu.sh/Ddugj/48a25ae995.png

**Comment by luizdepra** [comment]
IE 11 is an old browser and it doesn't handler `flex` rules properly.
I don't think it is worth trying to fix this problem. But, if you know how to fix it without adding another JS library or changing everything, please submit a PR with the fix.

**Comment by luizdepra** [comment]
No response, so... closing it.
