### ISSUE TITLE
Table Of Contents

### ISSUE THREAD

**Issue by khaf** [luizdepra/hugo-coder#178]
Thanks for the great theme. Love it!

Sorry if this issue sounds too stupid, I'm a beginner in Hugo. Nevertheless, I have utterly failed to add a TOC to content pages (like blog). After hours of search and different approaches, I hereby give up :)

What am I missing? Why adding `{{ .TableOfContents }}` doesn't do the trick anywhere?

**Comment by luizdepra** [comment]
I tried it here and it worked. I followed [this doc page](https://gohugo.io/content-management/toc/), I added the `{{ .TableOfContents }}` into `partials/posts/single.html`.
Well, it will need some styling changes and a front-matter config to activate/deactivate the ToC would be great too.
Give it a try. :)

**Comment by khaf** [comment]
This is great! I had put that same snippet everywhere, except in that file.

Thank you very much @luizdepra, this theme is great. Much appreciated.

**Comment by pinpox** [comment]
> I tried it here and it worked. I followed [this doc page](https://gohugo.io/content-management/toc/), I added the `{{ .TableOfContents }}` into `partials/posts/single.html`.
> Well, it will need some styling changes and a front-matter config to activate/deactivate the ToC would be great too.
> Give it a try. :)

It's quite a while ago, but what did you do exactly to show a TOC? I don't seem to have a `themes/hugo-coder/layouts/partials/posts/single.html` file, do I need to create it? If so what content does it need to work at all?

**Comment by luizdepra** [comment]
@pinpox, It should go [here](https://github.com/luizdepra/hugo-coder/blob/master/layouts/posts/single.html#L34) before `{{.Content}}`.

**Comment by pinpox** [comment]
@luizdepra See my comment in https://github.com/luizdepra/hugo-coder/issues/415#issuecomment-765635280
