### ISSUE TITLE
`inverted = true` doesn't build properly

### ISSUE THREAD

**Issue by gfairchild** [luizdepra/hugo-coder#179]
I set `inverted = true` in my `config.toml`, and I get this error:

```
Building sites … ERROR 2019/05/09 04:24:20 error: failed to transform resource: TOCSS: failed to transform "style.coder-inverted.css" (text/x-scss): this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Total in 241 ms
Error: Error building site: logged 1 error(s)
```

I'm running the latest Hugo version:

```
$ hugo version
Hugo Static Site Generator v0.55.5-A83256B9 freebsd/amd64 BuildDate: 2019-05-02T13:04:08Z
```

Is this something I'm doing wrong, or is this a bug in the theme?

**Comment by luizdepra** [comment]
You'll need Hugo's extended version. [This](https://gohugo.io/getting-started/installing/#fetch-from-github) is how you build Hugo with the extended flag.
