### ISSUE TITLE
Inverted colors

### ISSUE THREAD

**Issue by janmasarik** [luizdepra/hugo-coder#18]
First I would like to thank you for neat theme! 

Second, I would like to contribute with "inverted" color scheme which could be specifiable with config parameter.  You can check example of it [here](https://masarik.sh). Maybe a bit more grey (something like #101010), i would let that up to you. 

I came up with 2 solutions:

1. Create separate css file or split css files to colors and the rest
2. Put everything to <style> tags and edit css within template - https://discourse.gohugo.io/t/generating-dynamic-css-based-on-config-file/1279/8

Would you be up for it? Do you have any suggestions / recommendations?

**Comment by janmasarik** [comment]
So something like 
```
<style>
.colors {
    background-color: black;
    color: white;
} 
</style>

<body class="colors">
```
? I'm not very good with CSS, but would definitely like to contribute with this one.

**Comment by janmasarik** [comment]
Yeah, thanks! That could work.

I will need help with code highlighting though. Do you think that this is readable https://masarik.sh/posts/secret-pickle/ ? 

If not, what would you suggest? Should I try to come up with some custom highlighting?

**Comment by luizdepra** [comment]
It is redable. But why not use a black-letter-over-white-background highlight?

**Comment by luizdepra** [comment]
Yep, this is the way to accomplish what we want.
I just have test it and it works great.

Just some fixes:

1. We'll use the `inverted-colors` class the `body` element. So, no need  to put `color` and `background-color` inside `body`.

```
.inverted-colors {
  color: @inverted-fg-color;
  background-color: @inverted-bg-color;
  // and so on ...
}
```

2. We only need to change the colors. We can avoid re-declaring sizes and styles.

`border-left: 2px solid @inverted-darker-bg-color;` -> `border-left-color: @inverted-darker-bg-color;`

**Comment by luizdepra** [comment]
Hey, @janmasarik. Are you still willing to do these inverted color feature?
I can do it if you have another plans.

**Comment by janmasarik** [comment]
Sorry, I had too much work in recent weeks. I can try to get into this on Fri. If I won't respond here / won't create PR, feel free to take it:). 

Thanks for patience!

**Comment by luizdepra** [comment]
No problem, @janmasarik. I was just checking if you still have interest, ok?

**Comment by luizdepra** [comment]
We should continue discussing this issue at #54.
