### ISSUE TITLE
mailto url in the header

### ISSUE THREAD

**Issue by StevenMagdy** [luizdepra/hugo-coder#180]
How to provide a mailto url in the header like `url = "mailto:myMail@gmail.com"`?
when I type it, it becomes relative url.

**Comment by luizdepra** [comment]
Which header are you referring about? The HTML's `head`? The theme's top menu? Or post's titles?

**Comment by StevenMagdy** [comment]
The top menu (blog/contact me/about).

**Comment by luizdepra** [comment]
I see. So, I think we will need to change [this line](https://github.com/luizdepra/hugo-coder/blob/master/layouts/partials/header.html#L12). Change `relLangURL` to `safeURL`.
I don't remember why `relLangURL` is there, but think we don't need it.

Can you test it and open a PR if it works?

**Comment by erickgnavar** [comment]
I was trying to use `mailto` too. Changing `relLangURL` to `safeURL` works but it loses multi language support(url prefix). Maybe is there another way?

btw thanks for the theme

**Comment by luizdepra** [comment]
@erickgnavar removing `relLangURL` is not a problem. You can always override your menu links for every lang and put the correct URL.
But, probably there is a way to detect if the URL is relative ou absolute and so apply the correct function.
