### ISSUE TITLE
where should I save the images? to be called later from posts

### ISSUE THREAD

**Issue by anyosa** [luizdepra/hugo-coder#184]
Hi! Thanks for the template! However I'm kind of struggling to place images in other .md files. Should I put them in /static and then called from something like:

`
<img src="../static/img/my_image.png" width="400">`

**Comment by luizdepra** [comment]
Yep. That is exactly what you should do.

**Comment by anyosa** [comment]
I did it, but no success 😞 

https://anyosa.github.io/projects/

**Comment by luizdepra** [comment]
Sorry. I failed to notice the src content.
It should be `/img/my_image.png`.
The `static` folder content is copied to the root folder when the site is built.

**Comment by anyosa** [comment]
it's working! thanks!

**Comment by luizdepra** [comment]
YW!
