### ISSUE TITLE
Unable to add Disqus comments

### ISSUE THREAD

**Issue by pylenin** [luizdepra/hugo-coder#186]
I am unable to add disqus comments to my website that I built using this theme. You can find my repo at https://github.com/pylenin/purple-blue
Suggest me what should I change.

**Comment by luizdepra** [comment]
A coder was build to use two archetypes: Pages and Posts. Pages don't display comments and Posts do it.
So, all your articles are been built as pages. This is happening because they aren't inside a `posts` folder.
Unfortunately, you'll need to change your `content` folder to something similar to the [exampleSite structure}(https://github.com/luizdepra/hugo-coder/tree/master/exampleSite/content). And, this will change your articles URL to `/posts/article-slug/`, but you can change this behavior by setting `permalinks` in your config file.

**Comment by pylenin** [comment]
Can't I keep the url same and make the relevant changes ? Basically naming posts as blogs someway?

**Comment by luizdepra** [comment]
Yes, you can set a permalink. I think you'll need to configure it like this:
```
[permalinks]
  posts = "/blogs/:title"
```

**Comment by pylenin** [comment]
My website url is  - https://www.pylenin.com

**Comment by luizdepra** [comment]
have you renamed the `content/blogs` folder to `content/posts`?
I cloned your site and did this, ant it works.

**Comment by pylenin** [comment]
Yes. I did. have you only changed there? Or should I change the url in config.toml as well ?
<img width="612" alt="Screen Shot 2019-06-11 at 3 50 33 PM" src="https://user-images.githubusercontent.com/44732615/59277540-ae44bc00-8c60-11e9-8340-e3186883fa5b.png">

**Comment by luizdepra** [comment]
Yeah. This is another problem. The post list page URL will be `/posts/`.
I don't know if there is a way to change it to `/blogs/`. I need to research.

**Comment by pylenin** [comment]
May be use aliases in some way !!

**Comment by luizdepra** [comment]
You're right!
I created a `_index.md` file inside `posts` folder with the following content:
```
---
title: Blogs
aliases:
    - /blogs/
---
```
Works like a charm.

**Comment by pylenin** [comment]
Does it ? I still see it as `https://www.pylenin.com/posts/`. 
Here is my updated repo - https://github.com/pylenin/purple-blue

**Comment by luizdepra** [comment]
Yeah, my bad. It redirects to `/posts/`.

**Comment by luizdepra** [comment]
I think I got it. Try this:
```
---
title: Blogs
url: /blogs/
---
```

**Comment by pylenin** [comment]
In `_index.md`?

**Comment by luizdepra** [comment]
Yep. Just it.

**Comment by pylenin** [comment]
You rock bro !!
Thanks for supporting !!
Also thanks for this amazing theme.

**Comment by pasindujr** [comment]
Hi @pylenin, I set my `_index.md` file inside blog folder as you described here and it works as `sitename.com/blog`. But when I go to a single post inside that blog folder, the link resets to "sitename.com/posts/post1". How can I change that to `sitename.com/blog/post1`?

**Comment by pylenin** [comment]
![IMG_20210503_151737__01](https://user-images.githubusercontent.com/44732615/116863384-dd34f400-ac23-11eb-8afc-32a586559010.jpg)
You mean this?? In config.toml?

**Comment by pasindujr** [comment]
@pylenin, yes thank you!
