### ISSUE TITLE
Is it possible to add an author section to this theme?

### ISSUE THREAD

**Issue by pylenin** [luizdepra/hugo-coder#190]
A lot of python developers are now collaborating to add blogs to [www.pylenin.com](www.pylenin.com). Is it possible to add an authors section to this theme? That would be very convenient for us.

**Comment by luizdepra** [comment]
Not out of the box right now, but is feasible.
Do you want something like this [post](https://www.netlify.com/blog/2018/07/24/hugo-tips-how-to-create-author-pages/)? It is just a new archetype (author), a new partial template and a configuration to activate/deactivate the feature.
Could you try this and open a PR?

**Comment by pylenin** [comment]
Sure !! I will do that asap !!
