### ISSUE TITLE
Inconsistant target for social icons

### ISSUE THREAD

**Issue by alrayyes** [luizdepra/hugo-coder#191]
Github and Twitter links on the homepage seem to open in a new tab. Other social links don't. Where can this behavior be set?

**Comment by luizdepra** [comment]
Weird. This problem doesn't happen here. Could you share your configuration and what browser are you using?

**Comment by alrayyes** [comment]
I'm using firefox and I even have the same issue on the [demo page](https://themes.gohugo.io/theme/hugo-coder/). Twitter & Github launch in new tab, the other links launch in the current tab. It is weird. On my ipad everything opens in the same tab. For now i'll put it down to an extension issue on my part.

**Comment by alrayyes** [comment]
Oh, wait. It's [Multi account container](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) plugin that's causing this. I set it up to open github/twitter in their own tabs/containers. Nothing to see here :-)
