### ISSUE TITLE
Tags and Categories Taxonomy

### ISSUE THREAD

**Issue by ChrisShire** [luizdepra/hugo-coder#197]
I'm pretty new to Hugo, but I'm having trouble getting tags and categories to work. I have placed
```
[taxonomies]
category = ["category1", "category2"]
tag = [
  "tag1",
  "tag2",
]
```
into the config.toml of the site, and 
```
category = ["category1"]
tags = ["tag1", "tag2"]
```

into the top of posts. The categories do not show up, and the tags when clicked on lead to a 404 page...

I'm not sure what I've done incorrectly, if anyone could provide some advice I would much appreciate it.

**Comment by luizdepra** [comment]
Hi! I think this is simple to solve.
First, you must declare which taxonomy you want to use, `tags` and `categories` in your case. Put something like this in your `config.toml`:

```
[taxonomies]
    category = "categories"
    tag = "tags"
```

And in your post front matter:

```
categories = ["category1"]
tags = ["tag1", "tag2"]
```

Notice that both taxonomies are in the plural form here. Also, make sure you are enclosing the front matter with TOML identity tokens, `+++`.

**Comment by ChrisShire** [comment]
Thanks for the help dude, It's not working on my original install so I suspect I've screwed a setting somewhere. I created a new install and found your instructions worked great, so I'll just have to work on that. Thanks man. Issue closed.

**Comment by rchaganti** [comment]
I am facing the same issue. I tried re-creating the site and adding my site content but the categories and tags are not appearing in the posts. I have the config.toml exactly as mentioned in this thread. Any ideas what else I need to check. It was working before I added the recent set of posts.

**Comment by clement-pannetier** [comment]
Hi @rchaganti, I cloned your repo and saw that you changed the posts route from `posts` to `blog` as you can see [here](https://github.com/rchaganti/blog/commit/9fdee6bab3073da729506c7a91d36a5441bbc26c#diff-618063036395fe9ee107f22b46c9eadeR96).

The problem is that the posts are rendered with this file `layouts/posts/single.html` not `layouts/blog/single.html` which does not exists. Thus your blog posts are rendered using the default `single.html` from `layouts/default/` folder.

**Comment by rchaganti** [comment]
@clement-pannetier You hit it! Thank you so much. I renamed posts to blog to ensure that the domain  I am migrating will not break any existing links. This is working now.

**Comment by jorgesolatre** [comment]
> I am facing the same issue. I tried re-creating the site and adding my site content but the categories and tags are not appearing in the posts. I have the config.toml exactly as mentioned in this thread. Any ideas what else I need to check. It was working before I added the recent set of posts.

Same problem right now, if I find any solution I will tell you, hope the same from you bro.

**Comment by jorgesolatre** [comment]
> I am facing the same issue. I tried re-creating the site and adding my site content but the categories and tags are not appearing in the posts. I have the config.toml exactly as mentioned in this thread. Any ideas what else I need to check. It was working before I added the recent set of posts.

Can you help me please, I have the same problem with my blog and projects pages.
I don't what Can I do
The tags and categories are not show

**Comment by jorgesolatre** [comment]
> Hi @rchaganti, I cloned your repo and saw that you changed the posts route from `posts` to `blog` as you can see [here](https://github.com/rchaganti/blog/commit/9fdee6bab3073da729506c7a91d36a5441bbc26c#diff-618063036395fe9ee107f22b46c9eadeR96).
> 
> The problem is that the posts are rendered with this file `layouts/posts/single.html` not `layouts/blog/single.html` which does not exists. Thus your blog posts are rendered using the default `single.html` from `layouts/default/` folder.

Thanks so much, I fixed with the blogs pages, but with projects? What is the correct render?, in the original he only puts projects/ and add his website url

**Comment by luizdepra** [comment]
> Thanks so much, I fixed with the blogs pages, but with projects? What is the correct render?, in the original he only puts projects/ and add his website url

There is no special rendering for projects yet. You can put your project articles in the root `content` folder, or even create a subfolder with any name, it will always be rendered as a normal page. The only special case so far is `posts`.
