### ISSUE TITLE
Disqus is never rendered

### ISSUE THREAD

**Issue by naim94a** [luizdepra/hugo-coder#199]
When building with Hugo extended v0.55.6, the following warning appears:
```
WARNING: calling IsSet with unsupported type "ptr" (*hugolib.SiteInfo) will always return false
```

This is because of the line on disqus.html:
```
{{- if and (isset .Site "disqusshortname") (not (eq .Site.DisqusShortname "" )) (eq (.Params.disable_comments | default false) false) -}}
```
which will never allow Disqus to be inserted into rendered content.

**Comment by luizdepra** [comment]
Nice, thank you.
I should have double-checked the change in #198.

**Comment by naim94a** [comment]
Glad to help :)
