### ISSUE TITLE
Metadata + Taxonomy not shown when changing posts url

### ISSUE THREAD

**Issue by NissesSenap** [luizdepra/hugo-coder#204]
First of all thanks for a great theme!
Not sure if this is a hugo issue or a theme issue.

I had issues seeing the metadata + taxonomy in my posts.

![image](https://user-images.githubusercontent.com/14774899/62616921-f571c500-b910-11e9-9a97-fb1e9c37fa6b.png)

After a bunch of testing a realized that the issue was in my menu url:s

I had (wanted the url to be the same as the text that i klick on):
[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/blog/"

If i use this config the above metadata isn't seen but if i change to:
[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

![image](https://user-images.githubusercontent.com/14774899/62616619-4df49280-b910-11e9-865c-8be62fa43637.png)

Then it works great.

Is there any way to fix this with current functionality or is it a bug?
Obviously not a super big issue but I would like to use /blog as my url instead of /posts.

Thanks in advance.

**Comment by a1x42** [comment]
If you are using the latest version, then remove the trailing slash i.e. try the following instead: url = “blog/“

**Comment by NissesSenap** [comment]
Thanks for fast reply.
I gave it a try but still no luck.

I use hugo version: Hugo Static Site Generator v0.56.3-F637A1EA linux/amd64 BuildDate: 2019-07-31T12:51:09Z

Tried both:
        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "blog

and 

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "blog/

I have pulled down the latest theme from master commit: dea81ca4343531e3a38fcaf9a605df1cacd096aa

**Comment by a1x42** [comment]
Hum, not sure about the linux packages. Never used them. 

Have you checked what link is actually generated? search index.html in the public folder.

**Comment by luizdepra** [comment]
This problem is happening because your posts are being rendered as pages.
When you put your posts inside `posts` folder you tell  Hugo to render them using the Posts archetype. When you put them inside `blog`, there is no archetype with this name, so Hugo render it with the default one, Pages.

I think the solution we discussed in #186 will do the trick for you.

**Comment by NissesSenap** [comment]
Yes it worked, thanks for the fast help both of you.
