### ISSUE TITLE
Posts as homepage , homepage as a page

### ISSUE THREAD

**Issue by projectstravel** [luizdepra/hugo-coder#211]
Hi, 

I'd like to make the blog page as the main entry point of my domain. I'm trying to tweak the theme to achieve 2 things:

1.  have the list of posts as a homepage .
2. have the "official" homepage accessible but via an other url, let's say `/about` )

So far I got the posts as homepage by changing the `layout/index.html` to :
```
{{ define "content" }}
  {{ partial "list.html" . }}
{{ end }}
```

But I can't figure out how to have the "home.html" accessible via an other url. 

Thank you if anyone can point me to the right direction!

**Comment by luizdepra** [comment]
Hmmm... I think the easiest way is creating a archetype (like posts and pages) for your `about` page.
So you can use `type`[1] on the page front matter to use the new archetype and `url`[2] to set a custom address.

[1] https://gohugo.io/content-management/types/#define-a-content-type
[2] https://gohugo.io/content-management/urls/

**Comment by projectstravel** [comment]
Thanks @luizdepra , I'll give it a try this week and paste here the changes to help anyone else that would like the same changes. 

Cheers!

**Comment by luizdepra** [comment]
Well, I think this one is solved.

**Comment by 0xMH** [comment]
Did you manage to do it? @projectstravel
