### ISSUE TITLE
The mathjax used in `layout/partial` is outdated

### ISSUE THREAD

**Issue by foodtooth** [luizdepra/hugo-coder#214]
Hi, thank for your great theme, I'm really happy using it :)
According to the[ mathjax doc](http://docs.mathjax.org/en/latest/web/start.html#using-mathjax-from-a-content-delivery-network-cdn), the recommended way to use mathjax from cdn is
```
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script>
```
which will always return latest version.

Can we have the latest replacing the current one?

**Comment by luizdepra** [comment]
Sure. Could you open a PR applying this change?

**Comment by foodtooth** [comment]
> Sure. Could you open a PR applying this change?

https://github.com/luizdepra/hugo-coder/pull/215 PR created and waiting for review :)

**Comment by luizdepra** [comment]
Done!
