### ISSUE TITLE
Open social icons' url in new tab

### ISSUE THREAD

**Issue by gary-ruizhang** [luizdepra/hugo-coder#216]
How can I make social icons' url open in a new tab by default? 
`[blackfriday] hrefTargetBlank = true ` only work for url in markdown file, not the homepage.

**Comment by luizdepra** [comment]
I think there is no escape from adding `target="_blank"` into the icon's `a` tag [here](https://github.com/luizdepra/hugo-coder/blob/master/layouts/partials/home.html#L12-L20).

I'm just curious. Why do you want to change the default browser behavior? Wouldn't be better to let the user decide if she/he want to open the link in another tab/window or not?

**Comment by gary-ruizhang** [comment]
You're right. I used to think internal link: open in the default way, external link: open in a new tab. Should let the user decide that.
