### ISSUE TITLE
BlackFriday configuration causing Google Analytics script not loading

### ISSUE THREAD

**Issue by clement-pannetier** [luizdepra/hugo-coder#217]
Hi,

Yesterday, I tried to implement the BlackFriday markdown rendering into my config.toml but I found later on that the Google Analytics script won't load anymore.

Each time I add these lines below, the script disappear !

I added these lines in my config.toml file :

`[blackfriday]
fractions = false
smartypantsQuotesNBSP = true`

I think that it's not related to this theme because I've tested it, but I want to know if anywone has ever experienced that.

PS: Sorry for my English ;)

**Comment by clement-pannetier** [comment]
UP ! @luizdepra

**Comment by luizdepra** [comment]
I didn't have time to test this issue yet, but it doesn't look like a problem of the theme.
Did you try another theme with the same configuration?
If this is a Hugo's bug you can look for help [here](https://discourse.gohugo.io/) too.

**Comment by clement-pannetier** [comment]
Thank's for the reply, no problem I understand.

I tried with the default ananke theme used [here](https://gohugo.io/getting-started/quick-start/) and others.

I just wanted to know if anywone has ever experienced that because in the forum you point me at, there are no similar issues, same in the gohugo github repository.

**Comment by luizdepra** [comment]
Do you still have this problem?
I think Hugo replaced blackfriday in newest versions.

**Comment by clement-pannetier** [comment]
Hi, I no longer use blackfriday because it was not necessary.

I posted an issue [here](https://discourse.gohugo.io/t/blackfriday-configuration-causing-google-analytics-script-not-loading/21104), but since that post my account is "temporarily on hold", so I can't reply.

I'm gonna try to update my website to the lastest stable version of hugo soon.

**Comment by clement-pannetier** [comment]
Ok, after tests, GoldMark don't cause the same problems as BlackFriday but the features are not the same.

I close the issue, anyway it's not the template fault...
