### ISSUE TITLE
Enable RSS feed?

### ISSUE THREAD

**Issue by utkarsh2102** [luizdepra/hugo-coder#224]
Hey,  
While this is a lovely theme, I'm yet not able to use this because it lacks RSS feed for the blogs.  
Could you add the same?

**Comment by jaredmo** [comment]
For me, the index.xml file generates correctly. However, the RSS icon doesn't display on the desktop version of the site. It does on mobile, which is odd.

**Comment by luizdepra** [comment]
Maybe it is a browser cache problem and the icon is not loading?

**Comment by jaredmo** [comment]
I’ve cleared the cache and used different browsers. Same result.

**Comment by jaredmo** [comment]
I clicked on your site above as well and noticed the RSS icon wasn’t showing next to other social links.

**Comment by luizdepra** [comment]
![Screenshot from 2020-01-23 14-29-04](https://user-images.githubusercontent.com/1427376/73008200-d0a0d980-3dec-11ea-8f7a-ccc190920e4f.png)
Looks fine here.

**Comment by jaredmo** [comment]
That must be mobile web. This is the desktop version that I am seeing. 
![image](https://user-images.githubusercontent.com/27711028/73008340-f8377800-3dd3-11ea-905d-cc85147fa3f7.png)

**Comment by luizdepra** [comment]
No, it's not.
Try to open a browser instance without any addons (safe mode).

**Comment by jaredmo** [comment]
That worked. I run uBlock Origin which blocks google-analytics.com. Disabling that extension fixed the issue. Thanks for troubleshooting.
