### ISSUE TITLE
Auto-switch between Dark and Light modes

### ISSUE THREAD

**Issue by ariejan** [luizdepra/hugo-coder#226]
With some simple vanilla javascript, it's possible to automatically switch between Light and Dark mode, based on the user's OS preference. 

## Proposal

Add an option to `config.toml` like this:

`dark_mode = "auto"` to (by default) automatically detect the user preference.

This could replace the `inverted` option:

`dark_mode = "light"` to always select light mode
`dark_mode = "dark"` to always select dark mode

## Impact

This would remove the `inverted` option, and add a new `dark_mode` option. It might be possible to re-use the `inverted` option, but the naming is a bit off. It would also mix boolean values with a string value.

## Implementation

The implementation is straight-forward. I'm currently doing this already with some custom JavaScript at https://www.devroom.io (try switching between light and dark mode on your device).

At the moment you need to set `inverted = true` to include the inverted CSS. The javascript will then add/remove the `.inverted` class to `body`, based on what preference it detected. If no preference can be found, the script could default to light or dark, or set either one based on the local user's time. 

@luizdepra Please let me know you thoughts on this, I'd be happy to create a PR for this.

**Comment by clement-pannetier** [comment]
Hi,

I made a similar feature on my website, you can see it [here](https://clementpannetier.dev).
I added a button to toggle between the light and dark mode and it also works with the user preference in Windows settings.

I've been inspired by this [post](https://web.dev/prefers-color-scheme/) and this [hugo theme](https://themes.gohugo.io/hugo-theme-hello-friend/)

**Comment by ariejan** [comment]
@clement-pannetier that's even better!

**Comment by luizdepra** [comment]
This is a interesting feature.
I would like to avoid using javascript, I don't know if it is possible.

I would be glad if you could implement this feature. Using user preferences looks really nice, but I think we still need a way to change the colors by clicking somewhere. (Maybe in the page footer?) And a way to save the "use preference" when he/she changes the color scheme. (Local Storage?)

**Comment by ariejan** [comment]
@luizdepra It's possible to use CSS media queries to select light mode or dark mode, but without JS, users will not be able to interact with it. The choice is do you want it to happen automagically, or do you want to give the visitor some control on the fly? I would prefer the automagic solution, as the user already expressed their preference for one mode or the other. 

For reference: https://tombrow.com/dark-mode-website-css

**Comment by thesmiley1** [comment]
I also like the simplicity of the automagic solution.

**Comment by luizdepra** [comment]
Oops, closed by mistake.

**Comment by qsvtr** [comment]
> Hi,
> 
> I made a similar feature on my website, you can see it [here](https://clementpannetier.dev).
> I added a button to toggle between the light and dark mode and it also works with the user preference in Windows settings.
> 
> I've been inspired by this [post](https://web.dev/prefers-color-scheme/) and this [hugo theme](https://themes.gohugo.io/hugo-theme-hello-friend/)

Can you share how did you do this feature ? :)

**Comment by clement-pannetier** [comment]
> > Hi,
> > I made a similar feature on my website, you can see it [here](https://clementpannetier.dev).
> > I added a button to toggle between the light and dark mode and it also works with the user preference in Windows settings.
> > I've been inspired by this [post](https://web.dev/prefers-color-scheme/) and this [hugo theme](https://themes.gohugo.io/hugo-theme-hello-friend/)
> 
> Can you share how did you do this feature ? :)

You can see it on my GitLab repo : https://gitlab.com/clement-pannetier/clementpannetier.dev

**Comment by qsvtr** [comment]
> > > Hi,
> > > I made a similar feature on my website, you can see it [here](https://clementpannetier.dev).
> > > I added a button to toggle between the light and dark mode and it also works with the user preference in Windows settings.
> > > I've been inspired by this [post](https://web.dev/prefers-color-scheme/) and this [hugo theme](https://themes.gohugo.io/hugo-theme-hello-friend/)
> > 
> > 
> > Can you share how did you do this feature ? :)
> 
> You can see it on my GitLab repo : https://gitlab.com/clement-pannetier/clementpannetier.dev

document.getElementById ('dark-mode-toggle') is not found yet the custom.css is loaded before the custom.js (and I added the svg in the header.html)

**Comment by clement-pannetier** [comment]
I don't see the toggle button on your website, can you update your code or make a branch on your git

**Comment by qsvtr** [comment]
> I don't see the toggle button on your website, can you update your code or make a branch on your git

yes it's done, I added a window.onload = () => { ... } in custom.js 
PS: I work in local ;)

**Comment by clement-pannetier** [comment]
Ok, but one small mistake, you didn't change the hover color of the toggle button :)

How did you change your site without commiting to the github repo ?

**Comment by qsvtr** [comment]
> Ok, but one small mistake, you didn't change the hover color of the toggle button :)
> 
> How did you change your site without commiting to the github repo ?

Yes I saw that aha;)
It's on a new vps so for now I only zip that I unzip in the directory :D

**Comment by lthoerner** [comment]
Hey guys, I'm having a sort of related issue to this - I set `colorScheme = "dark"` in `hugo.toml`, but it does not actually set it to dark mode automatically, I have to click the button. Any ideas?

**Comment by luizdepra** [comment]
Hey, @lthoerner.

I use the dark theme on my site and it is working fine. See [here](https://github.com/luizdepra/luizdepra.dev/blob/main/config.toml#L33). I don't know, but shouldn't you be using `config.toml` instead of `hugo.toml`? I never heard about `hugo.toml`. This is a new name for the config file?
