### ISSUE TITLE
Date inside post page

### ISSUE THREAD

**Issue by mauricioabreu** [luizdepra/hugo-coder#232]
I am seeing an awkward behavior in single post pages.

There is a `meta` here that holds post metadata (date and reading time).

My site is using `hugo-coder` but I am not seeing these details on the page.

Example:
https://www.maugzoide.com/post/it-is-hard-to-be-a-better-human/

Post file:
https://raw.githubusercontent.com/mauricioabreu/blog/master/content/post/it-is-hard-to-be-a-better-human.md

Config file:
https://github.com/mauricioabreu/blog/blob/master/config.toml

Hugo version:
Hugo Static Site Generator v0.59.0/extended darwin/amd64 BuildDate: unknown

**Comment by mauricioabreu** [comment]
Also, tags are not visible.
Since that HTML is static, what could be causing it?
I installed hugo using a submodule and it looks up-to-date.

**Comment by josephting** [comment]
Posts files should be placed in `posts` directory, not `post`.
Note the 's'.

`blog/master/content/post`
should be renamed to
`blog/master/content/posts`

**Comment by mauricioabreu** [comment]
@josephting thank you so much! I don't know why it was `post`. I have this blog for years (changed theme days ago).

**Comment by josephting** [comment]
It's possible that your previous theme was using `post` instead.
It depends on the theme.

**Comment by mauricioabreu** [comment]
@josephting thank you! I did not know about the front matter and the type.
Already changed it here and it worked like a charm!
