### ISSUE TITLE
Support ORCID logo through fontawesome.

### ISSUE THREAD

**Issue by jme52** [luizdepra/hugo-coder#235]
ORCID (Open Researcher and Contributor ID) is the de facto standard for contributor identification in research and academic publishing.  Users of hugo-coder with an ORCID are likely to want to include a link to their ORCID profile through an ORCID logo in the same line as the fontawesome-provided github, linkedin, twiter, etc. logos.

Unfortunately, the fontawesome ORCID logo https://fontawesome.com/icons/orcid is not available in the version of fontawesome currently used by hugo-coder (v5.8.1).

Please update the fontawesome version to a newer one that supports the ORCID logo.

**Comment by luizdepra** [comment]
Closed by #236.
