### ISSUE TITLE
i18n translation used in layout files

### ISSUE THREAD

**Issue by tobiasehlert** [luizdepra/hugo-coder#237]
As right now, there are some translations in for example [i18n/de.toml](https://github.com/luizdepra/hugo-coder/blob/master/i18n/de.toml)

Should not files like [layouts/posts/list.html](https://github.com/luizdepra/hugo-coder/blob/master/layouts/posts/list.html) use the tags then, or maybe use newly added ones?

Would be awesome if the "Posts" word would be localized in the i18n file, if that now is the correct way to go. What else would the [i18n/de.toml](https://github.com/luizdepra/hugo-coder/blob/master/i18n/de.toml) file be useful for?

Maybe a little related to [issue 70](https://github.com/luizdepra/hugo-coder/issues/70)..

**Comment by luizdepra** [comment]
Yes, I probably need a `i18n` tag in the posts list template. And, of course, we need to add a translation entry in every language file.
I'm not 100% sure if this is everything we need to do, but it seems so. I need to test first.
