### ISSUE TITLE
Make code block with line number more compact?

### ISSUE THREAD

**Issue by bebound** [luizdepra/hugo-coder#246]
Currently, there is so much space in code with line number, and two code block are connected without padding.

<img width="331" alt="Screen Shot 2019-12-19 at 23 09 58" src="https://user-images.githubusercontent.com/2227874/71184648-0b2aca00-22b5-11ea-9261-fba3bfb20bd6.png">

Here is the url and src:
https://www.fromkk.com/posts/circular-import-in-python/
https://github.com/bebound/hugo_blog/blob/master/content/posts/circular-import-in-python.md

Sorry I'm not good at CSS, and don't know how to improve this.

**Comment by luizdepra** [comment]
Sure it is possible.
I'm kinda busy with other projects right now, but I'll try to take a look as soon as possible.
But anyone is free to help with this issue.
