### ISSUE TITLE
Disable menu button on mobile

### ISSUE THREAD

**Issue by yousifd** [luizdepra/hugo-coder#253]
If there are no menu options, the desktop theme works fine and doesn't show any items on the right side of the navigator. However, on mobile, the hamburger menu still shows up regardless. Is it possible to disable the menu on mobile if there are no menu items to show?

**Comment by luizdepra** [comment]
It is not possible to hide the button, yet.
We need to verify if there is any menu item and hide the menu container if not. It is kinda simple to do that, you only need to understand a bit of Hugo's templates.

I can try to do this fix later, but I'm kinda busy these days. Could you give it a try?
Anyone is free to help here too.
