### ISSUE TITLE
LaTeX code is not rendering properly in hugo posts

### ISSUE THREAD

**Issue by iamrajiv** [luizdepra/hugo-coder#255]
when I was making determinant in Hugo posts it rendered like this

<img width="131" alt="Screenshot 2020-01-29 at 2 12 39 PM" src="https://user-images.githubusercontent.com/42106787/73340885-8cf11880-42a1-11ea-9b31-b397cac956dc.png">

but it should be rendered like this

<img width="71" alt="Screenshot 2020-01-29 at 2 13 09 PM" src="https://user-images.githubusercontent.com/42106787/73340923-9da18e80-42a1-11ea-9173-e68035110b46.png">

The code I have used in both the cases is this
```tex
$$\left|
\begin{array}
&a&b \\ 
c&d \\ 
\end{array}
\right|$$
```

**Comment by luizdepra** [comment]
I'm gonna take a look soon.

**Comment by luizdepra** [comment]
Well, I don't know much about latex but... Shouldn't be you using `vmatrix` instead of `array`? Also there is an extra `&` before `a`.

```
$$\begin{vmatrix}
a & b \\ 
c & d \\ 
\end{vmatrix}$$
```

Another thing, are you using mathjax ou katex?

**Comment by iamrajiv** [comment]
@luizdepra I am using `KaTeX`. I don't think using `vmatrix` instead of `array` will do anything because I have used `vmatrix` it only creates the box of matrix or line like this `|` on both side which I have already implemented in `array` by using code `\left|` and `\right|` though I have tested with `vmatrix` and output is still same.

**Comment by luizdepra** [comment]
I think this is a katex bug. But I will try testing this later, ok?

**Comment by iamrajiv** [comment]
@luizdepra Yeah sure.

**Comment by luizdepra** [comment]
Well, I tried something and got it working with this code:

```
$$
\left|\begin{matrix} a&b \\\ c&d \end{matrix}\right|
$$
```

It seems you need a triple `\` to say that your will start a new line.

Also, if you're having too much trouble, try using mathjax (katex seems very buggy). You can try it replacing `katex = true` with `math = true`.

**Comment by iamrajiv** [comment]
thankyou @luizdepra

**Comment by iamrajiv** [comment]
can I use both `katex = true` and `math = true` in front matter? @luizdepra

**Comment by luizdepra** [comment]
I can put both, but I think they will conflict.
