### ISSUE TITLE
how to remove .[] at footer and  resize of image in markdown doesn't work

### ISSUE THREAD

**Issue by iamrajiv** [luizdepra/hugo-coder#257]
at the footer of the website, there is `.[]` how to remove it without changing the themes files
<img width="29" alt="Screenshot 2020-01-31 at 4 59 36 PM" src="https://user-images.githubusercontent.com/42106787/73536073-227bdc00-444b-11ea-8625-286c9ce9f56c.png">

also, I am not able to resize the image in markdown I think it is not rendering the HTML code
I have used both the code to resize the image but doesn't work
```
![](/images/test.png =100x20)
```
and I have used
```
<img src="/images/test.png" alt="test" width="200"/>
```

**Comment by luizdepra** [comment]
> at the footer of the website, there is .[] how to remove it without changing the themes files

Just remove the `commit` from you `config.toml`.

> also, I am not able to resize the image in markdown I think it is not rendering the HTML code
I have used both the code to resize the image but doesn't work

Hmmm... I never tried to resize images using these methods, but it have should worked.
Have you tried to use CSS rules? I think this is a better and reusable way.

I made something similar in my blog.

```css
figure.right-aligned > img {
  float: right;
  width: 50%;
  height: 50%;
  margin: 0 0 2rem 2rem;
}
```

And in the desired content/post/page:
```
{{< figure src="/images/img.jpg" alt="Hi there!" class="right-aligned" >}}
```

**Comment by iamrajiv** [comment]
thank you @luizdepra both the issues have been solved
