### ISSUE TITLE
Other Social Params

### ISSUE THREAD

**Issue by bemason** [luizdepra/hugo-coder#259]
I would like to add Google Scholar, Email, and another website with my own icon to the Social Params. How do I do that?

**Comment by luizdepra** [comment]
You could crate a custom CSS class for each icon and put it in the `icon` attribute of the desired social item.

**Comment by sidelux** [comment]
You should add one block like:
```
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram fa-2x"
    weight = 2
    url = "https://telegram.me/fenix45/"
```
Then replace icon  with one of [FontAwesome Icons](https://fontawesome.com/icons?d=gallery).

**Comment by bemason** [comment]
`[[params.social]]
    name = "Email"
    icon = "fas fa-envelope-square"
    weight = 3
    url = "mailto:bemason@umich.edu"`

I did this, but it didn't show up.. do I need to download a FontAwesome Icon and put it somewhere in the files?

**Comment by luizdepra** [comment]
I just found out that the social icons are not sorted correctly. I'm fixing it right now.

**Comment by bemason** [comment]
Can we access the Academic icons the same way we can access the original font awesome files? https://jpswalsh.github.io/academicons/

**Comment by luizdepra** [comment]
Yes, by downloading the `academicons.min.css`, placing it in your project static folder and adding it into the `custom_css` configuration. Then, you just need to put the desired icon CSS class in the `icon` field of any social item.

You could also change this theme files and add:
```
<link rel="stylesheet" href="https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css">
```
after this line: https://github.com/luizdepra/hugo-coder/blob/master/layouts/_default/baseof.html#L25

**Comment by bemason** [comment]
> Yes, by downloading the `academicons.min.css`, placing it in your project static folder and adding it into the `custom_css` configuration. Then, you just need to put the desired icon CSS class in the `icon` field of any social item.
> 
> You could also change this theme files adding:
> 
> ```
> <link rel="stylesheet" href="https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css">
> ```
> 
> after this line: https://github.com/luizdepra/hugo-coder/blob/master/layouts/_default/baseof.html#L25

**Comment by anyosa** [comment]
> Yes, by downloading the `academicons.min.css`, placing it in your project static folder and adding it into the `custom_css` configuration. Then, you just need to put the desired icon CSS class in the `icon` field of any social item.
> 
> You could also change this theme files adding:
> 
> ```
> <link rel="stylesheet" href="https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css">
> ```
> 
> after this line: https://github.com/luizdepra/hugo-coder/blob/master/layouts/_default/baseof.html#L25

Hi Luiz,

I went until copying the academicons.min.css in the static folder. Got lost in the following steps. Is it possible to get some help for them?

Thanks!

**Comment by clement-pannetier** [comment]
Hi @anyosa,

You have to options:

1. You copy the `academicons.min.css` in `static/css` and `academicons.ttf` in `static/fonts`
You add this line to `config.toml`: `custom_css = ["css/academicons.min.css"]`
You add a new social entry: 
```
[[params.social]]
    name = "Academia"
    icon = "ia ia-academia"
    weight = 1
    url = "https://jpswalsh.github.io/academicons/" 
```

2. Or simply follow this:
> You could also change this theme files adding:
`<link rel="stylesheet" href="https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css">`
after this line: https://github.com/luizdepra/hugo-coder/blob/master/layouts/_default/baseof.html#L31

And add the new social entry like above.

**Comment by anyosa** [comment]
Hi @clement-pannetier, thanks! but tried both options and no success so far. The icon just doesn't appear. 
(Do you know the name of the google scholar icon? Or where can I find the different icon names of academicons?)

**Comment by anyosa** [comment]
I managed to make it work! It was only about the icon name.
Thank you @clement-pannetier 👍.
