### ISSUE TITLE
Exclude default images from deployment

### ISSUE THREAD

**Issue by sidelux** [luizdepra/hugo-coder#261]
There is way to exclude placeholder/fault image file from production generated website?

Like:
avatar.jpg
favicon-16x16.png
favicon-32x32.png

Now i have that images and mine:
![image](https://user-images.githubusercontent.com/18572941/74034363-6bd2ab00-49b8-11ea-89b4-186f09b37219.png)

Thanks

**Comment by luizdepra** [comment]
Hmm... This never was a problem to me because I always override the default images.
But I think I just need to move these files to the `exampleSite` folder.
I will fix it soon.

**Comment by luizdepra** [comment]
Done. I can update now.

**Comment by sidelux** [comment]
Thanks a lot!
