### ISSUE TITLE
Add Images & Changing Font Color

### ISSUE THREAD

**Issue by bemason** [luizdepra/hugo-coder#262]
1. I want to set standard font colors for the headers in my pages, how do I do that? 
2. I want to add photos to my pages, similar to my friends site here: https://stroutm.net/index_research.html how would I add that?

Thank you!

**Comment by luizdepra** [comment]
You will need to play with CSS a bit for both cases. You can add a custom CSS file with the `custom_css` configuration of the `config.toml` file. You also could modify this theme source to get these things done. Anyway:

1. By creating CSS rules for `h1` elements, something like:
```
.page h1, .post h1 {
    color: red;
}
```

2. I'm not a CSS master, but seems like you will need to play with flex containers alignment.
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Aligning_Items_in_a_Flex_Container
