### ISSUE TITLE
Enable math in pages not in posts?

### ISSUE THREAD

**Issue by chongchonghe** [luizdepra/hugo-coder#271]
I noticed that only the pages inside posts are able to enable math via setting katex = true. Doing this in other pages does not enable math. Doing this in posts/index.md does not enable math either. Only multiple pages inside posts work. I wonder how to make "katex = true" enabling math work globally.

**Comment by luizdepra** [comment]
Yup. Only posts are capable to use katex or mathjax right now.
If you want to use it within any kind page you'll need to modify some layout files to include the partial `posts/math.html`, such as for [posts](https://github.com/luizdepra/hugo-coder/blob/master/layouts/posts/single.html#L45).

**Comment by chongchonghe** [comment]
> Yup. Only posts are capable to use katex or mathjax right now.
> If you want to use it within any kind page you'll need to modify some layout files to include the partial `posts/math.html`, such as for [posts](https://github.com/luizdepra/hugo-coder/blob/master/layouts/posts/single.html#L45).

Thank you for your reply. I want to enable it in another menu called 'research'. I made it work by copying everything in layouts/posts/ to [root]/layouts/research. Is there any more elegant way to do this? 

There is one more problem remaining. Math only works when there are multiple pages in posts. If there is a index.md inside posts, math won't work. How to fix this?

**Comment by luizdepra** [comment]
By creating a research folder you'll create a new archetype, like post is. Copying posts content is fine if it solve the problem.

About the other problem, you'll need to find with which template your content is rendering and try to add the math template in the right place.
