### ISSUE TITLE
not rendering posts list

### ISSUE THREAD

**Issue by theasmoth** [luizdepra/hugo-coder#272]
when run ```hugo serve``` everything is ok, but when i change smth in post file ```/posts/``` route renders this
![image](https://user-images.githubusercontent.com/3367484/76311821-d2fabc80-62e2-11ea-8da6-aa49f1bfcc72.png)

**Comment by luizdepra** [comment]
Hmm... I need more information.
What kind of change did you make and in  with file exactly?

**Comment by theasmoth** [comment]
anything, title or text content

changed Paginator to Paginate Pages and it works

**Comment by luizdepra** [comment]
So, it is solved? I think so.
