### ISSUE TITLE
CSS not generated correctly

### ISSUE THREAD

**Issue by mikeb01** [luizdepra/hugo-coder#278]
If I run the template in `hugo serve` it works fine, but if I upload the generated HTML to a site the CSS is not loaded correctly and the site is not formatted.  I'm running with the enhanced version of hugo, so it should support SCSS.

**Comment by luizdepra** [comment]
Are you trying to open the generated HTML files in your browser without hosting it?

Inspect the page source and take a look at css files addresses. This theme uses absolute URLs, so it is probably trying to find all the css files in address defined at `base_url` from your `config.toml`.

**Comment by mikeb01** [comment]
It didn't seem to work the first time I deployed to my site either, but subsequent clean and rebuild and it work.  Not quite sure what happened.  Hugo may have cached some stuff when I first ran it without the enhanced version.  Thanks for the quick response.

**Comment by mikeb01** [comment]
Actually I realise what is going on now, because of the absolute URL it will only work in http or https not both.  Is there are way to set it up so that it works with either.

**Comment by mikeb01** [comment]
I've worked around it with a re-write to https.  I've setup the base URL to use https, but for some reason the browser (firefox, brave, chrome) don't like it.  Firefox reports it being read correctly, Chrome shows an error (but not an HTTP error code).  So I'm not sure what is going on.
