### ISSUE TITLE
TOCSS: failed to transform

### ISSUE THREAD

**Issue by 3sky** [luizdepra/hugo-coder#279]
Hi @luizdepra,
Thanks for your work is awesome. 
Unfortunately today I noticed that the theme has a problem with Hugo v.0.67.1. 

8 days ago everything was fine:
https://github.com/3sky/blog-src/runs/503586227?check_suite_focus=true

Today I want to add new post and `boom`:
```bash
Error: Error building site: TOCSS: failed to transform "style.coder.css" (text/x-scss): resource "scss/scss/coder.scss_cb3a1967d0c4e493f72aa7656a0eb1bd" not found in file cache
```
https://github.com/3sky/blog-src/runs/519756565?check_suite_focus=true

After investigation, I find that Snapcraft upgrades the stable version of Hugo from 0.67.0 to 0.67.1.  
There is no option to use the older version with a snap. 
I know that I can build it from source, but it's just ineffective in CI/CD context. 

Can you take a look on that?

**Comment by luizdepra** [comment]
Hmmm... I suspect that snap is shipping the non-extended binary, but I need to take a better look.

**Comment by 3sky** [comment]
Thanks for response 👍 
As a workaround, I can recommend working with .deb file:

```bash
wget https://github.com/gohugoio/hugo/releases/download/v0.67.0/hugo_0.67.0_Linux-64bit.deb
sudo dpkg -i hugo_0.67.0_Linux-64bit.deb
```

Stay healthy :)

**Comment by pcnoic** [comment]
Having the same issue on a Windows environment while having Hugo installed via Scoop package manager. The error appears even on a clean install on Hugo, a freshly created Hugo website and fresh add of the theme as a submodule.

**Comment by clement-pannetier** [comment]
> Having the same issue on a Windows environment while having Hugo installed via the Scoop package manager. The error appears even on a clean install oF Hugo, a freshly created Hugo website and fresh add of the theme as a submodule. 
> 
> EDIT: Scoop installs version 0.68.3 by default. 

Hi, did you try to install the extended version.
For example with chocolatey the command is `
choco install hugo-extended`

**Comment by pcnoic** [comment]
> > Having the same issue on a Windows environment while having Hugo installed via the Scoop package manager. The error appears even on a clean install oF Hugo, a freshly created Hugo website and fresh add of the theme as a submodule.
> > EDIT: Scoop installs version 0.68.3 by default.
> 
> Hi, did you try to install the extended version.
> For example with chocolatey the command is ` choco install hugo-extended`

Hello Clement,

Thank you. Seems to work just fine with hugo-extended. Just tried it.

**Comment by luizdepra** [comment]
Nice. So, I gonna close this one.
