### ISSUE TITLE
Little issue when trying to use stackbit button

### ISSUE THREAD

**Issue by netrules** [luizdepra/hugo-coder#280]
![image](https://user-images.githubusercontent.com/48886164/77113471-45fde480-6a01-11ea-9e7c-5c22d02e0365.png)
![image](https://user-images.githubusercontent.com/48886164/77113489-501fe300-6a01-11ea-8532-277da1ab01ac.png)
![image](https://user-images.githubusercontent.com/48886164/77113493-544c0080-6a01-11ea-83fd-b3ca23795071.png)
Should be self-explaining. This is the best solution on the internet that I've found for the purpose I have. I appreciate the whole pipeline and workflow, and wonder what these errors might mean.

Thanks.

**Comment by luizdepra** [comment]
I don't use Stackbit to be 100% sure, but it seems there are some new configurations missing in [stackbit.yaml](https://github.com/luizdepra/hugo-coder/blob/master/stackbit.yaml).

Sorry, but I'm kinda busy right now. If you have some spare time, could you please try to add these missing items, test it and open a PR?
