### ISSUE TITLE
not found in file cache while starting

### ISSUE THREAD

**Issue by npsoni88** [luizdepra/hugo-coder#281]
I apologize if  its a silly question but I am very new to hugo. I get this error while trying to start the server after using the examplesite/config file.

```
Building sites … ERROR 2020/03/20 14:21:27 TOCSS: failed to transform "style.coder-dark.css" (text/x-scss): resource "scss/scss/coder-dark.scss_683a4b99b7581d7defe9f3136f4eecf6" not found in file cache
Built in 94 ms
Error: Error building site: TOCSS: failed to transform "style.coder.css" (text/x-scss): resource "scss/scss/coder.scss_078acb6e92884005af041aaabe919339" not found in file cache
```

Can somebody help please?

**Comment by npsoni88** [comment]
update - i replaced the hugo binary with hugo-extended and the error seems to have gone away. But now the CSS is not showing up on the page. I simply get HTML output without any style.

**Comment by npsoni88** [comment]
Apologies for brainfarts. I guess its still looking for css in "localhost" which wouldn't work as my files are on an actual server. The source inspection suggests its looking for this "href="http://localhost:80/css/coder.css"".

I tried grepping for localhost in themes/hugo-coder and in config but couldn't find any reference. Where exactly would I make that change?

**Comment by luizdepra** [comment]
You normally define your url in the `config.toml` with `baseurl`, see [here](https://github.com/luizdepra/hugo-coder/blob/master/exampleSite/config.toml#L1).
But, if you are running `hugo server`, this config will be ignored and replaced with localhost.
