### ISSUE TITLE
Queries about the theme

### ISSUE THREAD

**Issue by security-prince** [luizdepra/hugo-coder#282]
Hi,

1. I am very much new to hugo i tried using it to build a website on the local server for my use but i am not able to enable the dark mode or the option to select the color mode, i played around with the `colorscheme` but it doesn't seem to work.

2. I have created multiple posts and saved the draft state as false but still i am not able to see my posts
Screenshot 1: https://prnt.sc/rmxcqf
Screenshot 2: https://prnt.sc/rmxd6m

**Comment by luizdepra** [comment]
Hello.
 
1. The `colorscheme` is in the wrong place. You need to place it inside `[params]`, like [here](https://github.com/luizdepra/hugo-coder/blob/master/exampleSite/config.toml#L43). Also, you can remove the `rls` at the end of the file, it is already inside `[params]`.

2. Do don't know if I understood but are you expecting to see your posts list in the home page? You should see your posts by clicking in `posts` link, top menu.

**Comment by security-prince** [comment]
2. I attached the wrong screenshot, here is the intended one:
https://prnt.sc/rnkvij, i can access my posts when i give the exact url to the posts like this: https://prnt.sc/rnkwfq

**Comment by luizdepra** [comment]
I see. The problem is that you need to provide a title to your posts. Take a look at [this example post](https://raw.githubusercontent.com/luizdepra/hugo-coder/master/exampleSite/content/posts/creating-a-new-theme.md). There is a configuration section in the beginning of the post file, enclosed with `+++`. This is called [front matter](https://gohugo.io/content-management/front-matter). So, you need to provide at least a `title` and a `date` in the post front matter. `slug` is optional, but with this option you can control how your post url will be.

**Comment by security-prince** [comment]
> I see. The problem is that you need to provide a title to your posts. Take a look at [this example post](https://raw.githubusercontent.com/luizdepra/hugo-coder/master/exampleSite/content/posts/creating-a-new-theme.md). There is a configuration section in the beginning of the post file, enclosed with `+++`. This is called [front matter](https://gohugo.io/content-management/front-matter). So, you need to provide at least a `title` and a `date` in the post front matter. `slug` is optional, but with this option you can control how your post url will be.

Thanks, i did that but now it shows the posts like this: https://prnt.sc/rntrwx

**Comment by luizdepra** [comment]
This issue seems the same problem: #272
But the report doesn't give me enough information about the problem.

I suspect that this is a formatting problem. Could you show me your config.toml and your post content? Hosting it in a [gist](https://gist.github.com/) would be nicer than a screenshoot.

The post content should be formatted like this. Linebreaks and quotes are important.
```
+++ 
date = "2014-09-28"
title = "A title"
slug = "a-slug"
+++

Text here!
```

**Comment by security-prince** [comment]
> This issue seems the same problem: #272
> But the report doesn't give me enough information about the problem.
> 
> I suspect that this is a formatting problem. Could you show me your config.toml and your post content? Hosting it in a [gist](https://gist.github.com/) would be nicer than a screenshoot.
> 
> The post content should be formatted like this. Linebreaks and quotes are important.
> 
> ```
> +++ 
> date = "2014-09-28"
> title = "A title"
> slug = "a-slug"
> +++
> 
> Text here!
> ```

Hi, i have created the post content exactly like this, check this [gist](https://gist.github.com/security-prince/d8179b3b892f7b6a2822ceaebb7f5269) and the screenshot [here](https://prnt.sc/rnupbz) of the post content

**Comment by luizdepra** [comment]
I was not able to reproduce it.

Is Hugo throwing any error or warning?
Which Hugo version are you using? Try to using the newest one, extended.

But I found out that the taxonomy configuration is missing. Try adding this into your `config.toml`.
```
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
```

You could try to copy everything from `exampleSite` folder into a new site project and add one or more posts from your site. If everything works fine, the problem probably is something missing in your `config.toml`.

**Comment by security-prince** [comment]
> I was not able to reproduce it.
> 
> Is Hugo throwing any error or warning?
> Which Hugo version are you using? Try to using the newest one, extended.
> 
> But I found out that the taxonomy configuration is missing. Try adding this into your `config.toml`.
> 
> ```
> [taxonomies]
>   category = "categories"
>   series = "series"
>   tag = "tags"
> ```
> 
> You could try to copy everything from `exampleSite` folder into a new site project and add one or more posts from your site. If everything works fine, the problem probably is something missing in your `config.toml`.

Hi @luizdepra , the issue is fixed now, seems like a server restart was required for these changes to take effect

**Comment by security-prince** [comment]
Hi @luizdepra , my [site](https://ishaqmohammed.me/) is up and running, can you tell me how do i disable the disqus comments?

**Comment by clement-pannetier** [comment]
Hi, simply remove the "disqusShortname" property in your config.toml file.

**Comment by security-prince** [comment]
Thank you @clement-pannetier
