### ISSUE TITLE
Theme archetype does not override default.md

### ISSUE THREAD

**Issue by vvug** [luizdepra/hugo-coder#284]
The default `default.md` is:
```
$ cat archetypes/default.md 
---
title: "{{ replace .Name "-" " " | title }}"
date: {{ .Date }}
draft: true
---
```

This theme ships:
```
$ cat themes/hugo-coder/archetypes/default.md 
+++ 
draft = true
date = {{ .Date }}
title = ""
slug = "" 
+++
```

But the archetype shipped with the theme is not used:
```
$ hugo new pages/newpage.md
/home/user/hugotest/test3/content/pages/newpage.md created
$ cat /home/user/hugotest/test3/content/pages/newpage.md
---
title: "Newpage"
date: 2020-03-30T00:13:35+02:00
draft: true
---
```

Running Hugo 0.68.3 and hugo-coder from git (17fe8de72b97d0b91143afbb7b08b610292166d3).

**Comment by clement-pannetier** [comment]
Hi,

According to the [Hugo documentation](https://gohugo.io/content-management/archetypes/), when you make `hugo new ...` it searchs the following files in your directory

> 1. archetypes/pages.md
> 2. archetypes/default.md
> 3. themes/my-theme/archetypes/pages.md
> 4. themes/my-theme/archetypes/default.md

So I think you just have to remove the default.md file in archetypes/ folder or create your own pages.md archetype.

**Comment by vvug** [comment]
Thanks @clement-pannetier. Then it's working as intended, but I still find strange that the global default overrides the theme default. Not a theme issue in any case. Closing this.
