### ISSUE TITLE
No way to hide/disable the reading time

### ISSUE THREAD

**Issue by vvug** [luizdepra/hugo-coder#285]
I would like to globally disable the "reading time" of posts of my blog using hugo-coder. Is it possible?

Thanks!

**Comment by clement-pannetier** [comment]
Hi,

I don't think there is a global parameter in the configuration to do that, but you can override [this file](https://github.com/luizdepra/hugo-coder/blob/master/layouts/posts/single.html) and remove the reading time elements.

**Comment by christianortizch** [comment]
> Hi,
> 
> I don't think there is a global parameter in the configuration to do that, but you can override [this file](https://github.com/luizdepra/hugo-coder/blob/master/layouts/posts/single.html) and remove the reading time elements.

Hey! amazing, where should I paste that file code you sent to remove the reading time?

**Comment by christianortizch** [comment]
> Hi,
> 
> I don't think there is a global parameter in the configuration to do that, but you can override [this file](https://github.com/luizdepra/hugo-coder/blob/master/layouts/posts/single.html) and remove the reading time elements.

thanksssssss

**Comment by clement-pannetier** [comment]
Hi @vvug, did you manage to do what I said ?

**Comment by vvug** [comment]
Solved by overriding, thanks @clement-pannetier
