### ISSUE TITLE
No support for subsections

### ISSUE THREAD

**Issue by vvug** [luizdepra/hugo-coder#286]
If my understanding is correct, Hugo builds a tree with all the subdirectories of sections, for example:
```
content/posts/2019/post1.md
content/posts/2020/post1.md
content/posts/2020/post2.md
```
where `2019` and `2020` are subsections of the `posts` section. However this subdivision is not exposed by hugo-coder: the "Blog" page is flat, with no sectioning. It is possible to add support for this kind of sectioning? Thanks!

**Comment by clement-pannetier** [comment]
Hi,

Not sure about that, I don't have posts on my site but if you watch @luizdepra website directory, there is no year folder in content/posts.

**Comment by luizdepra** [comment]
I never tried to organize my content like this. 
I don't know if Hugo really supports this feature, but maybe this what you're looking for: https://gohugo.io/content-management/organization/#index-pages-_indexmd
