### ISSUE TITLE
Pages without date?

### ISSUE THREAD

**Issue by vvug** [luizdepra/hugo-coder#287]
Having dates is blog entries is great, but I'd like to have a section made of pages where the publication date is not shown because it doesn't matter. Think of some documents which are updated very rarely and are to be considered always up to date. Can this be done with hugo-coder?

Thanks for this great theme.

**Comment by clement-pannetier** [comment]
Hi

You don't want the underlined text on this screenshot to be visible ?
![image](https://user-images.githubusercontent.com/35581688/77863256-424c3800-7221-11ea-8589-dd1b3a31f6f7.png)

**Comment by vvug** [comment]
Yes, but the date also appears when viewing the post, so this is probably not to straightforward to do.

**Comment by clement-pannetier** [comment]
Override the theme to your needs, remove the date elements on the layouts/posts/single.html and layouts/posts/li.html.
