### ISSUE TITLE
Empty footer class still takes vertical space

### ISSUE THREAD

**Issue by paride** [luizdepra/hugo-coder#288]
In my `config.toml` I have:
```
footercontent = ""
hideCredits = true
hideCopyright = true
```
as I don't want a footer, but the generated html pages still contain this section:
```
      <footer class="footer">
  <section class="container">
    
    
    
    
  </section>
</footer>
```
which despite being empty takes some vertical space. This causes the page to become vertically scrollable even if there is nothing to scroll to, especially on mobile devices.

I think the footer class should be skipped entirely if there is no footer content.

**Comment by luizdepra** [comment]
We just add the `hidefooter` configuration to solve this problem.
Thx, @clement-pannetier.
