### ISSUE TITLE
Disqus

### ISSUE THREAD

**Issue by HypeLevels** [luizdepra/hugo-coder#291]
Not really an issue, can someone help me disable disqus from the WHOLE website ?

**Comment by clement-pannetier** [comment]
> Not really an issue, can someone help me disable disqus from the WHOLE website ? 

Hi, simply remove the "disqusShortname" property in your config.toml file.

**Comment by clement-pannetier** [comment]
Hi @HypeLevels, did you manage to do what I said ?

**Comment by luizdepra** [comment]
Yup, I think so.
