### ISSUE TITLE
Switching language jumps to index page

### ISSUE THREAD

**Issue by davhin** [luizdepra/hugo-coder#293]
Description:
When the language is changed by clicking in the menu, the page jumps to the index page for that language, not the translation for the currently viewed content.

Steps to reproduce:
Launch the example site inside the template, click on a page, and then click on the other language.

I have this problem with my own site of course, but it also happens with the example site from the template. Maybe I am just a noob?

**Comment by a1x42** [comment]
I noticed the same issue and fixed it locally as it might be desired behaviour i.e. not all pages might be available in all languages. I changed the header template to only list the languages for which a localised version for the current page exists. I can propose a patch if you are interested. of course this will affect the current behaviour which is a problem if it is not considered to be a bug.

**Comment by netrules** [comment]
Please propose patch

**Comment by a1x42** [comment]
done: see pull request #294

**Comment by davhin** [comment]
Thank you so much!!

**Comment by luizdepra** [comment]
Done. Closing. :)
