### ISSUE TITLE
Translate to french?

### ISSUE THREAD

**Issue by netrules** [luizdepra/hugo-coder#296]
Anybody getting an error similar to described https://stackoverflow.com/questions/2467454/why-does-chrome-incorrectly-determine-page-is-in-a-different-language-and-offer ?

i.e., when I visit my site which is in English, not in any other language:
![image](https://user-images.githubusercontent.com/48886164/78452717-40400a00-7663-11ea-8c04-b54509d69d70.png)

I can fix this and propose PR if anyone else is getting the same issue.

**Comment by clement-pannetier** [comment]
Hi, how do you get multiple translation possibilities ?
![image](https://user-images.githubusercontent.com/35581688/78500663-20d6d900-7758-11ea-86e5-4f2feb8fd9d8.png)

**Comment by netrules** [comment]
lol, that's offtopic, but anyway...
@offtopic @clement-pannetier 
Explanation:
- CTRL+L. In your chrome address, write the following: `chrome://settings/languages`.
- In `Languages > Language`, upon being expanded, choose `Add Languages`, look for it, mark the checkbox, and press `Add` button.
- Make sure it is saved and then you're done.

Glad to help. :)

**Comment by clement-pannetier** [comment]
> lol, that's offtopic, but anyway...
> 
> #offtopic @clement-pannetier 
> Explanation:
> - CTRL+L. In your chrome address, write the following: `chrome://settings/languages`.
> - In `Languages > Language`, upon being expanded, choose `Add Languages`, look for it, mark the checkbox, and press `Add` button.
> - Make sure it is saved and then you're done.
> 
> Glad to help. :)

Thanks but I've already made that and also checked the checkbox to be able to receive translations for this language...

**Comment by netrules** [comment]
Maybe check if you have latest chrome, it tends to be buggy sometimes. Oh by the way, do you mind if I steal/borrow the javascriptlet from your .dev site to change site mood/color?

**Comment by clement-pannetier** [comment]
> Maybe check if you have latest chrome, it tends to be buggy sometimes. Oh by the way, do you mind if I steal/borrow the javascriptlet from your .dev site to change site mood/color?

Already checked 😄
Of course you can but it's not very good code... I need to refactor it.

**Comment by clement-pannetier** [comment]
@netrules, I'ts now working (different translations capabilities) since the last update ([81.0.4044.92](https://chromereleases.googleblog.com/search/label/Desktop%20Update)), I don't know why...

I saw your commit on your [github repo](https://github.com/netrules/sgonzalez-tech/commit/639d9a40fda0d2f7883796a941a85b35d337807e).
I think that only this line `<meta http-equiv="Content-Language" content="{{ .Site.Language.Lang }}">` is relevant because the others parameters like `xml:lang` or `xmlns` are used when the page is not served as text/html as you can see [here](https://www.w3.org/International/geo/html-tech/tech-lang.html#ri20040429.092928424).

**Comment by netrules** [comment]
Thanks clement. Anyway, I refactored it a little and used for my project too. You can see it in the latest commits. Thanks again! Really practical imho.

**Comment by clement-pannetier** [comment]
> Thanks clement (or should I say, merci?). Anyway, I refactored it a little and used for my project too. You can see it in the latest commits. Thanks again! Really practical imho.

😄, I can make a PR if you want ?

@luizdepra, is it a bug you want to be fixed or not ?

**Comment by netrules** [comment]
Oh regarding the site language? I still haven't found a way to fix it lol

**Comment by clement-pannetier** [comment]
> Oh regarding the site language? I still haven't found a way to fix it lol

It doesn't work for you ? It seems to work on my side 🤨.

**Comment by netrules** [comment]
Not sure, do you see anything wrong with my landing page sources? Also, any way I can get in touch with you? I have some questions regarding your repo.

**Comment by clement-pannetier** [comment]
Of course, open an issue [here](https://gitlab.com/clement-pannetier/clementpannetier.dev) if you have a GitLab account.

**Comment by luizdepra** [comment]
Sure, a PR would be nice, @clement-pannetier.

**Comment by clement-pannetier** [comment]
> Sure, a PR would be nice, @clement-pannetier.

I'll do it tomorrow, it's getting late here.
