### ISSUE TITLE
code block in the dark mode 

### ISSUE THREAD

**Issue by aymaneMx** [luizdepra/hugo-coder#301]
just a question please, why my code looks like that in the dark mode? 

here is my code:
```graphql
query maliciousQuery {
  thread(id: "some-id") {
    messages(first: 99999) {
      thread {
        messages(first: 99999) {
          thread {
            messages(first: 99999) {
              thread {
                # ...repeat times 10000...
              }
            }
          }
        }
      }
    }
  }
}
```

and here is the result :
![image](https://user-images.githubusercontent.com/30264095/78907078-1aa66c80-7a78-11ea-8cc0-a8a36362cd02.png)

**Comment by luizdepra** [comment]
We are using using an old way to set code highlight. I need to take a look and update it.
But, I think it still works fine. Try to change the `pygmentsstyle` config to other values. [Here](https://xyproto.github.io/splash/docs/) is a list of available styles.

You could also try to use follow [this new configuration steps](https://gohugo.io/content-management/syntax-highlighting/).

**Comment by aymaneMx** [comment]
thank you! 
I change it to : `pygmentsstyle = "dracula"` and it works well for me. 
the result 👇 :
<img width="896" alt="Screenshot 2020-04-09 at 16 03 19" src="https://user-images.githubusercontent.com/30264095/78909577-a66dc800-7a7b-11ea-95c1-3b0f2bbb798e.png">
