### ISSUE TITLE
Custom SCSS files generated twice

### ISSUE THREAD

**Issue by clement-pannetier** [luizdepra/hugo-coder#305]
Hi all,

I'm currently working to create a new projects showcase page as you can see [here](https://github.com/luizdepra/hugo-coder/issues/59#issuecomment-609712806).

I noticed that this feature #244 causes problem. The SCSS files are generated twice because they are already generated before as you can see below :
![image](https://user-images.githubusercontent.com/35581688/79009748-8ebc3f80-7b60-11ea-880a-d5be9c4b5d01.png)
![image](https://user-images.githubusercontent.com/35581688/79012251-2f612e00-7b66-11ea-90bf-cb25af407f85.png)

## Steps to reproduce
1. Add this line to your `config.toml` file (the files are located inside `assets/` directory)
> `custom_scss = ["scss/coder.scss", "scss/coder-dark.scss"]`

2. Override the SCSS files of the theme (copy them inside `assets/` directory)

**Comment by luizdepra** [comment]
Hmm... weird. Looks like there is something missing in the base template.
I'm gonna take a look later.

**Comment by luizdepra** [comment]
Ahhh, man. I think I know what is the problem.
If you are overriding any SCSS file from the theme you don't need to put it in the `custom_scss`. Hugo is smart enough to figure it out and do the job.
Try removing both files from the config and see if everything is ok.

**Comment by clement-pannetier** [comment]
Ok, so it's just to add new SCSS files like @elihunter173 did in repo [here](https://github.com/elihunter173/website/blob/bcb272ef1d36c29549fd1e42a161caf5596fece9/config.toml#L39), not SCSS files with the same name as in the theme.
Thanks.
