### ISSUE TITLE
Links color doesn't follow WCAG standards on dark theme

### ISSUE THREAD

**Issue by clement-pannetier** [luizdepra/hugo-coder#308]
I recently checked the Material Design specifications for dark theme and saw that the $link-color-dark variable defined in `_variables.scss` doesn't follow the WCAG standards.

![image](https://user-images.githubusercontent.com/35581688/79146918-6aac6880-7dc3-11ea-9c69-1287b7c8dde9.png)

Sources :
- https://material.io/design/color/text-legibility.html
- https://material.io/resources/color/#!/?view.left=1&view.right=1&primary.color=212121&primary.text.color=36679f&secondary.color=FAFAFA&secondary.text.color=1565c0

**Comment by luizdepra** [comment]
Originaly the dark mode link color was red. But some PR changed it.

What do you thing? We should revert it back to red or find a suitable blue color?

**Comment by clement-pannetier** [comment]
> Originaly the dark mode link color was red. But some PR changed it.
> 
> What do you thing? We should revert it back to red or find a suitable blue color?

I think we should find a lighter color, it can be blue, red, whatever.
From the material design palette, I propose #42a5f5, it's legible.

Maybe we should add a new theme parameter like `palette = <colorName>`, it's a parameter name I used in an other theme ?

**Comment by luizdepra** [comment]
The #42a5f5 is ok.
I think we don't need another configuration just to override a color that is easily customizable editing a SCSS file.

**Comment by clement-pannetier** [comment]
Ok, btw did you checked my last PR ?

**Comment by luizdepra** [comment]
Not yet. I'm kinda overloaded at work right now. I'll try to take a look at all open PRs this weekend.

**Comment by clement-pannetier** [comment]
> Not yet. I'm kinda overloaded at work right now. I'll try to take a look at all open PRs this weekend.

No problem, that's not my case, that's why i'm more involved on this project 😄. Take care and stay home 💪
