### ISSUE TITLE
Open URLs in a New Tab

### ISSUE THREAD

**Issue by Fakorede** [luizdepra/hugo-coder#309]
I'm trying to make links to my socials open in new tabs when clicked. I learnt Hugo as of `v0.60.0` uses Goldmark rendering for markdown. So tried the [Render Hooks Template](https://gohugo.io/getting-started/configuration-markup/#render-hook-templates).

But it only works for links in markdown following the format `[Text](https://www.gohugo.io "Title")`. 

I would like to know how to achieve this for the links in the config file.

```
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/Fakorede"
```

**Comment by clement-pannetier** [comment]
Hi @Fakorede,

As you can below in the `layouts/_partials/home.html`
```
{{ with .Site.Params.social }}
    <ul>
      {{ range sort . "weight" }}
        {{ if .icon }}
          <li>
            <a href="{{ .url }}" aria-label="{{ .name }}" {{ if .rel }}rel="{{ .rel }}"{{ end }} {{ if .target }}target="{{ .target }}"{{ end }} {{ if .type }}type="{{ .type }}"{{ end }}>
              <i class="{{ .icon }}" aria-hidden="true"></i>
            </a>
          </li>
        {{ else }}
          <li>
            <a href="{{ .url }}" aria-label="{{ .name }}" {{ if .rel }}rel="{{ .rel }}"{{ end }} {{ if .target }}target="{{ .target }}"{{ end }}>{{ .name }}</a>
          </li>
        {{ end }}
      {{ end }}
    </ul>
    {{ end }}
```

You can add the `target = "_blank"` parameter in your `config.toml` file.

**Comment by Fakorede** [comment]
Great! Thanks @clement-pannetier .
