### ISSUE TITLE
Other seciton that posts does not generate tags or categories in the page

### ISSUE THREAD

**Issue by bauguste** [luizdepra/hugo-coder#311]
Hello,
Firstly, thank you for this beautiful theme.
I have a question, when I change my folder organization, for example:
```
content/posts/test.md
```
to
```
content/blog/test.md
```
the corresponding test.md not generate the tags or categories or reading time.

It's an issue or I don't understand how it works ?

**Comment by bauguste** [comment]
Thank your for your answer. It's not an issue, now I understand how this view is generated.

**Comment by luizdepra** [comment]
Take a look at #186. There are two ways to do the same thing without changing the theme.
