### ISSUE TITLE
JavaScript references in wrong place

### ISSUE THREAD

**Issue by netrules** [luizdepra/hugo-coder#314]
https://github.com/luizdepra/hugo-coder/blob/e46c452344a13d94b2748efa8a281778fc70df4b/layouts/_default/baseof.html#L66-L68

Scripts in head of html presentation should be at bottom of <body></body> element; 
> This prevents render blocking while the scripts load and is much better for site perception speed.
sources:
- https://stackoverflow.com/questions/3531314/should-i-write-script-in-the-body-or-the-head-of-the-html
- https://stackoverflow.com/questions/7751514/javascript-in-head-or-just-before-body

If anyone else agrees, I can make PR, although that'd take a little while. If you want to proceed with PR, go ahead.

**Comment by clement-pannetier** [comment]
@netrules, I already made that on my website to change theme dynamically. I can make a PR.

**Comment by luizdepra** [comment]
I would appreciate a PR here too, @clement-pannetier.

**Comment by clement-pannetier** [comment]
> I would appreciate a PR here too, @clement-pannetier.

I'll do it tomorrow, it's getting late here.

**Comment by luizdepra** [comment]
Done, ty!
