### ISSUE TITLE
Forestry Instant Previews

### ISSUE THREAD

**Issue by netrules** [luizdepra/hugo-coder#315]
Hello again,

This might be a little outside project scope currently, but when deploying through stackbit as jamstack, there's a thing called "Instant Previews". Anyway, in order to get it working for me using the latest provided hugo container image, I had to use the following configuration:
![forestry configuration](https://user-images.githubusercontent.com/48886164/80173321-6c451000-85bd-11ea-9524-02992d0bfd65.png)

As you can see in [my repository](https://github.com/netrules/sgonzalez-tech), I also made a few tweaks here and there in the Makefile in order to run it containerized within an app called Gitpod for practical staging purposes. Mostly I am just posting this PR in case anybody runs into the same requirement, or simply has interest in developing further container compatibility. I have no clue how all this could be repurposed/refactored into the luizdepra's repository in order to implement similar changes for other headless CMS's.

If you have any additional information or a maintainer wants to reject this issue, I understand. I just hope to get some feedback on what I am doing or how others might implement this using current stackbit configuration.

Thanks!

**Comment by luizdepra** [comment]
Hi.
The gitpod and staging features are interesting but they look like something I would like in a site deployment, not in a theme repository. Although, this repository has a staging deploy for PR, but I'm using Netlify directly.

**Comment by netrules** [comment]
Gotcha! No problem. Maybe it would be useful for reference in a wiki or if anybody is confused. Feel free to close the issue!

**Comment by luizdepra** [comment]
Yup. It would be interesting if you compose a blog post or a wiki entry explaining how to use gitpod and configuration a staging deploy. I could add or reference it to this project wiki.

**Comment by netrules** [comment]
Gonna do it. Thank you, I totally forgot about that. lol :D
