### ISSUE TITLE
Unable to use normal markdown/html formatting

### ISSUE THREAD

**Issue by utkarsh2102** [luizdepra/hugo-coder#321]
Hi @luizdepra @clement-pannetier,
Thanks for helping out previously.

However, I hit another obstacle. I've been trying to right align an image but it doesn't seem to work.
I need something like this:
```
paragraph about something              |        image        |
paragraph contrinued                   |       which is      |
paragraph ends here.                   |  aligned like this  |
```

I could think of doing this using html tags (`<img>`) while writing posts in markdown but it doesn't seem to work. Any clue or workaround?

**Comment by utkarsh2102** [comment]
Like this: 
![image](https://user-images.githubusercontent.com/31288318/80811283-328a8f80-8be3-11ea-9945-4578ca8e8894.png)

**Comment by utkarsh2102** [comment]
Furthermore, `<div align="center">` doesn't work either :/

**Comment by clement-pannetier** [comment]
Hi @utkarsh2102,

I used this on my website : `
{{< figure src="/images/avatar-transparent.png" alt="Avatar Clément PANNETIER" >}}`
as you can see [here](https://clementpannetier.dev/a-propos/).

And the css :
```
figure {
  text-align: center;
  img {
    width: 25%;
  }
  @media only screen and (min-width: 768px) {
    img {
      float: right;
      margin: 0 0 2rem 2rem;
    }
  }
}
```

**Comment by utkarsh2102** [comment]
Hi Clement,

And wow. Dark theme alongside the regular one. Did any tweaks?

And also, where do that CSS go?

**Comment by clement-pannetier** [comment]
> Wow. Dark theme alongside the regular one. Did any tweaks?

Yes, I changed dark theme colors and created my own brand dark surface following these specifications : https://material.io/design/color/dark-theme.html#properties section "Accessibility and contrast".

> And also, where do that CSS go?

I recently moved all the content of `custom.css` file into SCSS ones. So that CSS is now in the `_base.scss` file.

**Comment by utkarsh2102** [comment]
> Yes, I changed dark theme colors and created my own brand dark surface following these specifications : https://material.io/design/color/dark-theme.html#properties section "Accessibility and contrast".

Wow again. This is amazing!
Can we have it by default in hugo-coder? Dark theme option like that in your website^?

> I recently moved all the content of custom.css file into SCSS ones. So CSS is now in the _base.scss file.

Weehoo, worked for me, too! You're awesome, thanks! <3

**Comment by clement-pannetier** [comment]
> Can we have it by default in hugo-coder? Dark theme option like that in your website^?

Dark theme is already implemented but not the toggle button (corner right of the page). More info here #226.

**Comment by utkarsh2102** [comment]
> Dark theme is already implemented but not the toggle button (corner right of the page). More info here #226.

Oh yea, yeah! I mean the toggle button. At some point, I'd really appreciate this thing happening!

**Comment by clement-pannetier** [comment]
My GitLab repo : https://gitlab.com/clement-pannetier/clementpannetier.dev

**Comment by luizdepra** [comment]
I think we can closed this, right?
