### ISSUE TITLE
reading_time not translated

### ISSUE THREAD

**Issue by a1x42** [luizdepra/hugo-coder#325]
I am trying to setup a blog on my multi-language site. It should allow me to create posts for different languages and up to now it seems to work well. For ease of example I created one post (default language english) and a symbolic link to it for the second language (slovak). Now when switching language on the post itself, it translates everything fine in the footer but reading_time remains unresolved within the slovak version. In english it looks ok. Compare the following two links:
https://erz.lu/2020/05/learning-with-pandemic/
https://erz.lu/sk/2020/05/learning-with-pandemic/

Any hint would be appreciated.

**Comment by clement-pannetier** [comment]
Hi @a1x42,

I just tested slovak translation on the example site by adding a new languages parameter in the `config.toml` file. It works as you see below:

![image](https://user-images.githubusercontent.com/35581688/81473893-21a0d600-9202-11ea-92f8-7385d79c8a68.png)

Do you have a link to your repository ?

**Comment by a1x42** [comment]
I only have a local repository. But comparing with the ExampleSite, I haven't really done anything different. Adding a blog menu entry for both languages and creating a post... will continue searching, as generally it seems to work. ;-)

**Comment by a1x42** [comment]
ok, one step further. I tried with a shorter article and indeed, I also see the translation. The issue seems to be linked to translating e.g. "3 minutes read"

**Comment by clement-pannetier** [comment]
> ok, one step further. I tried with a shorter article and indeed, I also see the translation. The issue seems to be linked to translating e.g. "3 minutes read"

Same here 😕

**Comment by a1x42** [comment]
found the solution here https://discourse.gohugo.io/t/plural-doesnt-work-for-brazillian-portuguese-and-polish/20329/2

adding "few" and "many" option solves the issue. Will provide a fix. Interesting enough, the polish translation only uses other, i.e. omits one, which seems not to have the issue.

**Comment by clement-pannetier** [comment]
If I remember well, I had a similar issue when I wanted to add strings to the i18n files for the [project archetype](https://github.com/luizdepra/hugo-coder/pull/307/commits/46c3ec7a3670317d35b7827e1e5cccf191bd45a4). I saw this issue you mentioned but it didn't worked for me.
Do you know if the `few` and `many` options should be added to the other i18n files ?

**Comment by a1x42** [comment]
no, not sure. english seems ok without.

**Comment by clement-pannetier** [comment]
@a1x42, I found these links rather useful even thought it's quite difficult to understand 😅.

http://cldr.unicode.org/index/cldr-spec/plural-rules
https://www.unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules

**Comment by a1x42** [comment]
@clement-pannetier indeed, I also thought that it might be linked to something like this. Actually, as in Russian, also in Slovak language the form of the noun changes when saying 1, 2-4 or 5 and above. When originally providing the translation file, we were trying to put "two" but it wasn't accepted. So we came up with a sentence which stays the same independent of the number. We later saw that within the polish translation, apparently he faced the same issue (grammar is comparable to Slovak) and he solved it by using "min." instead of writing the full word, so he only needed to provide the "other" translation avoiding the issue. Quite good compromise too!

In any case, thanks for the article. This was a very interesting read!

**Comment by luizdepra** [comment]
Hi. This issue was fixed at #326, right?

**Comment by a1x42** [comment]
Yes, thanks.
