### ISSUE TITLE
Switching between dark and light background

### ISSUE THREAD

**Issue by rajmahendra** [luizdepra/hugo-coder#327]
Provide a button for dark and light background. when the viewer clicks a toggle the site changes its background to dark or light respectively

**Comment by clement-pannetier** [comment]
Hi @rajmahendra, this feature has been discussed here #226 but the "automagic" solution has been chosen.

**Comment by luizdepra** [comment]
BTW, this is kinda easy to customize.
But we go with the `prefers-color-scheme` approach.

**Comment by luizdepra** [comment]
Well, We've merged this feature while ago.
