### ISSUE TITLE
Adding Table of Contents toggle option and minor CSS bug

### ISSUE THREAD

**Issue by ajdintrejic** [luizdepra/hugo-coder#329]
So, I have been messing around with this theme and I have managed to get the toc in there. It wasn't that hard but why not just add a toggle in the post header `toc: true` and insert this code into `/layouts/posts/single.html`
```
        <div>
        {{ if .Params.featured_image }}
                 <img src='{{ .Params.featured_image }}' alt="Featured image"/>
        {{ end }}
    
        {{ if .Params.toc }}
              <hr>
              Table of Contents
               <div id="toc"> {{ .TableOfContents }} </div>
               <hr>
        {{ end }}
        {{ .Content }}
      </div>
```

This would make adding the Table much easier and it doesn't add much code. (excuse my horrendous indentation :) )
The table of contents also looks like this by default:
![image](https://user-images.githubusercontent.com/41389717/81501238-942fb580-92d7-11ea-8d7c-0057deda8e8c.png)

I think it's kinda out of place with all that blue text, I'm not a designer but I think making it black suits more the theme/colorscheme. You probably know better and you should decide, I have made it black so you can take a look.
![image](https://user-images.githubusercontent.com/41389717/81501173-1ff51200-92d7-11ea-93a8-4d10f2c90099.png)

I have also noticed this "bug", it a minor thing but on Android (Firefox and Brave), when you open the hamburger menu, and close it, the color of the hamburger menu changes to blue. 
![image](https://user-images.githubusercontent.com/41389717/81501368-4bc4c780-92d8-11ea-8a25-fa1442562155.png)
This also happens on light theme. When you emulate a mobile browser on desktop (atleast with Firefox) this doesn't happen all the time.

**Comment by luizdepra** [comment]
Well... what bothers me most are the list bullets. Maybe you could try to remove them but keep the indentation.
Links should be always colored with the default link-color. Making it black will make them look like a normal text.

**Comment by ajdintrejic** [comment]
![image](https://user-images.githubusercontent.com/41389717/81991064-b2cbde80-9640-11ea-9572-bf67b72deb11.png)
What do you think? Should I fix the padding? Anyway, If you're willing to I can make a changes to my fork and make a pull request with all the translations in `/i18n` dir

**Comment by jemus42** [comment]
I recently added a TOC to my site in a similar way, but I'm not all too happy with how it looks. Ideally I'd like to have a sticky TOC to the side of the content for easier navigation, but my (S)CSS experimentation was not particularly successful.

Then I saw [the LoveIt theme](https://themes.gohugo.io//theme/LoveIt/theme-documentation-content/) and became kind of envious of its neato TOC – among some other nice features.  
But that theme uses tons of other third party integrations with their JS dependencies I don't really care for, so… is there any interest in adding a similar TOC to Coder? 

I thought I'd rather ask here if there's a chance before I try to recreate that kind of TOC myself — and I *just* switched to Coder and I'm not looking to switch themes again over a TOC.

![](https://dump.jemu.name/20200520193040-8ahep1pgecmu48k.png)

**Comment by jsturdy** [comment]
I had also been interested in a sidebar TOC so I put together something pretty hacky (full disclosure, I'm neither a web developer nor a web designer).
It doesn't currently have the highlighting of the current location in the page, but that's something I'm interested in, so I'll keep poking at it.
I'll post some screen shots just to give an idea of what it currently does, so people can comment, pick it apart, propose better aesthetic design choices.
One thing I would change would be the link colour, as I'd consider it more in the same class as the links on the menu bar, but @luizdepra, you seemed to prefer keeping them with the standard link colour.

I was working to only have it active on the "posts" style of pages.
The TOC sticks to the top of page as you scroll, and disappears when the nav bar would collapse into the hamburger.

Here is the example site rendered in the light theme:
![hugo-coder-light-toc](https://user-images.githubusercontent.com/5197820/87067928-1a537400-c215-11ea-9734-eddf5a3456de.png)

And the same with the dark theme:
![hugo-coder-dark-toc](https://user-images.githubusercontent.com/5197820/87067946-22abaf00-c215-11ea-92a2-5be62cd9e20b.png)


Right-to-left doesn't look good currently, so design choices about that would be beneficial.

I'm happy to put what I have into a PR, or give it to someone who is more experienced with web design to bring it home.

**Comment by ajdintrejic** [comment]
@jsturdy this looks nice. The outline does look a wierd though. I'm running a table of contents like this: 
![image](https://user-images.githubusercontent.com/41389717/87224700-b8ffe200-c387-11ea-97da-b9fa0a9780cc.png)
it probably should look like mine on mobile, and like your's (@jsturdy) on desktop, or something similar atleast

**Comment by luizdepra** [comment]
I think I'm going to add TOC support in a near future. I should put it in the roadmap.

**Comment by luizdepra** [comment]
I'm going to follow with this discussion at #415.

**Comment by chenkai0520** [comment]
if you think this way is ok, I would be happy to create a pull requset

<https://chenkai.life/web/handling-fonts-in-the-web>
+ Widescreen
<img width="655" alt="截屏2021-09-27 下午3 34 50" src="https://user-images.githubusercontent.com/30174970/134864718-7fc3dc1c-a6b9-496f-84b6-6ab0b23a7d90.png">
<img width="453" alt="截屏2021-09-27 下午3 32 30" src="https://user-images.githubusercontent.com/30174970/134864771-8077210c-b2a8-4d98-8600-d8eb9ca886a3.png">
+ phone screen
<img width="343" alt="截屏2021-09-27 下午3 32 44" src="https://user-images.githubusercontent.com/30174970/134864928-369b234a-4f28-46a9-8b58-8c30138743ed.png">
<img width="338" alt="截屏2021-09-27 下午3 34 41" src="https://user-images.githubusercontent.com/30174970/134864942-a77f8ca4-743b-4cab-b445-7c0dee5796a7.png">
