### ISSUE TITLE
Atom autodiscovery

### ISSUE THREAD

**Issue by micheloosterhof** [luizdepra/hugo-coder#330]
Maybe it's an idea to add Atom autodiscovery into `layouts/_default/baseof.html` since an Atom feed is now included? Something like:

```
<link rel="alternate" title="RSS Feed" href="http://www.example.com/rss.xml" type="application/atom+xml" />
```

as defined in http://xml.coverpages.org/draft-ietf-atompub-autodiscovery-01.txt

**Comment by clement-pannetier** [comment]
Hi @micheloosterhof, what do you mean by:
> since an Atom feed is now included?

**Comment by micheloosterhof** [comment]
> Hi @micheloosterhof, what do you mean by:
> 
> > since an Atom feed is now included?

This PR https://github.com/luizdepra/hugo-coder/commit/e89ad7bd49c4e6da0a017a51b29573e456926def added an Atom feed.

Actually it seems there is already a `rel=alternate` but it's for `type="application/rss+xml"` while the data is actually Atom not RSS.

**Comment by clement-pannetier** [comment]
> This PR e89ad7b added an Atom feed.

That's not totally true, this file is based on the [embedded template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/rss.xml) provided by hugo, this file just overridide it's default behavior.

> while the data is actually Atom not RSS.

Moreover, an Atom template doesn't look like this, elements name are not the same, `<webmaster>` or `<managing editor>` for RSS and `<author>` for Atom for example.

**Comment by micheloosterhof** [comment]
I think what is confusing me is the use of the `<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">`. I.e. the Atom XML namespace inside the RSS feed.

In any case, the RSS feed seems to be there already.
Now I did notice one other thing, in the `hugo-coder` demo site, there are two links to the RSS feed (https://themes.gohugo.io/theme/hugo-coder/)

There's 
```
<link rel="alternate" type="application/rss+xml" href="https://themes.gohugo.io//theme/hugo-coder/index.xml" title="johndoe" />
```
and the second is:
```
<li>
  <a href="https://myhugosite.com/index.xml" aria-label="RSS" rel="alternate"  type="application/rss&#43;xml">
  <i class="fas fa-rss" aria-hidden="true"></i>
  </a>
  </li>
```
The first is from the template, the second from the RSS button, in the second one, the `type` field is escaping the `+` sign to `&#43;`.

**Comment by clement-pannetier** [comment]
> in the second one, the type field is escaping the + sign to &#43;.

I don't have this 😕.

**Comment by micheloosterhof** [comment]
Just to make sure it's not the browser:
```
$ curl -s https://themes.gohugo.io/theme/hugo-coder/ | grep -i alternate
    <link rel="alternate" type="application/rss+xml" href="https://themes.gohugo.io//theme/hugo-coder/index.xml" title="johndoe" />
            <a href="https://myhugosite.com/index.xml" aria-label="RSS" rel="alternate"  type="application/rss&#43;xml">
```

**Comment by clement-pannetier** [comment]
Ok, I have the same result, but is it a problem ? The Unicode character for `&#43;` is `+`.

The RSS button is generated thanks to these lines in `layouts/partials/home.html`:
```
<a href="{{ .url }}" aria-label="{{ .name }}" {{ if .rel }}rel="{{ .rel }}"{{ end }} {{ if .target }}target="{{ .target }}"{{ end }} {{ if .type }}type="{{ .type }}"{{ end }}>
   <i class="{{ .icon }}" aria-hidden="true"></i>
</a>
```

I tried to use functions like `htmlUnescape` without seing changes when running curl.

**Comment by luizdepra** [comment]
Wierd. Probably Hugo is making some type of automatic scaping.
