### ISSUE TITLE
Change gist style in dark mode

### ISSUE THREAD

**Issue by naim94a** [luizdepra/hugo-coder#332]
When dark mode is enabled and there is a gist embedded in the page, it doesn't look right - github's gist have a very light background, too much contrast...
Would it be possible to style github gists in the darkmode theme?

**Comment by luizdepra** [comment]
I never used embedded gist with this theme, but I think it is possible to override the default style by creating a custom CSS for the gists.

**Comment by clement-pannetier** [comment]
Hi @naim94a, It's possible by overriding the `gist-embed.css` file for example.

https://codersblock.com/blog/customizing-github-gists/
