### ISSUE TITLE
Table of Content is not linking

### ISSUE THREAD

**Issue by sariug** [luizdepra/hugo-coder#347]
Hello, 

Firstly thank you for the great work. I am sorry if this place is the wrong place to use this. 

Last year I used hugo-coder to create my website. Appearently used really old and depreciated versions that hugo 50.0 couldnt compile. 

So what bothers me right now is that I used to follow the following code in TOC:
`[Quadtree with C++](#chapter-8)`
`## Quadtree with C++ <a id="chapter-8"></a>`

and this used to navigate.
Currently it does not. I checked the example website and saw the following format:
`[Quadtree with C++](#quadtree-with-c++)` 
`## Quadtree with C++`

and it navigates. however, I do really have super long headers therefore this is so far from being optimal. Am I missing something or this is currently the only way ? 

Edit: this is the generated id: `id="quadtree-with-c-a-idchapter-8a"` so it merges.. 

Any solution to this ? 

Edit 2: Well, deleted the htmls and took care of it. Problem very close to this also happened with iframe. But I guess this is not related to you. Yet wanted to share my experience..

Edit 3: Clearly the problems are with html inputs. I still couldnt find a way to do "back to top" without html.

**Comment by clement-pannetier** [comment]
Hi @sariug,

> Any solution to this ?

Yes, use this syntax: `## Quadtree with C++ {#chapter-8}`

**Comment by sariug** [comment]
> Hi @sariug,
> 
> > Any solution to this ?
> 
> Yes, use this syntax: `## Quadtree with C++ {#chapter-8}`

Thanks for the quick answer. Would you have also any suggestion to fix the html inputs ? Clearly html inputs are not read right now.. such as  `<a id="top_point"></a>`

**Comment by clement-pannetier** [comment]
> Would you have also any suggestion to fix the html inputs ? Clearly html inputs are not read right now.. such as <a id="top_point"></a>

I don't understand what you're trying to do 🤨.

**Comment by sariug** [comment]
> > Would you have also any suggestion to fix the html inputs ? Clearly html inputs are not read right now.. such as
> 
> I don't understand what you're trying to do raised_eyebrow.

For example one of my md's was as following:

```+++
title= "Personal CV"
slug = "Resume"
+++


<object data="/pdf/Some.pdf" type="application/pdf" width="700px" height="700px">
    <embed src="/pdf/Some.pdf">
        <p>This browser does not support PDFs. Please download the PDF to view it.</p>
    </embed>
</object>

<a href="/pdf/Some.pdf">Download PDF</a>.</p>
```

It used to show directly the pdf inside. It was the same with iframes, videos etc.
Now it looks plain as if in a readme(Not exactly like this but close to this, the html part is not there as well as the Download pdf link):
![image](https://user-images.githubusercontent.com/14132181/83424807-39e4c900-a42d-11ea-902f-abd7c094df4e.png)

**Comment by clement-pannetier** [comment]
Could you provide the result (screenshot) you're looking for?

**Comment by sariug** [comment]
It was like this for example. It was really convenient to put html around for iframe as well as some navigation.

![image](https://user-images.githubusercontent.com/14132181/83428558-e6757980-a432-11ea-86df-63a20b0a189a.png)


Also, If a files name is written "file.JPG" after compiling(Not sure the correct word), it compile as "file. JPG" (with a white space between dot and J) and breaks the path.

**Comment by clement-pannetier** [comment]
I'm lost...

> It was like this for example. It was really convenient to put html around for iframe as well as some navigation.

What did you change, it's not related to the issue ?

> Now it looks plain as if in a readme(Not exactly like this but close to this, the html part is not there as well as the Download pdf link):

Do you also want the pdf to be generated when it's viewed as a md file not a blog post in your site ?

> Clearly html inputs are not read right now.. such as <a id="top_point"></a>

What does this have to do with the display of the pdf.

**Comment by sariug** [comment]
I am aware that it is getting away from the issue, however, not a good idea to open another issue or somethnig I guess.

> What did you change, it's not related to the issue ?

I basicly just updated everything(Nothing in the code). pulled the current master. build with the newest hugo. 

> Do you also want the pdf to be generated when it's viewed as a md file not a blog post in your site ?

I was pretty happy with the iframe viewer situation.

> What does this have to do with the display of the pdf.

PDF code was a direct iframe : 
```
<object data="/pdf/Some.pdf" type="application/pdf" width="700px" height="700px">
    <embed src="/pdf/Some.pdf">
        <p>This browser does not support PDFs. Please download the PDF to view it.</p>
    </embed>
</object>
```

**Comment by clement-pannetier** [comment]
> I basicly just updated everything(Nothing in the code). pulled the current master. build with the newest hugo.

Why you needed to update the hugo version? Since 0.60, Goldmark is the new markdown rendering engine, maybe it's related to this change.

**Comment by sariug** [comment]
> > I basicly just updated everything(Nothing in the code). pulled the current master. build with the newest hugo.
> 
> Why you needed to update the hugo version? Since 0.60, Goldmark is the new markdown rendering engine, maybe it's related to this change.

Sorry for late reply. Your suggestion is a great solution. As a person like me who is not a webdeveloper looking for something just working. I just downloaded 0.59.1 and all works good. Thanks again @clement-pannetier
