### ISSUE TITLE
Time of the blogs published is always "00:00:00"

### ISSUE THREAD

**Issue by utkarsh2102** [luizdepra/hugo-coder#348]
Hi,

It gets a little inconvenient to see that each of the blog gets published at "00:00:00".
Can this be fixed?
Or is there any workaround for it?

**Comment by clement-pannetier** [comment]
Hi @utkarsh2102,

Can you explain more what's your problem? Are you talking about the default date value for new blog posts?

**Comment by utkarsh2102** [comment]
Hiya,

Yeah, by default the time that appeared on my blogs was 00:00.
I just found out that we need to add the time with the date itself.

**Comment by utkarsh2102** [comment]
On another note, can we have another variable, `time`, after `date`, which takes in the time explicitly?

**Comment by clement-pannetier** [comment]
> Yeah, by default the time that appeared on my blogs was 00:00.

The time is not displayed on the blog posts unless you change the `dateFormat` config parameter to this for example: `02 Jan 06 15:04 MST`.

I think you're talking about the time displayed in the RSS feed, is that right ?
Also, if you run `hugo new posts/filename.md`, the date and time are automatically writed in the new post file.

> On another note, can we have another variable, time, after date, which takes in the time explicitly?

For which purpose?

**Comment by utkarsh2102** [comment]
Hey,

> I think you're talking about the time displayed in the RSS feed, is that right ?

You are very right! :smile: 

> Also, if you run hugo new posts/filename.md, the date and time are automatically writed in the new post file.

Aha, perfect! :100: 

> For which purpose?

I think I was using it wrong so far, thanks to you, I understood the right way :rocket:
