### ISSUE TITLE
Make Build error

### ISSUE THREAD

**Issue by atmosmaciel** [luizdepra/hugo-coder#35]
I have the following problem, I follow the correct installation steps of the Hugo Coder theme but at the time of making the build I get the following message:

```
rm -f ./static/css/*.css
rm -rf demo
lessc ./static/less/style.less > ./static/css/tmp.css
/bin/sh: lessc: command not found
```
I have already checked that there are no problems in Make configuration and no OS libs...

Any idea how to make it work?
Thank you very much in advance...

**Comment by khos2ow** [comment]
`make` build depends on `lessc` and `uglifycss`, you can install both of them with `npm`. And I believe this is missing from the documentation or guide.

**Comment by atmosmaciel** [comment]
Perfect, that solved my problem! I took advantage of it and also made a suggestion for improvement in the installation guide. :)
