### ISSUE TITLE
how to add light and dark mode switching button in the index page

### ISSUE THREAD

**Issue by iamrajiv** [luizdepra/hugo-coder#350]
how to add light and dark mode switching button in the index page
<img width="88" alt="Screenshot 2020-06-03 at 5 54 57 PM" src="https://user-images.githubusercontent.com/42106787/83636304-59adf580-a5c3-11ea-944f-ab2f7205f3e2.png">
I have edited `config.toml` by adding `colorscheme = "auto"` but I am not getting it.

**Comment by clement-pannetier** [comment]
Hi @rajmahendra, this feature has been discussed here #226 but the "automagic" solution has been chosen. We chose the prefers-color-scheme approach.

You can see an implementation of this functionnality on my GitLab repo: https://gitlab.com/clement-pannetier/clementpannetier.dev and see it directly on my website: https://clementpannetier.dev

**Just a quick note, you're maybe going to experience FOUC problems when switching themes**

**Comment by nturaga** [comment]
Is there a PR for this?

**Comment by clement-pannetier** [comment]
> Is there a PR for this?

No

**Comment by nturaga** [comment]
@clement-pannetier Can you highlight which parts of the code are the ones needed specifically? I'm unable to get it working on mine.

**Comment by clement-pannetier** [comment]
@nturaga ⬆😉
