### ISSUE TITLE
How to use shortcodes on homepage?

### ISSUE THREAD

**Issue by rchaganti** [luizdepra/hugo-coder#351]
I am quite new to Hugo and still figuring out a few things.

I have a few custom shortcodes I created for flairs and badges (SO, GitHub, etc). However, if I try to use these shortcodes in home.html, I see errors that the shortcode is not a function. From that, I assume that shortcodes cannot be used in homepage template. If so, is there a workaround?

**Comment by clement-pannetier** [comment]
Hi @rchaganti,

Shortcodes are meant to be used in your content files, not template/layout files.

From the docs: https://gohugo.io/content-management/shortcodes/

> A shortcode is a simple snippet inside a content file that Hugo will render using a predefined template. Note that shortcodes will not work in template files. If you need the type of drop-in functionality that shortcodes provide but in a template, you most likely want a partial template 5 instead.

_Source: https://discourse.gohugo.io/t/error-using-shortcodes-in-template-block-redefinition/22211_

**Comment by rchaganti** [comment]
Thank you! I will try partials!
