### ISSUE TITLE
Pages and posts in alternate languages

### ISSUE THREAD

**Issue by njcorona** [luizdepra/hugo-coder#352]
I am setting up my site to have English (en, the default) and Spanish (es-co) options.  

I wrote one blog post in English and Spanish (they are two different Markdown files, one in English and one in Spanish).  

Can I set up my content folder and Markdown files such that when my site is in Spanish mode and I click 'Blog', it shows the Blog page with my Spanish posts and when my site is in the default English mode and I click 'Blog', it shows the Blog page with my English posts?  

What should the parameters for the Spanish 'Blog' button be in config.toml?

**Comment by njcorona** [comment]
When the site is in Spanish mode, the url changes to baseurl.com/es-co/posts for the Blog page or baseurl.com/es-co/about for the about page, but it give a 404 error instead of showing the Spanish versions of the pages.  I played around with renaming the Spanish files filename.es-co.md, like in the exampleSite, and I tried making a folder called es-co in the content folder.  I wasn't able to get it to work with those.

**Comment by a1x42** [comment]
can you post the languages part of your config?

**Comment by luizdepra** [comment]
> Can I set up my content folder and Markdown files such that when my site is in Spanish mode and I click 'Blog', it shows the Blog page with my Spanish posts and when my site is in the default English mode and I click 'Blog', it shows the Blog page with my English posts?
Yes. The `exampleSite` does that. You can set your menu url with a leading `/` or make custom menu items for each language. See [here](https://github.com/luizdepra/hugo-coder/blob/master/exampleSite/config.toml#L151).

> When the site is in Spanish mode, the url changes to baseurl.com/es-co/posts for the Blog page or baseurl.com/es-co/about for the about page, but it give a 404 error instead of showing the Spanish versions of the pages. I played around with renaming the Spanish files filename.es-co.md, like in the exampleSite, and I tried making a folder called es-co in the content folder. I wasn't able to get it to work with those.
Well, this is weird. Could you share your config.toml or repository if it is open?

**Comment by njcorona** [comment]
My repository is private right now.  Here's my config.toml (saved into a text file so I can attach it here) and a screenshot of my ~/content folder - let me know if you'd like me to share anything else.  Thank you for your help!

[config.txt](https://github.com/luizdepra/hugo-coder/files/4755232/config.txt)

My website, currently set up with these files, is at nicolascorona.com.

![image](https://user-images.githubusercontent.com/43733460/84207795-3205d400-aa80-11ea-808b-c06781ca82e5.png)

**Comment by a1x42** [comment]
the Blog link in the spanish section should say posts not posts-spanish

**Comment by a1x42** [comment]
and then you create posts in the same source dir as for english ones just with .es-co.md extension

**Comment by njcorona** [comment]
Excellent, it's fixed.  Thank you, @a1x42!

I am attaching the current state of the config.toml file and the ~/content folder for reference.
![image](https://user-images.githubusercontent.com/43733460/84541072-9c0ebb00-acc4-11ea-9287-f14a27188db2.png)
[config.txt](https://github.com/luizdepra/hugo-coder/files/4772921/config.txt)
