### ISSUE TITLE
server start error

### ISSUE THREAD

**Issue by sgouda835** [luizdepra/hugo-coder#353]
λ hugo server -D
Building sites … Built in 67 ms
Error: Error building site: TOCSS: failed to transform "style.coder.css" (text/x-scss): resource "scss/scss/coder.scss_fd4b5b3f9a48bc0c7f005d2f7a4cc30f" not found in file cache

**Comment by clement-pannetier** [comment]
#343

**Comment by luizdepra** [comment]
Ty, @clement-pannetier.
Closing.
