### ISSUE TITLE
Reducing space between headings and paragraph

### ISSUE THREAD

**Issue by rchaganti** [luizdepra/hugo-coder#354]
I see a lot of whitespace on a page when I have multiple headings on the same page. 
Example: https://ravichaganti.com/books/

Is there a way to address this? I am assuming that I have to fix some CSS but I am not an expert in that area. Thanks for your help and a great theme.

**Comment by clement-pannetier** [comment]
Hi @rchaganti,

You can edit the `assets/scss/_base.scss` file under h* selectors -> margin.

**Comment by rchaganti** [comment]
Thanks! But, when I update the REM values, I don't see that reflecting on the page. I tried reloading the local server too.

**Comment by clement-pannetier** [comment]
It should work and it works for me, which file did you edit ? What's your directory structure ?

**Comment by rchaganti** [comment]
![blog](https://user-images.githubusercontent.com/1748744/85867307-5551b280-b7e6-11ea-90d1-042959e4db92.png)
Here is the directory structure. I tried multiple times but no luck so far.

**Comment by luizdepra** [comment]
Are you using Hugo Extended version? If you are using the default version, Hugo will not build the SCSS file.

**Comment by rchaganti** [comment]
Great! Thanks for the help. I was using Hugo default version and downloaded extended to try this.
