### ISSUE TITLE
Weird display of image while sharing blogs on Twitter

### ISSUE THREAD

**Issue by utkarsh2102** [luizdepra/hugo-coder#356]
![image](https://user-images.githubusercontent.com/31288318/85879441-00b73300-b7f8-11ea-9af0-eb50e1c28c03.png)

This looks..bad, I think. I am not sure what renders it likes this because the original image used is really small (see: https://utkarsh2102.com/posts/foss-in-may-20/).

I am not sure what's the fix either. Any ideas?

**Comment by utkarsh2102** [comment]
Maybe something relevant: https://stackoverflow.com/questions/17825195/twitter-share-button-but-with-image
But I am not sure :sweat_smile:

**Comment by luizdepra** [comment]
Yup! You can tweak that kind of thing with twitter card data.
Hugo already supports it, but this theme yet not. But it is possible to add it.

https://gohugo.io/templates/internal/#twitter-cards

**Comment by utkarsh2102** [comment]
Aha!
Would you be interested to have it here as well?

**Comment by luizdepra** [comment]
Sure, why not? :)

**Comment by luizdepra** [comment]
I'm going to add twitter cards and other kind of social media things into the v2 roadmap.

**Comment by pduchnovsky** [comment]
Twitter cards are working fine for me, I only add this to markdown header of new page/post and it works:
```
images:
    - /images/something.jpg
```
Or this, depending how your header is set up :)
```
images = ["/images/something.jpg"]
```


As for 'default' twitter card (shown if not specified in post/page), this works in global config:
```
[params]
    images = ["/images/something.jpg"]
```

**Comment by luizdepra** [comment]
I think this is related with the resolution of the image used right? Going to close this issue, but if it still persist let me know.
