### ISSUE TITLE
Post pages are not opening after the source repo branch rename 

### ISSUE THREAD

**Issue by rchaganti** [luizdepra/hugo-coder#360]
I am not sure if these are related events but I just renamed my source repo (that contains *.md and theme files and not the public repo for site rchaganti.github.io) master branch to live. I am now using a draft branch in that repo for all the writing and merge a PR into live when I am ready to publish. After I set this up, the blog pages are not opening anymore. https://www.ravichaganti.com/blog/ points to home page. All individual blog articles open a blank page.

What did I mess up? I am using Hugo extended 0.73.

**Comment by luizdepra** [comment]
Taking a look into your public repo (https://github.com/rchaganti/rchaganti.github.io/tree/master/blog) everything seems fine.
I don't think that there is a problem with hugo-coder or even hugo here. Your deploy seems fine too.
Maybe, is there a misconfigured DNS rule for your domain?

**Comment by rchaganti** [comment]
Thanks for looking at this, Luiz. I have not changed anything in the DNS since I set up this site. I will check that DNS anyway.

**Comment by rchaganti** [comment]
closing this here. I was using peaceiris/actions-gh-pages and the default settings were pushing static pages to a new branch called gh-pages. This was changing the cname also to a different repo than the public repo I had initially configured. It was failing there for whatever reason.
