### ISSUE TITLE
Switch to Fork Awesome, or make the font location customizable

### ISSUE THREAD

**Issue by paride** [luizdepra/hugo-coder#361]
While free to use, Font Awesome is not free software. Fork Awesome (https://forkaweso.me/) can mostly replace it, and it's MIT licensed like hugo-coder.

Bonus point: it has a Debian icon, which Fork Awesome lacks :)

If you are not willing to switch, then it would be nice to have the possibility to override the font css location set in `baseof.html` with a custom location from the `config.toml` file.

**Comment by luizdepra** [comment]
No objection. Would be nice if you create a PR to change it.

**Comment by sdwolfz** [comment]
On my fork I've removed the hardcoded Font Awesome and am serving them from assets, was thinking of implementing this but did not know about Fork Awesome.

Give me a weekend and I might be able to open a PR.

**Comment by metbril** [comment]
I second the option to locally host my fonts (no tracking, no external dependencies).

**Comment by luizdepra** [comment]
We have a branch with locally hosted fonts, scripts, etc. It can be used as a base for these changes, but it is really outdated.

**Comment by luizdepra** [comment]
Doing to put this into v2 roadmap.

**Comment by luizdepra** [comment]
Let's continue the discussion at #412.
