### ISSUE TITLE
custom.css and header images

### ISSUE THREAD

**Issue by theapiarist** [luizdepra/hugo-coder#365]
I'm a beginner with hugo and themes switching from wordpress.

I'm trying to override some styles in **_content.scss**. My **config.toml** has 

`custom_css = ["scss/custom.scss"]`

in [params] and I've placed the modified file in [siteroot]/assets/scss/custom.scss (newly created) but the overrides are not being picked up. My **config.toml** has baseurl = "http://localhost/". If I edit **_content.scss** the changes I make work, so I'm thinking this is a file location issue. I'm running the current extended version of hugo on a Mac. 

I'd also like to introduce header images and assume these will need to go into [siteroot]/layouts/partials/posts/header.html to override the theme version in /layouts/partials/header.html

Thanks for this very readable theme.  I've also read the Projects discussion with interest and look forward to trying that as well.

**Comment by clement-pannetier** [comment]
Hi @theapiarist, you just have to use the `custom_**s**css` config variable not this one `custom_css`.
If you override scss theme files, you don't need to use it.

**Comment by theapiarist** [comment]
Many thanks … I’ll try again.
The Github page for Coder is currently giving a 500 server error.
Regards
David

**Comment by theapiarist** [comment]
I see all Github pages have a problem … not just coder.
David
