### ISSUE TITLE
Random header images - readDir and shuffle?

### ISSUE THREAD

**Issue by theapiarist** [luizdepra/hugo-coder#366]
I'm trying to insert a build-time random header image into certain posts and pages. I've worked out where to insert it e.g. single.html and have seen some implementations with javascript. 

However, it should be possible by passing a directory name in the front matter e.g. random_image: /headers (relative to static) and then reading the directory, shuffling it and returning the file for display. There's [one discussion of this](https://discourse.gohugo.io/t/readdir-not-return-filename/21415/3) on golang.org, but I cannot get it to work as it returns a hash key by the looks of things [randomstring] (when I get it to return anything).

The solution on gohugo.io was:

```
{{ $dir := "cool-images" }}
{{ $images := readDir $dir | shuffle }}
{{ $first := index $images 0 }}
{{ $path := path.Join $dir $first.Name }}
```

Does this need to be in the existing header partial, or in a new one, called from header.html if the front matter directory is not ""?

The same solution includes reference to page bundles, but I want the random headers to be shared across all posts (and some other content types).

Is there a better was to achieve this?

Seven years of poorly understood wordpress 'features' are slowly being replaced. Astonished by build speed and (Netlify) hosting speed of delivery of hugo.

**Comment by clement-pannetier** [comment]
Hi @theapiarist.

> I'm trying to insert a build-time random header image into certain posts and pages.

Are you trying to set an header image each time you refresh the webpage / click on a post or when you create a new post with for example the `hugo new` command ?

> Does this need to be in the existing header partial, or in a new one, called from header.html if the front matter directory is not ""?

I don't understand exactly what you want, please show an example / screenshot.
Is it something like that ?
![image](https://user-images.githubusercontent.com/35581688/87475135-8888a400-c624-11ea-851f-3378f4c12faf.png)

**Comment by theapiarist** [comment]
Hi

Apologies … here’s a example. 

I can insert an image where I want - in this case by adding a couple of lines to an override version of single.html. This is a screenshot of the site being developed.



However, this has the image name hard coded into the front matter.

What I want to do is select ALL images in a directory (name of directory provided in front matter) and choose one at random to insert into the page at build time. Every time the page is loaded the image changes, every time I add another page or edit a page and rebuild, the image changes.

All the images are the same size/dimensions so the formatting is retained. 

I think I should be able to do this by (pseudocode) …

readDir .Params.random_dir
shuffle filenames read
selecting one at random
displaying it

I live in a very scenic part of north west Scotland and have hundreds of images to use in this way.

I hope this makes a bit more sense :)

With thanks

**Comment by clement-pannetier** [comment]
I can't see the image...

**Comment by theapiarist** [comment]
Apologies again ... that's what comes of emailing a reply rather than going to GitHub. File attached.
I realise that this might be better directed to the hugo community rather then being theme-specific.

![Screenshot 2020-07-14 22 31 34](https://user-images.githubusercontent.com/53646689/87542290-a09b0a80-c69a-11ea-9ccd-eeccae4f8215.png)

**Comment by clement-pannetier** [comment]
> The same solution includes reference to page bundles, but I want the random headers to be shared across all posts (and some other content types).

I think it's not a good idea and therefore you don't need image processing features page bundles offers so just use the static dir.

> I can insert an image where I want - in this case by adding a couple of lines to an override version of single.html. This is a screenshot of the site being developed.

Does it change the image when you reload the page, it doesn't for me (with the code you provided), it does only if I go back to blog page for example and click again on the blog post ?

> However, this has the image name hard coded into the front matter.

I don't understand, the front matter is defined inside your `.md` files, not in layouts files !?

**Comment by theapiarist** [comment]
Front matter defines the location of the random images e.g. /static/posts/random and /static/projects/random, the page template then contains code to `readDir` the image files in the directory defined in the front matter, `shuffle` the files and select one at random to embed at build time. That way posts and projects can use different types/sizes of random headers. Every time I make changes to the site - a new post, an edit etc - if I choose a complete rebuild and cache invalidation, all posts will get new header images. The code I provided does not work - I either get a static image or a hex code which suggests I'm using readDir and shuffle incorrectly.

I'm going to close this and chat with some people on discourse.gohugo.io. I'll post an update if/when I get a solution.

Really like the theme. Nice and clean. Logical locations for the files and a clear layout. Many thanks.
