### ISSUE TITLE
Post not appearing without referencing index.html

### ISSUE THREAD

**Issue by rchaganti** [luizdepra/hugo-coder#367]
I just published a page at https://ravichaganti.com/blog/azure-resource-manager-introduction/ and this is redirecting to 404. However, if I add index.html, I can access the published content. I have been publishing on this site and did not have any such issue. I don't know if this is an issue with the meta data but all that seems good to me. Any thoughts?

**Comment by rchaganti** [comment]
I updated the meta data by copying the same from another post and published again. It worked this time. What could have gone wrong in the initial commit? The new meta data is same as the old one.

**Comment by clement-pannetier** [comment]
Hi @rchaganti, do you have the front matter variable `date` on your .md blog post file ?

It's maybe related to this if it was set to a future date. To build posts with a future date, try this command `hugo -F`.

**Comment by luizdepra** [comment]
Also, posts with `draft = true` will not be rendered unless you tell Hugo to do so.

**Comment by rchaganti** [comment]
This is what I had in the front matter.

title: "Azure Resource Manager - Introduction"
date: 2020-07-16
toc: true
slug: "azure-resource-manager-introduction" 
tags: ["Azure Resource Manager","Azure"]
series: ["Azure Resource Manager In 30 Days"]
categories: ["Azure Resource Manager","Azure"]

I removed draft: true before committing this MD into my repo.

**Comment by rchaganti** [comment]
And, same problem today again. I published another article after removing draft: true. I can access it if I suffix index.html. https://ravichaganti.com/blog/azure-resource-manager-tools-for-arm-template-design-authoring-and-deployment/index.html

**Comment by luizdepra** [comment]
I understand the problem now.
I can access your post normally here: https://ravichaganti.com/blog/azure-resource-manager-tools-for-arm-template-design-authoring-and-deployment/
Are you sure that this is not a deployment or caching problem?

**Comment by rchaganti** [comment]
Interesting. This is happening with posts that I author with date set to a future date. I am using GitHub pages and use a GitHub action to deploy from a private repo. I need to check if there is something [within this workflow](https://ravichaganti.com/blog/github-workflow-for-streamlined-publishing-of-static-pages/).

**Comment by rchaganti** [comment]
closing this issue as it seems more like a caching issue on GitHub pages side.

**Comment by rchaganti** [comment]
I am reopening this since I am seeing it again and came across a support post that says this could be because of the theme. https://github.community/t/github-page-blank-after-deploy-failed-to-load-resource-the-server-responded-with-a-status-of-404/10577

I have another article that I just published that does not load at all. 
https://ravichaganti.com/blog/get-set-go-introduction-to-go-lang/index.html

This does not work whether I use index.html or not. Earlier posts used to work if I suffix index.html.

**Comment by clement-pannetier** [comment]
> I have another article that I just published that does not load at all.

It loads fine on my browser..., using index.html or not. 🤷‍♂️

**Comment by luizdepra** [comment]
It is really weird, @rchaganti. But I still think this is not related with the theme or hugo build.
