### ISSUE TITLE
Could not find style module 'b2'

### ISSUE THREAD

**Issue by rschmidtz** [luizdepra/hugo-coder#37]
Hi all
After the command

`make demo
`
the build fails with the following error:

`ERROR 2018/06/25 21:31:05 Error: Could not find style module 'b2'.
`

**Comment by luizdepra** [comment]
Witch version of Hugo are you using?
Maybe you haven't installed pygments? Although, I think you don't need it anymore with Hugo newer versions.

**Comment by rschmidtz** [comment]
I was using an old version of Hugo, I updated and now is working.
Thanks.
