### ISSUE TITLE
Singular translation reading time missing for English

### ISSUE THREAD

**Issue by metbril** [luizdepra/hugo-coder#371]
The singular translation for reading time is missing for the English translation

https://github.com/luizdepra/hugo-coder/blob/f46d1e2c3ec58ead0c282951e9247f234e26d5e3/i18n/en.toml#L10

**Comment by clement-pannetier** [comment]
The singular translation was removed here #251. English is not my native language so I can't tell whether he is right or wrong.

**Comment by metbril** [comment]
Removing the 'one' translation will work grammarly. It's personal preference to use a cipher or a word for one. For future translators it would be more clear that they need to add the item. 

Current English: '1-minute read'
Proposed English: 'One-minute read'

Both are correct English. If you hesitate a compromise would be re-add the one parameter but leave the cipher notation.
