### ISSUE TITLE
Reading time missing when language not available

### ISSUE THREAD

**Issue by metbril** [luizdepra/hugo-coder#373]
When there is no i18n file for the site language in the theme, the reading time is shown 'empty'. There should be a default (English) so the reading time is always shown.

See example if site language is `nl`.

<img width="622" alt="Schermafbeelding 2020-07-18 om 07 14 58" src="https://user-images.githubusercontent.com/559346/87845333-9cebcb80-c8c6-11ea-887d-b41344eb47cc.png">

**Comment by luizdepra** [comment]
We can add a `default` filter to every translation.
I thought that Hugo would do that for us but doesn't seem the case here.

**Comment by luizdepra** [comment]
Related to #417.

**Comment by luizdepra** [comment]
If I remember well, this issues was resolved. So, closing.
