### ISSUE TITLE
disable google Analytics for local render

### ISSUE THREAD

**Issue by rchaganti** [luizdepra/hugo-coder#379]
I had google analytics enabled for my site and I have the following line in Single.html.

{{ template "_internal/google_analytics_async.html" . }}

I have now updated it to 
        {{ if not (in (.Site.BaseURL | string) "localhost") }}
          {{ template "_internal/google_analytics_async.html" . }}
        {{ end }}

so that it does not load GA for localhost. Is this good enough? In F12 developer options, I still see GA loading on the page.

**Comment by clement-pannetier** [comment]
Hi @rchaganti, you should use this instead `{{ if .Site.IsServer }}`.

**Comment by rchaganti** [comment]
You meant like this?

```
        {{ if not .Site.IsServer }}
          {{ template "_internal/google_analytics_async.html" . }}
        {{ end }}
```

I have this in both layouts/blog/single.html and layouts/index.html. I still see the GA related elements in the generated HTML.
![ga](https://user-images.githubusercontent.com/1748744/88036536-4ea62900-cb61-11ea-94e5-941b28066186.png)

**Comment by clement-pannetier** [comment]
> I have the following line in Single.html.

I didn't saw that, you have to update the `baseof.html` file, not this one. The GA line is already written, you just have to surround it with the condition.

**Comment by rchaganti** [comment]
Perfect! Thank you!
