### ISSUE TITLE
Sorting Series article links from oldest to newest

### ISSUE THREAD

**Issue by rchaganti** [luizdepra/hugo-coder#380]
By default, when I go to a series URL, the list of articles is shown from newest to oldest. However, is there a way we can display from oldest to newest?

**Comment by clement-pannetier** [comment]
Hi @rchaganti, you can see the documentation [here](https://gohugo.io/templates/lists/#order-content).
And the corresponding file is `layouts/partials/list.html`. Simply add the `.Reverse` method.
Be careful, it's the default `list.html` file so it renders the others taxonomies.

**Comment by rchaganti** [comment]
I see what you meant there. Is there a way to separate out what the series uses as a list template?

**Comment by clement-pannetier** [comment]
@rchaganti, yes, you can create a `layouts/series/list.html` file. It's the same method as content types like `posts` or `projects`.

**Comment by rchaganti** [comment]
Sorry! couldn't try this until today. I tried using the same list.html from layouts/partials/list.html, updated it to add .Reverse method and copied it to layouts/series/list.html under the theme folder. But, this had no effect on the ordering of the articles in a series page.

**Comment by clement-pannetier** [comment]
@rchaganti, I's working fine on my side...🤔
In the `layouts/series/list.html` file you changed this `{{ range .Paginator.Pages }}` to this `{{ range .Paginator.Pages.Reverse }}` right ?
Which hugo version are you running ?

**Comment by luizdepra** [comment]
I thing we can close this one, right?
