### ISSUE TITLE
Issue with integrating <kbd>

### ISSUE THREAD

**Issue by MMilczynski** [luizdepra/hugo-coder#383]
Hi, I wanted to use the "kbd" tag for displaying nicely styled keyboard shortcuts but without success. I tried creating a shortcode and created custom css styling but that didn't work. I'm honestly not sure where to put custom css? static/css or assets/css?
Thanks,
MM

**Comment by clement-pannetier** [comment]
Hi @MMilczynski, to add custom css, simply put your css file under `static/css/` folder and set the `custom_css` `config.toml` configuration to `['css/name_of_your_file.css']`.

**Comment by MMilczynski** [comment]
Ok, Thanks for clarifying that. I figured it out now by creating a kbd shortcode with custom styling in the location you mentioned above. Many thanks!
