### ISSUE TITLE
Error when trying to serve site

### ISSUE THREAD

**Issue by TiborGalko** [luizdepra/hugo-coder#386]
Hi,
I'm trying Hugo for the first time and wanted to check out this theme. When I tried serving my page i got these errors about null pointers to resources or not working links. I installed hugo and hugo-extended on windows with chocolatey. Ananke theme from quickstart guide works fine.
Thanks for any help.

`Building sites … ERROR 2020/08/12 21:40:14 render of "taxonomy" failed: "...\portfolio\themes\hugo-coder\layouts\_default\baseof.html:114:29": execute of template failed: template: _default/list.html:114:29: executing "_default/list.html" at <$script.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
ERROR 2020/08/12 21:40:14 render of "taxonomy" failed: "...\portfolio\themes\hugo-coder\layouts\_default\baseof.html:114:29": execute of template failed: template: _default/list.html:114:29: executing "_default/list.html" at <$script.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
ERROR 2020/08/12 21:40:14 render of "taxonomy" failed: "...\portfolio\themes\hugo-coder\layouts\_default\baseof.html:114:29": execute of template failed: template: _default/list.html:114:29: executing "_default/list.html" at <$script.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
Built in 33 ms
Error: Error building site: failed to render pages: render of "home" failed: "...\portfolio\themes\hugo-coder\layouts\_default\baseof.html:114:29": execute of template failed: template: index.html:114:29: executing "index.html" at <$script.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink`

**Comment by 3gcodes** [comment]
This needs to get merged. Ran into this today.

**Comment by TiborGalko** [comment]
Tried this PR and it fixed my issue. No errors after.

**Comment by KeithETruesdell** [comment]
got this same issue the past couple days as well

**Comment by luizdepra** [comment]
I just merged the fix. Thanks.
