### ISSUE TITLE
Plausible integration has issues

### ISSUE THREAD

**Issue by jensenmo** [luizdepra/hugo-coder#388]
There are a couple of issues with the plausible.io integration:
* The wrong endpoint is used: `/js/index.js`, which should be: `/js/plausible.js`
* The wrong (non-ASCII) quotes are used in the plausible.html, which is stopping calls from being made to plausible
Original:
```
<script async defer data-domain=”{{ .Site.Params.plausibleAnalytics.domain }}” src=”https://{{ .Site.Params.plausibleAnalytics.serverURL | default "plausible.io" }}/js/index.js”></script> 
```
Should be:
```
<script async defer data-domain="{{ .Site.Params.plausibleAnalytics.domain }}" src="https://{{ .Site.Params.plausibleAnalytics.serverURL | default `plausible.io` }}/js/plausible.js"></script>
```

**Comment by luizdepra** [comment]
I would appreciate if you open a PR to fix the issue.
