### ISSUE TITLE
Add live version for previewing current state?

### ISSUE THREAD

**Issue by netrules** [luizdepra/hugo-coder#392]
Not much to describe here, need a live version in order to see current features and what has been implemented since my last fork. I have been considering to re-fork and re-implement my changes, but taking into account how time consuming that could be, I'd like to know if any of the recent commits are useful to me or whether I should PR some of the things I've added to my fork.

Thanks.

**Comment by clement-pannetier** [comment]
Hi @netrules,

Link to the live version of the master branch : https://hugo-coder.netlify.app

You can also use this type of URL : https://deploy-preview-<PR_number>--hugo-coder.netlify.app/

**Comment by netrules** [comment]
Oh. Sorry, I didn't see that. I see several things have been added to the UI which I like :). Also a couple other commits I might merge as well. Should this URL be added to the readme or repo website?

**Comment by luizdepra** [comment]
Nice idea. I just added it to the readme.
