### ISSUE TITLE
Remove toggle between light and dark mode?

### ISSUE THREAD

**Issue by jflipp** [luizdepra/hugo-coder#395]
I use hugo-coder for my blog, but I would like to remove the toggle between light and dark mode in the header, just right of the main menu.

What's a good way to do this?

I set the parameter colorscheme in config.toml to "light", but this doesn't hide the toggle.
I looked at hugo-coder/layouts/partials/header.html, but there are no useful variables controlling the appearence of the toggle.
I found the wiki page about inverted colors, but currently that's a WIP.
I found several issues concerning light and dark mode, but none that addressed my problem.

So, what's a good, "canonical" way to remove that toggle?

Thanks for your help.

**Comment by luizdepra** [comment]
For now, you need to remove it manually from the navigation bar template.
Need help doing?

**Comment by jflipp** [comment]
\# For now, you need to remove it manually from the navigation bar template.
Thanks for the tip.

\# Need help doing this?
I can manage this.  :-)
