### ISSUE TITLE
How to add custom 404 page?

### ISSUE THREAD

**Issue by PiotrWachulec** [luizdepra/hugo-coder#396]
Hi!

Like in the topic I would like to add to my page custom 404 page. I followed [the official tutorial](https://gohugo.io/templates/404/), but it doesn't work with this theme. I got something what is shown on the picture below:
![Zrzut ekranu z 2020-08-20 10-24-26](https://user-images.githubusercontent.com/11841233/90741223-6ba05a00-e2cf-11ea-96a5-649c1859a290.png)
Is there any way to add such a page with this theme?

Thanks in advance!

**Comment by luizdepra** [comment]
Well, this theme provides a default 404 page as you can see [here](https://hugo-coder.netlify.app/notfound).

Are you trying to customize it?

But I need to mention that you'll be unable to see the 404 page if you're testing your deployment with `hugo server` command.

**Comment by PiotrWachulec** [comment]
From official docs:

> hugo server will not automatically load your custom 404.html file, but you can test the appearance of your custom “not found” page by navigating your browser to /404.html.

When I run hugo server and I go on http://localhost:1313/404.html I see theme default 404 page. But I would like to customize it :) How can I do that?

**Comment by clement-pannetier** [comment]
Hi @PiotrWachulec, to customize the 404 page, you have to change [this file](https://www.github.com/luizdepra/hugo-coder/tree/master/layouts%2Fpartials%2F404.html).

**Comment by PiotrWachulec** [comment]
Ok, so when I added this theme as submodule then I can have problems with updating theme when I will change this file.

**Comment by luizdepra** [comment]
I don't remember now, but I think you can override only this file by creating `layouts/404.html` on your site root. But I may be wrong.
You also can fork this project, change what you want and use the fork as a submodule.

**Comment by clement-pannetier** [comment]
> I don't remember now, but I think you can override only this file by creating `layouts/404.html` on your site root. But I may be wrong.

👍 but to override the `404.html` file you have to create it under `layouts/partials/404.html` not `layouts/404.html`.

**Comment by PiotrWachulec** [comment]
Ok, I'll try to override it under `layouts/partials/404.html` and I'll get back with the answer. Thanks @luizdepra and @clement-pannetier !

**Comment by PiotrWachulec** [comment]
@clement-pannetier and @luizdepra overriding `layouts/partials/404.html` works! Thanks a lot for your help! :)
