### ISSUE TITLE
Deploy to Netlify doesn't show theme

### ISSUE THREAD

**Issue by maxdrohde** [luizdepra/hugo-coder#398]
When I deploy to Netlify, the page loads but the theme does not show properly.

Everything looks fine when I deploy locally with `hugo serve`

Any thoughts on what may be causing this? I set the `base_url` up properly.

<img width="900" alt="Screen Shot 2020-08-27 at 10 36 05 AM" src="https://user-images.githubusercontent.com/25734232/91463553-25a84080-e851-11ea-9d1a-9124c932752c.png">

**Comment by maxdrohde** [comment]
here is the website if that is helpful
https://maximilianrohde.com

and the GitHub page with the source is here
https://github.com/maxdrohde/website

**Comment by luizdepra** [comment]
Inspecting your website I saw that both CSS and JS content are suffering a redirect and so being blocked by CORS rules.

![Screenshot from 2020-08-27 13-52-55](https://user-images.githubusercontent.com/1427376/91471690-c9531a00-e86c-11ea-9a0a-986690e9a7f0.png)

You have configured your `base_url` as `https://www.maximilianrohde.com`. I think It should work fine if you remove the subdomain `www`, so changing `base_url` to `https://maximilianrohde.com`.

**Comment by maxdrohde** [comment]
That fixed it, thank you!
