### ISSUE TITLE
Page after deployment to GitHub Pages didn't load custom css

### ISSUE THREAD

**Issue by PiotrWachulec** [luizdepra/hugo-coder#400]
After updating to v0.2 I'm getting the message when I deploy my page to GitHub Pages, I'm getting an error related to custom css:
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://devdiary.wachulec.me/css/newsletter-form.41ab8feeeba31fe76d273b3cf27a31ff6acd2203b4c18108390653b995d72a80.css' with computed SHA-256 integrity 'GeWA05DEnpmOAEbv24B8taIzq+jKlpCHi6kvlUlFoqQ='. The resource has been blocked.
```
Used Hugo version: v0.74.3/extended

**Comment by luizdepra** [comment]
Hey!
What do you mean when you say you've updated to v0.2?

Well, the `newsletter-form` is not a CSS file from this theme. Have you added a custom CSS or something like that?

**Comment by PiotrWachulec** [comment]
Sorry @luizdepra , I opened issue in the not related repository 😂 Sorry again for that!
