### ISSUE TITLE
add search functionality

### ISSUE THREAD

**Issue by sangeet259** [luizdepra/hugo-coder#404]
Hey is there a way to implement the search functionality in the theme.
There is some work here:
- https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae
- https://github.com/kaushalmodi/hugo-search-fuse-js

Can something be done in this regard ?

**Comment by luizdepra** [comment]
It could be done but prefer to keep this kind of JS-based feature away. Moreover, Google and DDG already do a good job on searching.
You always can fork this theme and make your changes, tho. :)
