### ISSUE TITLE
Google analytics support?

### ISSUE THREAD

**Issue by CrazyOptimist** [luizdepra/hugo-coder#409]
Thanks for your great work @luizdepra and all the contributors!
Is there anyway to figure out google analytics easily or should I write some code to create a pull request for that?
Thanks for help in advance!

**Comment by clement-pannetier** [comment]
Hi @CrazyOptimist, simply add `googleAnalytics: UA-...` to your config.toml file.
You also have the choice between fathom and plausible analytics.

**Comment by CrazyOptimist** [comment]
Thanks, I've read the latter two, just wondered about googleAnalytics.
Would be great for the users of your theme if it's added to your example site config file or to the README.
Thanks again!
