### ISSUE TITLE
[v2] Self-hosted dependencies

### ISSUE THREAD

**Issue by luizdepra** [luizdepra/hugo-coder#413]
Change all JS and CSS dependencies to self-hosting.
Some work was started in an [outdated self-hosted-deps branch](https://github.com/luizdepra/hugo-coder/tree/self-hosting-deps).

We should check if there are conflicts or problems related to the deps' licensing.

**Comment by plett** [comment]
I've grepped for all the external JS and CSS dependencies and looked up what their licenses are.
IANAL, but my interpretation of their licenses is that we would be fine to duplicate all of them in hugo-coder and distribute them. 

For details, baseof uses:
- Google Fonts (Lato, Merriweather, Source Code Pro)
All three of these fonts are under the SIL OFL Open Fonts License
https://www.fontsquirrel.com/license/lato
https://www.fontsquirrel.com/license/merriweather-sans
https://www.fontsquirrel.com/license/source-code-pro
- Fork Awesome 1.1.7
SIL OFL https://forkaweso.me/Fork-Awesome/license/
- Normalize 8.0.1
MIT https://github.com/necolas/normalize.css/blob/master/LICENSE.md
- twemoji
Graphics are CC-BY 4.0 https://github.com/twitter/twemoji/blob/master/LICENSE-GRAPHICS
Project licence looks like MIT, but isn't described as such https://github.com/twitter/twemoji/blob/master/LICENSE

And posts/math uses:
- polyfill
MIT https://github.com/Financial-Times/polyfill-service/blob/master/LICENSE.md
- mathjax
Apache https://github.com/mathjax/MathJax/blob/master/LICENSE
- katex
MIT https://github.com/KaTeX/KaTeX/blob/master/LICENSE

Other optional features:
- utterances
MIT https://github.com/utterance/utterances/blob/master/LICENSE.md
Not suitable for embedding in the theme, it needs to be the same version as the API server https://github.com/utterance/utterances/issues/42

- analytics/plausible
AGPL, but not suitable to embed in the theme, it should come from the Plausible server

- analytics/goatcounter
count.js is ISC, but also not suitable for embedding, it should come from the goatcounter server

@luizdepra How should the next steps be approached? Do you intend v2 of the theme to be self-hosted only with no external JS/CSS resources, or does it need to optional and controlled via a `$.Site.Params` setting?

Are you content with taking the final minified versions of all the code that each of the projects publishes and putting them in this repo as static assets? Or would you rather go hardcore and use `git submodule` to link to the projects source and use Hugo Pipelines to create the JS and CSS from TS and SASS etc?

**Comment by pduchnovsky** [comment]
^ I actually unknowingly of this 'issue' already migrated some of the above to self hosting in my PR, will look at selfhosting of twemoji right now.

**Comment by luizdepra** [comment]
@plett, I want to keep everything self-hosted only. Of course there is an issue with all the analytics imports, and we should keep them external. I think we should keep it simple and just add minified files as static assets.

**Comment by plett** [comment]
That sounds like a sensible approach. I'm already maintaining a fork of coder for my site with the subset of dependencies that I need as static assets, so I'm already part of the way there.

I'll wait and see how #481 goes. If this issue doesn't get fixed as part of that PR, then I'll put my own PR together.

**Comment by pduchnovsky** [comment]
Question: Have you considered moving towards web-safe fonts ?
e.g. OS default fonts like github and many other sites do ?

I am testing it on my page and it looks good, this way the site basically loads instantly without any font dependencies.

Body/headings: `-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji;`
Code: `SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace`

**Comment by rabinadk1** [comment]
I don't think hosting everything is a good idea. Many users already have downloaded the files from a popular CDN, often the one which is included in the website of the resource provider, when visiting another site. As a result, it will be loaded from the cache when they visit our site, which leads to faster loading time. Also, most CDN's will make sure that once a user requests a file from it, it will be served from the server closest to them, which also leads to faster loading time.

**Comment by pduchnovsky** [comment]
> I don't think hosting everything is a good idea. Many users already have downloaded the files from a popular CDN, often the one which is included in the website of the resource provider, when visiting another site. As a result, it will be loaded from the cache when they visit our site, which leads to faster loading time. Also, most CDN's will make sure that once a user requests a file from it, it will be served from the server closest to them, which also leads to faster loading time.

Fair points but..
#1 advantage of self-hosting is that prevents any user tracking so you don't have to have privacy policy on your site.. and you can also serve from CDN (netlify cdn, cloudflare cdn, etc.)
#2 advantage is less overall requests in case of merged css and in case of self-hosted fonts they are served from one source and combined providing faster 'final' page load

**Comment by rabinadk1** [comment]
> > I don't think hosting everything is a good idea. Many users already have downloaded the files from a popular CDN, often the one which is included in the website of the resource provider, when visiting another site. As a result, it will be loaded from the cache when they visit our site, which leads to faster loading time. Also, most CDN's will make sure that once a user requests a file from it, it will be served from the server closest to them, which also leads to faster loading time.
> 
> Fair points but..
> #1 advantage of self-hosting is that prevents any user tracking so you don't have to have privacy policy on your site.. and you can also serve from CDN (netlify cdn, cloudflare cdn, etc.)
> #2 advantage is less overall requests in case of merged css and in case of self-hosted fonts they are served from one source and combined providing faster 'final' page load

I agree with the first one. But CDN providers like jsdelivr can provide you with merged CSS and merged JS in one request. Also, if the fonts are from google like we are using now, then they come from the same source. Also, not everyone uses a CDN to host their website. And, with CDNs like jsdelivr you can provide the major version of the package, and with will automatically serve the latest minor version of the major version which reduces the manual updates for self-hosted ones. Additionally for the fonts, they are changed quite often and you have to store them in woff2, woff, and tff to provide compatibility across all the browsers which google fonts handles for you.

**Comment by pduchnovsky** [comment]
> > > I don't think hosting everything is a good idea. Many users already have downloaded the files from a popular CDN, often the one which is included in the website of the resource provider, when visiting another site. As a result, it will be loaded from the cache when they visit our site, which leads to faster loading time. Also, most CDN's will make sure that once a user requests a file from it, it will be served from the server closest to them, which also leads to faster loading time.
> > 
> > 
> > Fair points but..
> > #1 advantage of self-hosting is that prevents any user tracking so you don't have to have privacy policy on your site.. and you can also serve from CDN (netlify cdn, cloudflare cdn, etc.)
> > #2 advantage is less overall requests in case of merged css and in case of self-hosted fonts they are served from one source and combined providing faster 'final' page load
> 
> I agree with the first one. But CDN providers like jsdelivr can provide you with merged CSS and merged JS in one request. Also, if the fonts are from google like we are using now, then they come from the same source. Also, not everyone uses a CDN to host their website. And, with CDNs like jsdelivr you can provide the major version of the package, and with will automatically serve the latest minor version of the major version which reduces the manual updates for self-hosted ones. Additionally for the fonts, they are changed quite often and you have to store them in woff2, woff, and tff to provide compatibility across all the browsers which google fonts handles for you.

That is still additional http requests and relies on availability of 3rd party cdn.. compared to merging all required css using SASS during theme build process and self-hosting fonts files/js.
My PR has only one single css file which includes normalize, forkawesome and google fonts as well, while it is easily maintained as all files are separate in theme assets/static folders and are merged during build process.

**Comment by plett** [comment]
There are no longer any performance benefits when a user visits two sites which use the same resource from a CDN.

As of Chrome 86 (and other browsers are expected to do the same soon), the browser cache is partitioned per domain for privacy reasons, so it will download the same resources from a CDN each time a new site requests it.

https://developers.google.com/web/updates/2020/10/http-cache-partitioning

**Comment by luizdepra** [comment]
> Question: Have you considered moving towards web-safe fonts ?

@pduchnovsky, never heard about that. But it looks good to have here.

**Comment by luizdepra** [comment]
I'm not sure which way to go.
We should have good gains with self-hosting, but, on the other hand, this will make this project very complex. Look at the tweemoji, which adds many files even though it is an optional dependency.
I imagined that we would have few files to keep. But this is apparently not the case.

What we can do is keep all optional dependencies on CDNs and only internalize the standard dependencies. But honestly, I am thinking of maintaining all dependencies in CDNs as we do today, and advise people who want to keep everything self-hosted to fork the project.

**Comment by luizdepra** [comment]
Another issue, not necessary related with self-hosting. I'm thinking if we should drop MathJax and just use katex instead. There is no need to keep two dependencies that do the same thing.

**Comment by pduchnovsky** [comment]
> > Question: Have you considered moving towards web-safe fonts ?
> 
> @pduchnovsky, never heard about that. But it looks good to have here.

I created PR #496 so you can check it out :)

**Comment by luizdepra** [comment]
I think we already did the best to make all mandatory dependency self-hosted. Only optional dependencies aren't, and this is ok.
