### ISSUE TITLE
[v2] Fix configurations with underline

### ISSUE THREAD

**Issue by luizdepra** [luizdepra/hugo-coder#414]
Hugo uses cameCase for its configuration names. We need to replace `custom_css` and `custom_js` with `customCSS` and `customJS`.

**Comment by Lucas-dOliveira** [comment]
I opened the PR, but I still have some questions that may or not impact on #434 
- It will be necessary to update the wiki, how can I do this update?
- I noticed that there is a variable called `custom_scss` that isn't in the camelCase format, should we convert it to camel_case on this pull request?
- Still talking about `custom_scss` this value isn't on the wiki nor on the example config.toml, is this an issue?

**Comment by clement-pannetier** [comment]
@luizdepra @Lucas-dOliveira Hi, I updated a few months back the wiki (camelCase variable format and some other changes) but didn't push the changes. Since we can't send PR on wikis, are you interested that I share my modifications ?

**Comment by luizdepra** [comment]
@Lucas-dOliveira I would appreciate if you also fix `custom_scss`. I should add it to `config.toml` if you want, it's your call.

@Lucas-dOliveira @clement-pannetier, sure. Only the project's owner can edit wiki pages. You could send me the edited content, so I can publish it. Just create a separated issue, please.

**Comment by clement-pannetier** [comment]
@luizdepra You have the wiki pages I edited here : https://github.com/clement-pannetier/hugo-coder/wiki
Just the Quick Start and Configurations pages where modified. I can update them this week-end and tell you when it's done (#206 and maybe #203).
I'm also going to send a PR to update all the configurations variable to camelCase if you are interested.

**Comment by luizdepra** [comment]
Ok, @clement-pannetier. Thank you, I'll copy the content from these pages you already fixes and wait for the next ones.

About the camelCase, @Lucas-dOliveira already changed everything. Or are you talking about fixing all `exampleSite/config.toml` to camelCase? Like `defaultcontentlanguage` to defaultContentLanguage`? If so, this is not necessary.

**Comment by clement-pannetier** [comment]
> About the camelCase, @Lucas-dOliveira already changed everything. Or are you talking about fixing all `exampleSite/config.toml` to camelCase?

@luizdepra Yes that what I was thinking, there is some new config which are still in the lowercase format like `hidecolorschemetoggle` for example. I could fix all of them if you want

**Comment by clement-pannetier** [comment]
@luizdepra It's done.

**Comment by luizdepra** [comment]
Nice, @clement-pannetier. I'm going to fix these wiki pages right now.

There no hurry to fix all the lowercased configurations. I think Hugo is clever enough to convert `hidecolorschemetoggle` to `hideColorschemeToggle` into `hidecolorschemetoggle` and vice-versa.

**Comment by luizdepra** [comment]
@clement-pannetier, could you do me a favor? Could you please copy the markdown content of every wiki page you've edited and put it in a gist? I can't see the Markdown source of your fork, so would need to check-pick your changes which is very tedious and error prone.
With the MD source I can use a diff to look for changes and also copy and paste. xD

**Comment by clement-pannetier** [comment]
@luizdepra Here it is: https://gist.github.com/clement-pannetier/2973bbdd317558a77d08135c24e94696
I added the Taiwan Chinese (zh-tw) you recently merged. **I'm not sure about the translation!!**

**Comment by luizdepra** [comment]
Nice and done!

What do you mean with "I'm not sure about the translation!"?

**Comment by clement-pannetier** [comment]
> What do you mean with "I'm not sure about the translation!"?

I'm not sure about the translation for the  Taiwan Chinese language. There are simplified and traditional Chinese in China but not sure if there is a name for this specific language.
I don't know if I'm clear 😅

**Comment by luizdepra** [comment]
Well, there is a zh-tw code, so I think there is no problem here. But, the translation per se could be completely bogus and I'm not able to tell if it is because I don't speak Chinese. hahahaha
