### ISSUE TITLE
[v2] Fix missing i18n strings

### ISSUE THREAD

**Issue by luizdepra** [luizdepra/hugo-coder#417]
There are some missing translations. We should find them, translate and add default values.

**Comment by clement-pannetier** [comment]
Recap of missing translations:
- [ ] **Arabic**: author, see_also, posts @latiif 
- [ ] **Bangali**: author @arafat-hasan 
- [ ] **Czech**: author, posts @tomkys144 
- [ ] **German**: author, see_also, posts @AltNico 
- [ ] **Spanish**: author, see_also, posts @viticlick @AltNico 
- [ ] **Finnish**: author, see_alo, posts @endormi 
- [ ] **French**: posts @clement-pannetier 
- [ ] **Hebrew**: author, see_also, posts @FIGBERT 
- [ ] **Hindi**: author, see_also, posts @iamrajiv 
- [ ] **Hugarian**: author, see_also, posts @voroskoi 
- [ ] **Italian**: author, posts @came88 
- [ ] **Japanese**: author, see_also, posts @josephting 
- [ ] **Malay**: author, posts @hussaini 
- [ ] **Dutch**: author, see_also, posts @metbril 
- [ ] **Polish**: author, see_also, posts @0rzech 
- [ ] **Brazilian Portuguese**: author, see_also, posts @luizdepra 
- [ ] **Romanian**: author, see_also, posts @sdwolfz 
- [ ] **Russian**: author, see_also, posts @PakhomovAlexander @estim 
- [ ] **Swedish**: author, see_also, posts @tobiasehlert 
- [ ] **Slovak**: author, see_also, posts @a1x42 
- [ ] **Turkish**: author, see_also, posts @tosbaha 
- [ ] **Simplified Chinese**: author, see_also, posts @PanZiwei 
- [ ] **Taiwan Chinese**: author, see_also, posts @TMineCola 

Help would be appreciated 👍.

**Comment by a1x42** [comment]
@clement-pannetier posts already exists for Slovak, I believe. Or am I missing something?

**Comment by clement-pannetier** [comment]
> @clement-pannetier posts already exists for Slovak, I believe. Or am I missing something?

@a1x42, I don't see [posts] inside the `sk.toml` file.

**Comment by a1x42** [comment]
@clement-pannetier lol, classic case of pebkac! it exists only in my fork! ;-)

**Comment by sdwolfz** [comment]
I'm confused, which entries are actually missing from the translation files? (I can submit the Romanian one no problem, just need to know what is needed)

Would it be just...
```
[posts]
other = "Articole"
```
... or are there others?

**Comment by clement-pannetier** [comment]
> I'm confused, which entries are actually missing from the translation files? (I can submit the Romanian one no problem, just need to know what is needed)
> 
> Would it be just...
> ```
> [posts]
> other = "Articole"
> ```
> ... or are there others?

Hi @sdwolfz, you also need to add see_also + author i18n translations.

**Comment by josephting** [comment]
@clement-pannetier I don't see `posts` being used anywhere. Can you explain why we need to add that?

**Comment by clement-pannetier** [comment]
> @clement-pannetier I don't see `posts` being used anywhere. Can you explain why we need to add that?
> I need to see an example of how it's being used before I can translate it properly.

@josephting, this theme uses one content type, posts. When you go to `<url>/posts` (assuming you have a posts folder inside content), there is a h1 element (Posts) that need to be translated. If we add another content type, for example "Projects", this one should be translated too, etc...

**Comment by luizdepra** [comment]
Closed by accident.

**Comment by luizdepra** [comment]
Stop closing this issue automatically, Github. xD

**Comment by luizdepra** [comment]
Guys, I just have updated the `en.toml` and `pt-br.toml` with all the missing translation. You can use them as base for other translations.

**Comment by luizdepra** [comment]
Another thing, I think that the category, tag and series translations are no working. Maybe we'll need to add the plural form translation for these words.

**Comment by clement-pannetier** [comment]
@luizdepra Also noticed that I made a typo in the wiki, I wrote "Hugarian" instead of "H**u**ngarian". Two in a row, wow 🤯.

**Comment by luizdepra** [comment]
Fixed, @clement-pannetier. xD

**Comment by josephting** [comment]
> Stop closing this issue automatically, Github. xD

lol that's why I made it like this in #455 to not trigger auto closing 😅 
> Resolves one of the item in #417

**Comment by clement-pannetier** [comment]
> Another thing, I think that the category, tag and series translations are no working. Maybe we'll need to add the plural form translation for these words.

@luizdepra, I'm working on that. Do you want to open a new issue ? If you remember, I started to do it when I worked on the projects archetype here #323.

**Comment by luizdepra** [comment]
@clement-pannetier I think we could make the fix based on all the already translated texts and ask for people's review. But, sure, I should create another issue.

**Comment by tobiasehlert** [comment]
@clement-pannetier, I've added the Swedish translation in #551. If there is something more missing, please let me know.

Looks also like the German translation (done in #598) and Malay (done in #641) can be ticket off :)

**Comment by luizdepra** [comment]
There are still some missing translation. I'm going to open another issue to address.
