### ISSUE TITLE
[v2] Floating Color Scheme Toggle

### ISSUE THREAD

**Issue by luizdepra** [luizdepra/hugo-coder#418]
Move the toggle icon to be always floating in the bottom-left corner of the screen. Something like [this site](https://fasterthanli.me/articles/so-you-want-to-live-reload-rust) has.

**Comment by JianLoong** [comment]
Sorry for the spam. Didn't notice there were other things to be done until I took a look at the PR template. The Netlify preview seems fine. The only thing that bothers me is the size of the toggle button itself.
