### ISSUE TITLE
Allow for nested menu options

### ISSUE THREAD

**Issue by tydel** [luizdepra/hugo-coder#425]
I would really like it if we were able to use nested/multi-level menu options in the menu.

This would be achieved by using "parent" in the menu configuration in the config.toml.

I found [this](https://gohugo.io/content-management/menus/#nesting) as a reference, however found that the theme didn't support this :( 

I would appreciate your consideration!  Thank you.

**Comment by luizdepra** [comment]
This feature isn't on my roadmap, but it if simple and possible to do. I could try to add it to the plan, but if anybody is interested in this feature, you're welcome to do it.

**Comment by luizdepra** [comment]
Just added this feature request into the roadmap.
