### ISSUE TITLE
Disqus alternatives?

### ISSUE THREAD

**Issue by sgtrusty** [luizdepra/hugo-coder#428]
Preferably non-tracking, non-bloatware, privacy affecting tools, like in this list: https://lisakov.com/projects/open-source-comments/
![image](https://user-images.githubusercontent.com/48886164/95021783-7ded1200-0649-11eb-81a7-9c567c470c24.png)
![image](https://user-images.githubusercontent.com/48886164/95021784-80e80280-0649-11eb-850d-a8a1e4983cc7.png)

**Comment by nekr0z** [comment]
The only non-tracking, privacy-respecting and lock-in free way of commenting on contemporary Web is by using [webmentions](https://indieweb.org/Webmention), everything else is a some sort of a compromise one way or the other. Disqus is not the worst out there.

**Comment by luizdepra** [comment]
We already integrates with Commento and Utterances. (I think these are the most known ones.)

I just met WebMentions, so I need to learn more about it. But it seems interesting to have it added to this theme.

**Comment by nekr0z** [comment]
> But it seems interesting to have it added to this theme.

Receiving can easily be implemented with minimal additions to templates by leveraging a third party-service like [webmention.io](https://webmention.io/) and [client-side rendering](https://github.com/PlaidWeb/webmention.js/). Sending is another story, and there's hardly a one-size-fits-all solution for static websites. I [ended up](https://evgenykuznetsov.org/en/posts/2020/un-known/#what-about-webmentions) writing my own tool for that.
