### ISSUE TITLE
SASS/SCSS resources not found in the file cache

### ISSUE THREAD

**Issue by jrwaine** [luizdepra/hugo-coder#429]
Hi,

I downloaded the module in Windows and when running `hugo serve`, it printed this error
```bash
ERROR 2020/10/05 02:21:39 TOCSS: failed to transform "style.coder-dark.css" (text/x-scss): resource "scss/scss/coder-dark.scss_9e20ccd2d8034c8e0fd83b11fb6e2bd5" not found in file cache
Built in 75 ms
Error: Error building site: TOCSS: failed to transform "style.coder.css" (text/x-scss): resource "scss/scss/coder.scss_fd4b5b3f9a48bc0c7f005d2f7a4cc30f" 
not found in file cache
```

I believe that the error is related to [this other one](https://github.com/gohugoio/hugoThemes/issues/822), but I'm new to Hugo and Go, so I don't know how to fix it.

I was able to stop the error by downgrading Hugo to version 0.65.3.

**Comment by luizdepra** [comment]
Probably there is problem with some new minimal versions of Hugo. This is not related with the theme itself.
Well, you can try to use Hugo's extended binaries too.

**Comment by jrwaine** [comment]
I believe that with the extended binaries the problem is solved. Thanks!
