### ISSUE TITLE
How do you use Fathom Analytics?

### ISSUE THREAD

**Issue by garyrob** [luizdepra/hugo-coder#436]
Issue 264 covers adding Fathom Analytics support. But I'm not clear on how to use it. The issue mentions adding this to confit.toml:

```
[params.fathomAnalytics]
    siteID = "ABCDE"
    rootURL = "analytics.example.com"
```

But that code snippet is marked as Outdated. And I can't find anything in the documentation about it. The issue mentions renaming rootURL to "serverURL or something like that", but I don't know what was actually done. Also, if I'm using hosted Fathom, would it point to app.usefathom.com which is the panel analytics are displayed on, or would it point to something else?

**Comment by luizdepra** [comment]
I never used Fathom, so maybe I won't help much here.

You should use [`exampleSite/config.toml`](https://github.com/luizdepra/hugo-coder/blob/master/exampleSite/config.toml#L63-L67) as example.
As far as remember, we already changed `rootURL` to `serverURL` and it should work fine.
About the `serverURL` content, you can remove it from your configuration and it will use the default one. In my opinion, `serverURL` is as misleading configuration name. It is not to configure to where your data is sent, but to configure where the `tracker.js` file is hosted.
