### ISSUE TITLE
Collapsible menu?

### ISSUE THREAD

**Issue by chipsenkbeil** [luizdepra/hugo-coder#44]
The combination of my name's length and an additional menu item makes the top menu wrap around to the next line. Has there been any thought towards a collapsible menu? Or some other design that wouldn't wrap around? Or is this the preferred way to handle length like that?

![36501997_185085205502761_2999050975601229824_n](https://user-images.githubusercontent.com/2481802/42172755-87effc6e-7de2-11e8-852d-9ef00e8e3198.jpg)

**Comment by luizdepra** [comment]
A collapsible menu is a really nice idea.
I did not add it yet but I was looking for an option that don't use JS (if possible).
Could you help me this feature?

**Comment by chipsenkbeil** [comment]
@luizdepra, I've used some HTML5 elements that enable collapsing on https://scala-debugger.org/api/getting-started/what-is-a-debugger/

Details and summary are the related tags to do this.

A simple example of this can be found on MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**Comment by chipsenkbeil** [comment]
Another thought (maybe additional) is to collapse the name on the lefthand side. Given that it represents going to the homepage, maybe converting it to __~__ (equivalent of home for programmers) on small screens would be an option.

**Comment by khos2ow** [comment]
I like the idea of using `~` but it won't solve the problem for all situations. What if one has more than three items in the menu, what if the items' text are long and etc. The one fix for all will definitely be the collapsible menu (such as the one bootstrap does with its hamburger menu)

This is the way I've done it (lazy enough!) with Bootstrap.
![selection_053](https://user-images.githubusercontent.com/372575/42230452-0c64c4dc-7eb7-11e8-83c3-2384f2d37081.jpg)

**Comment by luizdepra** [comment]
Yeah. I'll try to add a collapsible menu later. But for now, I'll use the `~` idea.

**Comment by luizdepra** [comment]
Now we have a collapsible menu for mobile screens. So, I'm closing this issues.
