### ISSUE TITLE
custom css no longer sourced!?

### ISSUE THREAD

**Issue by a1x42** [luizdepra/hugo-coder#443]
Is it possible, that the latest changes linked to light/dark mode broke the option of custom_css? Mine seems no longer read after getting the latest changes just now.

**Comment by clement-pannetier** [comment]
@a1x42 Maybe it's because this property has been renamed here #434 from `custom_css` to customCSS` ?

**Comment by a1x42** [comment]
@clement-pannetier many thanks for the quick reply. I think you are right, I certainly still had the underscore in my config. Will retry tomorrow. I thought I checked the samplesite config to check for new options but didn’t notice the new spelling. Not sure how to do it. but it could be useful if hugo offered a way for themes to sanity check configs i. e. alert about unsupported parameters and inform about default values for parameters which aren’t specified. But I guess this can’t be implemented on theme level only.

**Comment by a1x42** [comment]
@clement-pannetier worked like a charm. Thanks again for your help. :)
