### ISSUE TITLE
Icons are not rendering properly

### ISSUE THREAD

**Issue by iamrajiv** [luizdepra/hugo-coder#445]
After running `hugo serve` getting this
<img width="533" alt="Screenshot 2020-10-19 at 4 18 58 PM" src="https://user-images.githubusercontent.com/42106787/96441211-cc440880-1226-11eb-877b-929f070814dc.png">

but it should look like this
<img width="533" alt="Screenshot 2020-10-19 at 4 24 52 PM" src="https://user-images.githubusercontent.com/42106787/96441734-9fdcbc00-1227-11eb-8c55-fd896d01bad8.png">

**Comment by clement-pannetier** [comment]
Hi @iamrajiv, if you've updated the theme, you have to change the icons in your `config.toml` file.
This theme no longer use fontawesome but is using forkawesome.

**Comment by iamrajiv** [comment]
Thank You @clement-pannetier I got my issue solved.
