### ISSUE TITLE
custom(S)CSS[] config variable doesn't seem to work as expected

### ISSUE THREAD

**Issue by esperlu** [luizdepra/hugo-coder#448]
I have created a `assets/css/custom.css` at the site root and set the config variable `customCSS = ["assets/css/custom.css"]`

That file does not seem to be taken into account. The ` <link rel="stylesheet" href="/assets/css/custom.css" />` show in the web page sources though, but returns a 404 when I try to access it from the browser.

Other issue with the `customSCSS` list : whatever value I put in there, I get multiple Hugo errors like this one :
`ERROR 2020/10/21 19:56:03 failed to render pages: render of "taxonomy" failed: "/home/jeanluc/hugo-sites/appart-21302/themes/hugo-coder/layouts/_default/baseof.html:68:40": execute of template failed: template: _default/list.html:68:40: executing "_default/list.html" at <toCSS $cssOpts>: error calling toCSS: no Resource provided in transformation`

The corresponding line in baseof.html : `{{ $styles := resources.Get . | toCSS $cssOpts }}`

**Comment by a1x42** [comment]
the file needs to be relative to the static folder, not in the theme.

**Comment by luizdepra** [comment]
If I remember well, you need to put your SCSS file inside the `resources` folder.

I see that these customXXX options are causing lots of problems and confusions. They're also making the template code very messy.
I'm thinking that I should drop these features. It looks better to guide people into forking the theme to making their changes.

**Comment by esperlu** [comment]
> the file needs to be relative to the static folder, not in the theme.

That was it. Thanks. The customSCSS also doesn't throw any errors anymore when defined as relative to the static folder.

> If I remember well, you need to put your SCSS file inside the `resources` folder.
> 
> I see that these customXXX options are causing lots of problems and confusions. They're also making the template code very messy.
> I'm thinking that I should drop these features. It looks better to guide people into forking the theme to making their changes.

I am not sure that will be easier, I have worked with other themes that allow the use of custom css on top of the theme's css. I find it easier that messing around on the main css file. At least we can keep that main css untouched and customise it with a separate file JM2C.

Thank you for your help. Nice theme.

**Comment by luizdepra** [comment]
No problem. You are welcome.
