### ISSUE TITLE
customSCSS wouldn't re-compile when changed

### ISSUE THREAD

**Issue by gwd0715** [luizdepra/hugo-coder#458]
Hugo version: Hugo Static Site Generator v0.76.5/extended darwin/amd64.

Config.toml settings as follows:
`assetDir = "static"`
`customSCSS = ["scss/custom.scss"]`
custom.scss is under `/hugo-site/static/scss/custom.scss `

The SCSS will compile when I start the server or a hard hugo restart server through Command Line. However if I change any SCSS while watching or hugo server, Hugo doesn’t recompile the SCSS, even after forced browser refresh and hard refresh, even though it sees a change in the file.

**Comment by luizdepra** [comment]
I think `hugo server` does not make a full reload when you change something inside the `static` folder.

I guess this is not a bug, but I recommend you to ask about it in the [Hugo's Discourse](https://discourse.gohugo.io/) for a proper answer.

**Comment by gwd0715** [comment]
Thank you.

**Comment by gwd0715** [comment]
@luizdepra 
Do you have the same issue on your computer?
Just wanna know whether this problem is related to my dev environment.

**Comment by luizdepra** [comment]
The watch and reload feature is working fine here, but I think I found your problem.
Try creating your file under `assets/scss` instead of `static/scss`.

**Comment by gwd0715** [comment]
You mean `assets/scss`  under `/<root>` or under `/<root>/themes/hugo-coder`
And do I need to change  settings in config.toml file or just leave it as follows:
`assetDir="static"`
`customSCSS=["scss/custom.scss"]`
Thank you.

**Comment by clement-pannetier** [comment]
Hi @gwd0715, place it under root and remove the `assetDir` config.

**Comment by gwd0715** [comment]
@clement-pannetier 
Thank you! 
Problem founded: 
Just put hugo pipe resources under `/asset`, and **DO NOT** change the default value of assetDir even though the Docs of Hugo suggests you can. This can cause live reload issue!!!

<img width="564" alt="Screen Shot 2020-11-05 at 5 26 40 PM" src="https://user-images.githubusercontent.com/17922721/98222659-14378f00-1f8c-11eb-92bc-28aa6b379a39.png">
