### ISSUE TITLE
[Request] Pages and components 

### ISSUE THREAD

**Issue by NicoCG** [luizdepra/hugo-coder#46]
Hi @luizdepra,

### PAGES
Could you kindly add the following authentication pages like Login, Register and forget password or even just login and I will tweak the rest of the pages.

### Component
Could please add a tables example component for this theme. I really could use a clean, hack looking table.

**Comment by rdhox** [comment]
I don't want to talk for @luizdepra here, but I don't think these requests match the description of "very minimalist developer blog theme" ;)

**Comment by mbollemeijer** [comment]
This would even be useless without server side authentication, these kind of things are not suited for Hugo, maybe you should consider wordpress.

**Comment by luizdepra** [comment]
I agree with @rdhox and @mbollemeijer.
Are you looking for a CMS? Maybe https://forestry.io?

**Comment by NicoCG** [comment]
@luizdepra No I am building my own blog which is why I need authentication pages so I can style the login.

**Comment by luizdepra** [comment]
@NicoCG, I think we aren't at the same page here. Are you using Hugo to build your blog?
This theme was built to be used with Hugo and Hugo only.

**Comment by NicoCG** [comment]
@luizdepra Don't worry I have figured I had other idea for this theme merging it into another provider but I found another theme similar to this with what I need thank you.
