### ISSUE TITLE
help me.

### ISSUE THREAD

**Issue by zenochien** [luizdepra/hugo-coder#468]
how do thing?
[
![Capture](https://user-images.githubusercontent.com/48956792/97596519-61b97680-1a37-11eb-90c8-60f5bc1202da.PNG)
](url)

**Comment by luizdepra** [comment]
Hello, @zenochien.

You need to configure `baseurl` inside your `config.toml` to reflect your website URL.
Setting it to `https://github.com/zenochien/blogcanhan.github.io/`  should work, I guess.
