### ISSUE TITLE
Thank You :)

### ISSUE THREAD

**Issue by Mike-EEE** [luizdepra/hugo-coder#47]
Hey there,

I wanted to send a shout of my sincerest gratitude for your great work here.  I used it for a personal art site that I put together and thought I would make sure you knew about it.  As soon as I saw your design I was inspired to put my art together to see how it looked on it, and I was not disappointed. 😄 

Here is the site:
http://www.ossem.com/

Much respect and appreciation!
Michael

**Comment by Mike-EEE** [comment]
Going to close this now as this is not an issue, just wanted to share.

**Comment by luizdepra** [comment]
Thank you for the compliment.
I still can't understand why my poorly designed theme pleases you, guys. :laughing:

**Comment by Mike-EEE** [comment]
OMG hahaha... now THAT was a laugh I needed!  Haha... if your design is "poorly" implemented then PLEASE BY ALL MEANS CONTINUE!!! 😆 🎉
