### ISSUE TITLE
failed to transform issue

### ISSUE THREAD

**Issue by Ronen-Sigan** [luizdepra/hugo-coder#475]
Hi,
Can you please look at this log from the terminal. I made no changes to configuration and using toml from example site.
Thanks

hugo server
Start building sites … 
ERROR 2020/11/03 19:14:43 TOCSS: failed to transform "style.coder-dark.css" (text/x-scss): resource "scss/scss/coder-dark.scss_9e20ccd2d8034c8e0fd83b11fb6e2bd5" not found in file cacheBuilt in 164 ms
Error: Error building site: TOCSS: failed to transform "style.coder.css" (text/x-scss): resource "scss/scss/coder.scss_fd4b5b3f9a48bc0c7f005d2f7a4cc30f" not found in file cache        
PS C:\Users\ronen\Documents\muse>

**Comment by clement-pannetier** [comment]
@Ronen-Sigan Hi, using the hugo-extended version should fix your issue.

**Comment by Ronen-Sigan** [comment]
@clement-pannetier Solved it. Many thanks 👍
