### ISSUE TITLE
rtl=true for just one language

### ISSUE THREAD

**Issue by Ronen-Sigan** [luizdepra/hugo-coder#478]
Hi,
My site is in English and Hebrew, and if I set rtl=true in the config.toml then both languages are displayed in rtl. If I enter rtl=false in the [params] section and rtl=true only in the [languages.he.params] section of the toml file, then all pages are displayed ltr. 
How can I define an rtl=true setting only for the Hebrew language pages? 

Thanks
``

**Comment by pduchnovsky** [comment]
Have you tried this:
    [languages.he]
         rtl = true
?

**Comment by Ronen-Sigan** [comment]
It only affects the Hebrew home page, but the Hebrew 'blog' and 'about' pages remain aligned to the left.

**Comment by pduchnovsky** [comment]
> It only affects the Hebrew home page, but the Hebrew 'blog' and 'about' pages remain aligned to the left.

Hmm, I tested this and with options above, everything is aligned to the right for specific language
![image](https://user-images.githubusercontent.com/54581833/98797923-8802ed00-240d-11eb-865b-7da67a7e1046.png)

**Comment by Ronen-Sigan** [comment]
But are your English pages aligned properly?

Can you please look at my TOML file (I changed it to a config.toml.txt file to enable the upload)?
[config.toml.txt](https://github.com/luizdepra/hugo-coder/files/5523710/config.toml.txt)

Thanks


``

**Comment by pduchnovsky** [comment]
Copied your config to mine and started hugo server, copied one english article and added .he.md at the end
It works fine:

![Wrrr6tMLMZ](https://user-images.githubusercontent.com/54581833/98808404-58a7ac80-241c-11eb-969f-bf6526598522.gif)

Maybe I changed something in my fork, you might try to download it: https://github.com/pduchnovsky/hugo-coder.git
I already created PR to this repo.

**Comment by Ronen-Sigan** [comment]
I've uploaded the entire site with the forked theme you indicated so you can examine it. 
Please go to https://cocky-shirley-a7b657.netlify.app/he/about/my-first-post/
As you can see, the alignment in this page is ltr.

Please click on other pages to notice the problem throughout the site excluding the main page in English and Hebrew.
Note that the many of site's Hebrew pages have not been translated yet.

Thanks

**Comment by pduchnovsky** [comment]
Something weird is going on because when I click to about/blog on HE homepage, it switches back to english.

What's your directory/file structure ? Can you do `tree . -L 3 -I resources` and post results ?
This is mine, as you can see, about-me is split between english (no lang defined in filename) and slovak (lang defined in filename), non-translated blog posts won't even show whatsoever, I'd get 404 if I were to click on 'blog' link and weren't using netlify and url rewrite.

Could be that you don't even have anything really translated to HE yet ? Because if it is not translated and it does not have files with .he. in names, it won't work

```
pduchnovsky@pd-pc:~/repos/pd-web$ tree . -L 3 -I resources
.
├── README.md
├── config.toml
├── content
│   ├── about-me.md
│   ├── about-me.sk.md
│   ├── images
│   │   ├── ...
│   ├── portfolio.md
│   ├── portfolio.sk.md
│   └── posts
│       ├── ...
├── netlify.toml
├── optimg.flag
├── optimize_img.sh
├── static
│   └── images
│       ├── ...
└── themes
    └── hugo-coder

9 directories, 35 files
```

**Comment by Ronen-Sigan** [comment]
Please examine the files and structure here: https://bitbucket.org/RonenSigan/muse/src/master/
Note that the page https://cocky-shirley-a7b657.netlify.app/he/about/my-first-post/ is not aligned properly as you can see in the screenshot I've attached.
<img width="804" alt="wrong-alignment" src="https://user-images.githubusercontent.com/32033755/98841781-4300aa00-2451-11eb-8eaf-8582ad7156c0.png">

**Comment by pduchnovsky** [comment]
Since you are using "**translation by directory**"
Can you set it up as mentioned here ?
https://gohugo.io/content-management/multilingual/#translation-by-content-directory
I think you are missing contentDir definition.

**Comment by Ronen-Sigan** [comment]
Yes! That was it! Works fine now. Excellent!
Thank you!!
