### ISSUE TITLE
Any plan to integrate Google Analytics (GA4)?

### ISSUE THREAD

**Issue by kdpuvvadi** [luizdepra/hugo-coder#480]
just wondering is there any plan or timeline to integrate new GA4?

**Comment by luizdepra** [comment]
I don't know if Hugo will support GA4, or when it will happen.
There an issue about it [here](https://github.com/gohugoio/hugo/issues/7954).

I think we shouldn't add this integration into `hugo-coder`, but we should contribute to `hugo` instead.

**Comment by kdpuvvadi** [comment]
I do agree with that.
