### ISSUE TITLE
Stackbit build failed

### ISSUE THREAD

**Issue by pduchnovsky** [luizdepra/hugo-coder#483]
I'm playing with stackbit and can't get it working with this theme, anybody has any idea why ?

@JugglerX 

# Setup:

![image](https://user-images.githubusercontent.com/54581833/99060693-af3df380-25a0-11eb-90b9-bd837fe5c489.png)
^ here I use my fork but I also tried using main repo and it's the same problem

# Outcome:

![image](https://user-images.githubusercontent.com/54581833/99059662-2a060f00-259f-11eb-8b0c-def5ab5fae58.png)

I mean, **it builds the page in the background** which is working after all, but you cannot edit anything in stackbit, it's stuck in this phase in studio:
![image](https://user-images.githubusercontent.com/54581833/99059367-c7147800-259e-11eb-8437-b39dae824440.png)

**Comment by JugglerX** [comment]
@pduchnovsky I'll take a look and do a PR to fix the issue. 

Stackbit has been making some big updates to custom themes and this theme still uses stackbit v2.

**Comment by pduchnovsky** [comment]
@JugglerX 
Small update, after above mentioned commit, it at least loads the page, but still fails to load setup:
![image](https://user-images.githubusercontent.com/54581833/105578114-3fa56b00-5d7e-11eb-82b8-5d70b26b5361.png)

**Comment by luizdepra** [comment]
We removed Stackbit because no one was able to maintain it.
