### ISSUE TITLE
About the List Page

### ISSUE THREAD

**Issue by nakiamo** [luizdepra/hugo-coder#490]
I'm a newbie and I couldn't figure out what I'm doing wrong that's why I'm looking for your help.
I created a list page called "Lectures" to list the single pages of my courses. I have two issues I could not solve:
I added an _index.md file to include an introduction text on the list page. But the content is shown in columns that are aligned to right. 
Secondly, I wonder if I can remove the date info of the listed single pages.

[https://www.naimcinar.com/lectures/](url)
https://github.com/nakiamo/hugo_site.git

**Comment by luizdepra** [comment]
Probably you'll need to create new archetype templates for `lectures` or your content will be rendered as a normal page.
Posts are a special archetype in this theme, you can use it as an example. But, I recommend you to take a look at Hugo's Documentation about list and single templates, and archetypes too.

**Comment by nakiamo** [comment]
Thanks for the suggestion and for this great theme!
