### ISSUE TITLE
modify footer font family to match header? 

### ISSUE THREAD

**Issue by bfallik** [luizdepra/hugo-coder#493]
Hi,

Thanks for your work on this theme!

After applying coder to my site one little nit that struck me as odd was that the font family of the footer didn't match the header. I'm not a font expert but I believe the header uses sans-serif and the body uses serif. To my eyes it looks weird for the footer to also use serif.

I'm also not a CSS expert but I was able to produce the behavior I wanted with this one-liner:

```
diff --git a/assets/scss/_footer.scss b/assets/scss/_footer.scss
index 286c393..623efa0 100644
--- a/assets/scss/_footer.scss
+++ b/assets/scss/_footer.scss
@@ -1,6 +1,7 @@
 .footer {
   width: 100%;
   text-align: center;
+  font-family: $heading-font-family;
   line-height: 2.0rem;
   margin-bottom:1.0rem;
   a {
```

Of course this may just be my taste preference but I wanted to ask if you'd accept a PR that contains this patch?

Thanks in advance.

**Comment by luizdepra** [comment]
Let me see how this looks. But it should be fine.
Also, I need to mention that I'm thinking of changing the fonts to both sans-serifs, not the same, of course.

**Comment by bfallik** [comment]
hi @luizdepra . Was wondering if you had any feedback on my PR for this issue, #498.

**Comment by luizdepra** [comment]
Done. :)
