### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [luizdepra/hugo-coder#5]
Hello yet again:)

I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19, only part of the image visible on the screenshot where whole should be:

![image](https://user-images.githubusercontent.com/712534/37847104-b872ecee-2ee0-11e8-865c-2faa971abd31.png)

Source code:

    ![Icinga 2 web interface](https://www.icinga.org/wp-content/uploads/2015/10/Screen-Shot-2015-10-02-at-00.11.09.png)]

**Comment by luizdepra** [comment]
Done in d3e619ecf9d451c7b6574a53d13555ac2faffdd5. :)

**Comment by paskal** [comment]
I'm not sure github sent notifications to mentioned authors, so posting double there: theme highlight is out, this very theme is in it, additional info on https://github.com/paskal/terrty/issues/1.
