### ISSUE TITLE
google analytics

### ISSUE THREAD

**Issue by dalenoe** [luizdepra/hugo-coder#50]
Is it possible to add google analytics to this theme?

I apologize for the silly question, but I am also new to hugo itself. Thanks..

**Comment by khos2ow** [comment]
It's already supported, you only need to add the following to your `config.toml` outside of `[params]`:

```
googleAnalytics = "UA-xxxxxxxxx-1"

...

[params]
  ...
```

**Comment by dalenoe** [comment]
thanks @khos2ow

**Comment by luizdepra** [comment]
@dalenoe no it doesn't. But what is the use case of it?

**Comment by khos2ow** [comment]
I guess it would be useful for a open source, collaboration based website, which the content can be updated through individual PRs.

I personally haven't needed it. @luizdepra may be we can add this in v2 if time allows and other higher priority items were done?

**Comment by luizdepra** [comment]
@khos2ow, ok. We can add it.

@dalenoe, could you please create and feature request (issue) with some examples?

**Comment by dalenoe** [comment]
Sure thing. For the record, I can possibly contribute. I almost have it working on my personal site.
