### ISSUE TITLE
Last line in post is not left justified

### ISSUE THREAD

**Issue by Ronen-Sigan** [luizdepra/hugo-coder#503]
The last line in the post contains spaces, and I am not sure which css needs to be modified in order to adjust text to the left. Please see screenshot for example.

Thanks
<img width="688" alt="2021-01-01 18_45_10-s" src="https://user-images.githubusercontent.com/32033755/103442727-92997000-4c61-11eb-8687-4339d5a6d897.png">

**Comment by Ronen-Sigan** [comment]
Fixed by adding spaces.

**Comment by luizdepra** [comment]
You could change `text-align` to `left`. I use `justify`, I guess.

**Comment by Ronen-Sigan** [comment]
Should I edit '_content_rtl.scss'?

**Comment by luizdepra** [comment]
Sure. If you want something different, this is the way to do it.
But, maybe you are looking for `_content.scss`. `_rtl` files are related with the `rtl` feature, which is used to change text direction to right-to-left. Normally, only user that write in languages like Arabic will need this feature.
