### ISSUE TITLE
Support for Code Copy-to-Clipboard Button

### ISSUE THREAD

**Issue by b-reich** [luizdepra/hugo-coder#510]
Hi, 

a Button for "copy to Clipboard" für code blocks would be great.
Example: https://aaronluna.dev/blog/add-copy-button-to-code-blocks-hugo-chroma/

**Comment by luizdepra** [comment]
Hmm. It is feasible.

There are other things in the row on my roadmap, but if someone is interest, feel free to contribute.

**Comment by luizdepra** [comment]
I'm going to add this feature request as part of #55.
