### ISSUE TITLE
A lot of spacing between heading tags

### ISSUE THREAD

**Issue by iamrajiv** [luizdepra/hugo-coder#511]
![Screenshot 2021-01-19 at 6 38 31 AM](https://user-images.githubusercontent.com/42106787/104975552-f4f3be00-5a20-11eb-8dbf-f6d032ae643b.jpg)

**Comment by pduchnovsky** [comment]
This is reduced in PR #496

**Comment by luizdepra** [comment]
This margin size is intended. Articles normally shouldn't have sequentially placed heading with any text in between. So, the margin gives a comfortable spacing between the heading and the following paragraph.

**Comment by luizdepra** [comment]
Also, you can always use a custom CSS or change our SCSS files to adjust these values.
