### ISSUE TITLE
[Wiki] colorScheme param typo in configuration example

### ISSUE THREAD

**Issue by AnatomicJC** [luizdepra/hugo-coder#512]
Hi !

There is a typo for the colorScheme param in the wiki here: https://github.com/luizdepra/hugo-coder/wiki/Configurations#complete-example

It is written
```
colorsheme = "auto"
```

instead of 

```
colorScheme = "auto"
```

**Comment by luizdepra** [comment]
Just fixed it. Thank you. :)
