### ISSUE TITLE
Does it support post summaries?

### ISSUE THREAD

**Issue by Trumeet** [luizdepra/hugo-coder#517]
I'm trying this theme for my new Hugo blog, but I find my `summary` front matter setting does not work using this theme. Summaries are important for my blog, does the theme support that? Thanks.

**Comment by luizdepra** [comment]
Do you want to have summaries in the post lists, right? Well, the answer is no. But, it is easy to add it.
You should change [the `li` file for post](https://github.com/luizdepra/hugo-coder/blob/master/layouts/posts/li.html) and add `{{ .Summary }}` variable. You may need to change or add some (S)CSS rules too.

I remember seeing this feature in one of the forks many forks of this project. Maybe you could use one of them as a base.

**Comment by Trumeet** [comment]
> Do you want to have summaries in the post lists, right? Well, the answer is no. But, it is easy to add it.
> You should change [the `li` file for post](https://github.com/luizdepra/hugo-coder/blob/master/layouts/posts/li.html) and add `{{ .Summary }}` variable. You may need to change or add some (S)CSS rules too.
> 
> I remember seeing this feature in one of the forks many forks of this project. Maybe you could use one of them as a base.

Thanks. Are there any plans to add this feature?

**Comment by luizdepra** [comment]
> Thanks. Are there any plans to add this feature?

No. I prefer to keep the list simple as it is now. I think it fits better with the theme style,

**Comment by Trumeet** [comment]
> > Thanks. Are there any plans to add this feature?
> 
> No. I prefer to keep the list simple as it is now. I think it fits better with the theme style,

Thank you. I will try some forks or modify the list a little bit to accomplish that.
