### ISSUE TITLE
Failed to use Katex

### ISSUE THREAD

**Issue by ckjzsa** [luizdepra/hugo-coder#519]
I wanna use Katex in the blogs, and I tried to add either **katex=true** or **math=true** in the config.toml file. However, the latex syntax still cannot display correctly. I wonder if anyone has idea about it?

**Comment by luizdepra** [comment]
Both Katex and MathJax will work only on `post` content.

BTW, you could enable these features for one or another posts by adding the desired configuration into the content front matter.
