### ISSUE TITLE
how to build locally

### ISSUE THREAD

**Issue by vuillaut** [luizdepra/hugo-coder#524]
I have seen all the issues with the `baseurl` wrongly set.
But how do you build a working version of this theme locally, using only `hugo` and not `hugo server` to have the website properly built in `/public`.
The css is not applied and the links between the pages are broken.

Thanks

**Comment by luizdepra** [comment]
Try adding `relativeURLs = true` into your `config.toml`.
For more information see [the official documentation](https://gohugo.io/getting-started/configuration/).
