### ISSUE TITLE
window title for posts menu entry

### ISSUE THREAD

**Issue by a1x42** [luizdepra/hugo-coder#529]
Since #70 we have localisation of the posts title, which is great. But I found a little problem with it. Since this change the window title when clicking on the posts link in the menu does not show the title of the menu entry but instead shows the localised version of posts instead. I called my menu entry Blog, but the window title shows Posts, rather than the name entry of my localised menu entry. With below config, the story entry shows "Môj príbeh" in the window title but for posts I get "Posts"

            [[languages.sk.menu.main]]
                name = "Môj príbeh"
                weight = 4.0
                url = "story"

            [[languages.sk.menu.main]]
                name = "Blog"
                weight = 5.0
                url = "posts"

Am I holding it wrong?

**Comment by a1x42** [comment]
After posting, I did another test and realised that the title is taken from the actual content file, which does not exist for the posts, so probably the only workaround would be to change the translation for posts in my i18n files to my liking in my own branch. Any other ideas?

**Comment by luizdepra** [comment]
You are right, your post list page will be named `Posts` whatever your name  the menu item.

I think making a copy of the translation file inside your site root folder will work too. There is no need to fork the theme and edit its files directly, I guess.

**Comment by a1x42** [comment]
Thanks for the quick confirmation. Too late for not forking! But even though I made quite a few adaptations especially on the posts https://erz.lu/posts/, I still manage to merge in changes from the main branch! ;)
