### ISSUE TITLE
Can leave a comment on About page？

### ISSUE THREAD

**Issue by vitahlin** [luizdepra/hugo-coder#530]

**Comment by luizdepra** [comment]
Could you elaborate on exactly what kind of comment you want to add? Any example?

**Comment by vitahlin** [comment]
Like post, it can use utteranc to leave comment:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/6998610/111327068-074c4a00-86a8-11eb-8ca6-059c5ee67448.png">

**Comment by luizdepra** [comment]
Ohh, I see. Yes, you can but you need to modify one file: [`layouts/partials/page.html`](https://github.com/luizdepra/hugo-coder/blob/master/layouts/partials/page.html). You could just copy the footer section from [posts](https://github.com/luizdepra/hugo-coder/blob/master/layouts/posts/single.html#L42-L47) and add it into the `page.html` file.

**Comment by vitahlin** [comment]
Got it. I hope it would become a configuration option then I can decide what pages can leave comments.
Thanks a lot.
