### ISSUE TITLE
Taxonomies problem

### ISSUE THREAD

**Issue by jorgesolatre** [luizdepra/hugo-coder#531]
![Screenshot_2021-03-18-16-51-00-15.jpg](https://user-images.githubusercontent.com/77653940/111707706-2b27a100-880a-11eb-8dff-6045d1e2dbc9.jpg)![Screenshot_2021-03-18-16-50-50-89.jpg](https://user-images.githubusercontent.com/77653940/111707709-2ebb2800-880a-11eb-8f18-af972275a77e.jpg)

What Am I doing wrong? My tags are not displayed at website

**Comment by jorgesolatre** [comment]
If you change the url of blogs, the tags are not going show up 
The original is "posts" 
I was using blogs so that's the reason, I still don't know how to fix the same situation with the projects page.

**Comment by pasindujr** [comment]
I did the same and got the same issue. Have you find a solution @jorgesolatre?

**Comment by jorgesolatre** [comment]
> I did the same and got the same issue. Have you find a solution @jorgesolatre?

Yes, with this I found the solution.
Go to the config toml to change the url of your "blog" 
In the blog page I was using the url "blogs" and the tags were not working.
In the original theme the blog page is using the url of "posts" so you have to use it too instead of any other and that's it.

![Screenshot_2021-04-04-08-42-48-53.jpg](https://user-images.githubusercontent.com/77653940/113512418-cbc3d380-9521-11eb-9694-aca81250fd5d.jpg)

**Comment by pasindujr** [comment]
Got it @jorgesolatre. Thanks! I renamed the "posts" file to "blog" and made a copy of it and renamed it to "projects" in the theme folder. Now it works.

**Comment by luizdepra** [comment]
I recommend you guys to read about Hugo's archetypes. Post is an archetype and some kind of content are only shown if you use it properly.

There is an alternative to change your posts URL without needing to change the theme. See discussion in #186.
