### ISSUE TITLE
integrity attribute ignored

### ISSUE THREAD

**Issue by lazyyz** [luizdepra/hugo-coder#535]
#520  After add forkawesome-webfont.woff2 intergrity attributes, Chrome console show this warning:

(index):21 : < link rel="preload" href="/fonts/forkawesome-webfont.woff2?v=1.1.7" as="font" type="font/woff2" integrity="sha256-hEIt6X6xzye8ubyk8/uxjz68cRZHsJxoKS9fQ8idUGQ=" crossorigin / >

The integrity attribute is currently ignored for preload destinations that do not support subresource integrity. See https://crbug.com/981419 for more information

How to fix it? Thanks!

**Comment by luizdepra** [comment]
Is this problem happening when hosting the project somewhere? (GH Pages, Netlify or something else.)
Or do it only appears when testing with `hugo server`?

**Comment by 0rzech** [comment]
This happens because, AFAIK, the standard does not support integrity for non-css and non-script targets yet. The only way to get rid of it is to remove for now integrity attribute for preloaded font.

**Comment by luizdepra** [comment]
Just tested with Chrome and the problem is really there. With Firefox everything is normal.
