### ISSUE TITLE
[v2] Inverted Color style

### ISSUE THREAD

**Issue by luizdepra** [luizdepra/hugo-coder#54]
Create an `inverted` configuration that forces the theme to use another set of colors. These colors should use a black background and a white foreground.

You can copy and paste the colors from [my site](https://github.com/luizdepra/luizdepra.com/blob/master/assets/scss/_variables.scss). No shame on that.

**Comment by luizdepra** [comment]
This is easily feasible after #77.
I'll create a wiki entry explaining how to do it.

**Comment by DewaldDeJager** [comment]
I would be happy to help with this.

**Comment by luizdepra** [comment]
I just updated this issue with a better description. :)

**Comment by josephting** [comment]
Shouldn't this be closed with #110?
