### ISSUE TITLE
[v2] Remove `hide` configurations

### ISSUE THREAD

**Issue by luizdepra** [luizdepra/hugo-coder#540]
These `hide` configurations are a kind of customization that are easily achieved by overriding one or two files. These features turn our templates really messy. Look how monstrous is the [`partials/footer.html`](https://github.com/luizdepra/hugo-coder/blob/master/layouts/partials/footer.html) template, and it just renders a simple footer section.

So lets remove these configurations and fix all related files:

- `hideFooter`
- `hideCredits`
- `hideCopyright`
- `hideColorSchemeToggle` (we still need to keep hiding the toggle when the color scheme is set to `auto`)

**Comment by luizdepra** [comment]
We removed footerContent for the same motive.

But we still need to remove `hideColorSchemeToggle`.

**Comment by 0xMH** [comment]
Can you please explain how to hide Copyright  and Footer now that the option is removed?

**Comment by luizdepra** [comment]
@0xMH, now you need to override the footer template.

**Comment by peterder72** [comment]
These shall also be removed from all READMEs as it's still in the [example configuration manual](https://github.com/luizdepra/hugo-coder/wiki/Configurations#complete-example). Is someone already on that or shall I fix it?

**Comment by luizdepra** [comment]
If there are any mentions of it in the repository, I would appreciate your help. The wiki page, I'm going to fix it now.
