### ISSUE TITLE
Add categories and tags in Posts.

### ISSUE THREAD

**Issue by TianqiZhang93** [luizdepra/hugo-coder#550]
Show category and tag list in Posts.

**Comment by TianqiZhang93** [comment]
<img width="1489" alt="hugo" src="https://user-images.githubusercontent.com/23652019/113102842-219e3000-9231-11eb-8e5c-600c71b1ae04.png">

I mean show category&tag list here, is it more friendly to readers?

**Comment by a1x42** [comment]
I did add a sidebar in my fork see https://erz.lu/posts/

**Comment by pasindujr** [comment]
When I write content no tags, date and reading time are shown in the single page. How can I sort that.

![Annotation 2021-04-04 134557](https://user-images.githubusercontent.com/61911519/113502886-6c2eed80-954c-11eb-8b2c-0c15ab19f237.png)

**Comment by luizdepra** [comment]
@pasindujr, are you creating a normal page or a post? Only posts are supposed to show tags, categories, date, etc.

**Comment by pduchnovsky** [comment]
I use something like this on my /blog posts page.. if you would be interested I can make a PR for it.

![image](https://user-images.githubusercontent.com/54581833/117512379-c974ef00-af8f-11eb-8fa2-54d57dd46d16.png)

**Comment by pasindujr** [comment]
Hi @pduchnovsky, How did you customize your /blog page your website?

**Comment by pduchnovsky** [comment]
> Hi @pduchnovsky, How did you customize your /blog page in your website?
> 
> And single pages also?

I didn't really edit my single pages, only the blog page tbh. 
As for blog page it's mostly custom css and then changes in pagination files.

**Comment by JensRantil** [comment]
> Hugo Coder already shows tags and categories in post page. See an example [here](https://hugo-coder.netlify.app/posts/markdown-syntax/). You need to enable these taxonomies in your `config.toml`. See this relevant part of our [exampleSite config](https://github.com/luizdepra/hugo-coder/blob/master/exampleSite/config.toml#L96-L100).

Given this response, maybe this issue can be closed?
