### ISSUE TITLE
Cannot render math typesetting in posts

### ISSUE THREAD

**Issue by avs2805** [luizdepra/hugo-coder#556]
First of all, thank you for the template! love the website! 
Running into an issue:
I cant seem to get the math typesetting working for the posts. I tried setting `katex`= `true` in archetypes.md as suggested in #240 post.

I've tried following the steps mentioned in the [`Math Typesetting.md`](https://themes.gohugo.io/theme/hugo-coder/post/math-typesetting.html) as well.

My `config.toml` also has `katex` = `true`. I've also tried with `math` = `true` but the end result still ends up without math rendering.

Any Ideas what I might be doing wrong?

**Comment by luizdepra** [comment]
Right, could you provide an example of Markdown file with math content? Are you trying to use this feature in a `post` content or in a normal page? The math feature is only available in `post` pages right now.

Remembering that you can configure math globally by adding `math = true` or `katex = true` in your `config.toml`, or if you want it only in certain pages, add one of these configurations in your content front-matter.

I'm going to add the math feature for every kind of page, but there are other things in the roadmap row right now. I'm also going to remove mathjax and keep only katex. But I'll keep both `math` and `katex` configurations working.

**Comment by avs2805** [comment]
The issue is with `post` pages.

I've tried both using a using $ and double $$:
$x_t$​
$$\mu'=\frac{r^2\mu+\sigma^2\nu}{r^2+\sigma^2}$$

I've also tried using escape `\`.  so my `config.toml` has `katex=true`. I've also tried adding that to the frontmatter.

**Comment by Shbu** [comment]
@iamrajiv @avs2805 My math typesetting isn't working either. I'm testing this on local machines in hopes to switch to the "coder" theme. I haven't included the math settings in the config.toml file or modified any partials under my project. As suggested, I just added the `math = true` to the front matter of my markdown files. It's still not working. Could you one of you share your code base for the project, thanks.

**Comment by avs2805** [comment]
@iamrajiv  Just tried removing `katex=true` from my `config.toml` and added `math=true` to the front matter of the post. Still cant render math typsetting.

**Comment by luizdepra** [comment]
I'm going to take a double check in this feature to see if there is something broken.

Take a look at your browser if it is loading the math JS files when you load your post. Maybe the CSP feature is blocking the resource load. If this is the problem, you can add the resource domain into CSP config or you can just completely remove CSP from you `config.toml`.

**Comment by iamrajiv** [comment]
@avs2805 @Shbu Yeah, remove the Content-Security-Policy configuration from `config.yaml` file and follow the procedure suggested here https://github.com/luizdepra/hugo-coder/issues/556#issuecomment-831145762.

**Comment by iamrajiv** [comment]
Yeah, remove the Content-Security-Policy configuration from `config.yaml` file and follow the procedure suggested here https://github.com/luizdepra/hugo-coder/issues/556#issuecomment-831145762.

**Comment by Shbu** [comment]
Yup, it worked! 
I didn't wanted to remove CSP entirely given it's benefits of added security layer. Instead, I included the thirdparty domain to the `scriptsrc` tags in the `config.toml` file. Here's before and after. `https://cdn.jsdelivr.net/` is the domain for katex's javascripts. Hope that helps, thanks all!

> before
`# scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]`

> after
`scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com", "https://cdn.jsdelivr.net/"]`

**Comment by avs2805** [comment]
Removing CSP settings completely worked for me! Can render math settings now. Thank you all!
