### ISSUE TITLE
Missing image in metadata

### ISSUE THREAD

**Issue by jfet97** [luizdepra/hugo-coder#561]
Hi, Hugo newbie here 😅!

I am unable to set an image metadata for both the entire website and for a specific post. I am using `featuredImage` in posts, the image shows up in the article but not when I share it. For the entire website I don't know what to do, is there a specific param to set in `config.toml`? Thanks 😃!

**Comment by luizdepra** [comment]
Do you mean the image that is displayed in twitter or facebook cards? Take a look [here](https://gohugo.io/templates/internal/#open-graph) and [here](https://gohugo.io/templates/internal/#open-graph).

Post's feature images are not related with social media sharing links, yet. I need to refactor this feature.

**Comment by jfet97** [comment]
Yes, I've solved thanks to the `images` parameter 😄. Thanks!
