### ISSUE TITLE
Add Sub Menu

### ISSUE THREAD

**Issue by sblzland** [luizdepra/hugo-coder#562]
Hello,

Before, thank you verry much for this template.
I'm tring it since two days and i love it ! 

I'm looking to create a sub menu like this : 

[[menu.main]]
    identifier = "category"
    name = "Category"
    url = "category/"
    weight = 1
  [[menu.main]]
    name = "Category1"
    url = "category1/"
    parent = "category"
  
But it's doesnt work, the menu Category1 appear on the top

**Comment by a1x42** [comment]
please see #542. Nested menus aren’t yet implemented.

**Comment by sblzland** [comment]
Ho sorry for the question, I don't know that "nested menu" was "sub menu" !
Thanks 😌
