### ISSUE TITLE
Easy to read code blocks

### ISSUE THREAD

**Issue by pasindujr** [luizdepra/hugo-coder#567]
How can I make this block of code dark or easy to read?

![Screenshot_20210504_234435](https://user-images.githubusercontent.com/61911519/117052307-350f5000-ad35-11eb-9f99-b19dc13adbcf.jpg)

**Comment by luizdepra** [comment]
We are using a bad default colorscheme for code highlight for a dark theme.
You can choose [other styles](https://xyproto.github.io/splash/docs/) and set it at your `config.toml`.

Example:
```
pygmentsStyle = "monokai"
```

You also can control code highlight styling using a custom CSS file. See [here](https://gohugo.io/content-management/syntax-highlighting/).
