### ISSUE TITLE
Blockquotes line breaks

### ISSUE THREAD

**Issue by phpgao** [luizdepra/hugo-coder#571]
Here is a doc abount blockquotes:

Use the > character in front of a line, just like in email

```
> Use it if you're quoting a person, a song or whatever.

> You can use *italic* or lists inside them also.
And just like with other paragraphs,
all of these lines are still
part of the blockquote, even without the > character in front.

To end the blockquote, just put a blank line before the following
paragraph.
```
Output:

Use it if you're quoting a person, a song or whatever.

You can use italic or lists inside them also.
And just like with other paragraphs,
all of these lines are still
part of the blockquote, even without the > character in front.

To end the blockquote, just put a blank line before the following
paragraph.

But in hugo:

![企业微信截图_3c8a98c1-4323-4cbd-a6df-3941c5d41c2d.png](https://i.loli.net/2021/05/09/S1c7zaNiV2vjmUx.png)

**Comment by alfunx** [comment]
First, I don't think this is an issue related to this theme.
And I don't think this is an issue at all, actually ­­– the behavior is exactly as described by the text…

**Comment by luizdepra** [comment]
Yep. This is how Hugo handles line breaks inside quotes, and I think this is the default and correct behavior.
