### ISSUE TITLE
Can't use HTML tags inside a blog post

### ISSUE THREAD

**Issue by utkarsh2102** [luizdepra/hugo-coder#576]
Hello,

Thanks for writing this! 🎉 
However, whilst trying to write HTML tags to center align something (which Markdown supports) like:
`<center> hugo-coder </center>`
...I found that the blog post rendered doesn't show "hugo-coder" anywhere. Further it turns out that if I use anything with HTML tags, nothing gets rendered. 

Please let me know if I am missing something; thanks!

**Comment by utkarsh2102** [comment]
Extending this further, how do I center align a text? Also, is there a way to justify the text? 😭

**Comment by pduchnovsky** [comment]
In your config enter:

```
[markup.goldmark.renderer]
unsafe= true
```

This enables raw html support in markdown files.

**Comment by utkarsh2102** [comment]
Wooot, thanks, @pduchnovsky! 🎉

**Comment by luizdepra** [comment]
Solved, right?
