### ISSUE TITLE
SEO and metadata

### ISSUE THREAD

**Issue by endormi** [luizdepra/hugo-coder#585]
Hi!

I haven't seen tips on how to update metadata, so if there is sorry about that. I only get some text when I link my page on social media. 
Is there a possibility of having an image instead of text?

Thanks for making this awesome theme!

**Comment by luizdepra** [comment]
I think you are talking about open graph metadata. Am I right?
Take a look [here](https://gohugo.io/templates/internal/#open-graph). This is a Hugo feature, so you just need to configure it as it is explained in the docs.

**Comment by endormi** [comment]
Yeah I am. Thanks!
