### ISSUE TITLE
the `a` may be overflowing its line box

### ISSUE THREAD

**Issue by chenkai0520** [luizdepra/hugo-coder#586]
<img width="395" alt="截屏2021-07-13 下午12 03 46" src="https://user-images.githubusercontent.com/30174970/125389175-62324b80-e3d3-11eb-944f-0a2d0150ca89.png">

the `a` should insert line breaks within an otherwise unbreakable string to prevent text from overflowing its line box.

```css
a {
  word-wrap: break-word;
}
```

<img width="401" alt="截屏2021-07-13 下午12 05 24" src="https://user-images.githubusercontent.com/30174970/125389222-74ac8500-e3d3-11eb-819c-a9cf9a7a6105.png">

**Comment by luizdepra** [comment]
Done!
