### ISSUE TITLE
Discussion: Extensible touchpoints with more modular includes?

### ISSUE THREAD

**Issue by fj** [luizdepra/hugo-coder#591]
Looking across some of the forks of `hugo-coder`, I've noticed that many people fork to customize or change parts of hugo-coder in appearance or structure, without changing functionality very much.

I think there would be less reason to fork if the touchpoints were extended and explicit. That way, extensions happen using Hugo rather than needing git forks of `hugo-coder` — you'd simply override a file in your site, rather than editing the theme.

## A simple example

For example, let's say you want to add extra headers or conditional logic to the `<head>` tag. Right now, there's not necessarily an easy way to do this short of modifying the `baseof.html`. But if you do that, now you've touched a file in `themes/`, which means you're running a fork of `hugo-coder`. Bummer!

How can we improve this and avoid needing to fork `hugo-coder`? Using this example, if there were, say, a `baseof.html` like this:

```
# baseof.html
⋯
<head>
  <!-- many things specific to hugo-coder theme -->
</head>
⋯
```

might instead look like:

```
# baseof.html
⋯
<head>
  {{- partial "head-hugo-coder.html" . -}} <!-- specific to hugo-coder -->
  {{- partial "head-extensions.html" . -}} <!-- blank in theme; available for overriding in consumers -->
</head>
⋯
```

This way, you don't modify a `hugo-coder` file; you modify a file in your own local repository, and you aren't breaking your compatibility with `hugo-coder`. Repeat this exercise for every interesting extension point.

## An offer to drive this

If you like this idea, I'd be willing to shepherd this and open a PR for review that would cover a number of such touchpoints. But before proceeding I wanted to gauge interest.

**Comment by luizdepra** [comment]
Interesting idea. I would accept this kind of change, no problem.
But, it will consume a good amount of effort to change everything. Maybe it would be a good idea to start small, only changing a few templates.
Also, maybe it would be a good idea to pin a new version of the theme before accepting these changes. It will break lots of things.

**Comment by fj** [comment]
Great, thanks for the feedback. Just to outline this, I think I'd probably only modify `baseof.html` to start with, and I'd have:

* `baseof.html`
  * `head.html`: everything in `<head>` right now
    * `head-icons.html`: controls the icons
    * `head-styling.html`: controls the styling directives
    * `head-color-scheme.html`: controls the color scheming
    * `head-alternative-outputs.html`: controls extra outputs
    * `head-extensions.html`: blank in the theme; used as an extension point

and that's it. Then, if that goes well you can consider if you'd like to expand (but imo that should be a separate PR).

Does this sound like a plan? If so I'll get started.

**Comment by luizdepra** [comment]
People that already override our templates will not benefit of these changes until they refactor their code. But I think this is ok if we make things clear.
