### ISSUE TITLE
KaTex not rendered at all

### ISSUE THREAD

**Issue by tarunjana** [luizdepra/hugo-coder#593]
I am having a hard time implementing KaTex. I've set `katex: true` in the frontmatter. Still, no result is visible. After inspecting the page source code, I've found that KaTex is injected in the `body` tag. If I'm not wrong, this should be injected in the `head` tag.

Please have a look at the source code of this page: [View Source](https://tarunjana.codeberg.page/posts/math-typesetting/)

Thank you in advance!

**Comment by rabinadk1** [comment]
It should work. Your issue might be related to https://github.com/luizdepra/hugo-coder/pull/575/commits/9b9ea48771a734d6e0089aaf6b64ba174cd7afde

**Comment by tarunjana** [comment]
I've already done the task of setting `katex:true` in the front matter. But KaTex is not rendering. Perhaps the issue is related to something else.

Anyway, thanks man for your valuable comment @rabinadk1 :)
