### ISSUE TITLE
Mermaid support

### ISSUE THREAD

**Issue by jneo8** [luizdepra/hugo-coder#594]
Is there any plan/way to support [mermaid](https://mermaid-js.github.io/mermaid/#/) in this theme?

**Comment by luizdepra** [comment]
Not, but it is a good addition for this theme.

**Comment by luizdepra** [comment]
Closing because #595 was merged.

**Comment by abhemanyus** [comment]
How, exactly, does one use the mermaid feature? I do not see that shortcode importing the mermaid.js script anywhere.

**Comment by luizdepra** [comment]
Something broken when we made a recent refactor. I'm going to take a look.

**Comment by luizdepra** [comment]
It is working now. See [here](https://hugo-coder.netlify.app/posts/mermaid-support/).
Sadly, It is not possible to change themes yet. I need to make a little refactor to make it happen.

**Comment by abhemanyus** [comment]
Is it possible to make mermaid generate the .svg, and then embed that into the webpage? Even the minified javascript is over 1MB in size, and makes it impossible to have a javascript-free site.

**Comment by abhemanyus** [comment]
> Yes, you could add the generated images as static files. But, you'll need to create a `Makefile` or something like that to generate the images before running Hugo.

Nice, gonna look into that. Thanks!
