### ISSUE TITLE
[v2] Talks/Presentations Archetype

### ISSUE THREAD

**Issue by luizdepra** [luizdepra/hugo-coder#60]
Partially implemented in #12.
I want to keep this theme lightweight. I don't want to use JS, so the solution in #12 doesn't fit it well.

Find a full screen, CSS only solution to present slides.

**Comment by clement-pannetier** [comment]
Hi @luizdepra, I searched a css only solution to do that, can you explain in details what you want ?

How you imagine the layout for this new archetype ?

To create a new presentation we should add a new .md file in `content/presentations/` folder ? How we style the content. I found a [tool](https://marp.app/) to do that but that's not lighweight 😅.

**Comment by luizdepra** [comment]
Hey. I missed your message here, @clement-pannetier.
Well, I'm dropping this idea. I think it is better to use other themes or tools for presentations.
