### ISSUE TITLE
fontawesome size (fa-..x) overwritten

### ISSUE THREAD

**Issue by metbril** [luizdepra/hugo-coder#607]
The larger size for the social icons on the home page is overwritten by the `.centered` class.

The example config has `fa-2x` class added, but the CSS is overwritten by the `.centered` class with a fixed **3.2em** size.

See screenshot.

<img width="443" alt="Schermafbeelding 2021-10-08 om 14 43 17" src="https://user-images.githubusercontent.com/559346/136559139-d70ae51b-4fa2-4dbc-a91b-8c8d6d41b19f.png">
.

**Comment by luizdepra** [comment]
I'm open to contributions with this issue.

We should respect the fork-awesome CSS rules.
