### ISSUE TITLE
H1 font size differently for pages, posts and lists

### ISSUE THREAD

**Issue by metbril** [luizdepra/hugo-coder#609]
For lists (including taxonomies), the font size is 3.2em, but for pages it is 4.2em. It looks better if both are the same.

Pages and posts use this:

https://github.com/luizdepra/hugo-coder/blob/af7360e89ab0220c8c1e1da2ab28cfab3410b809/assets/scss/_content.scss#L18-L27

Lists use this:

https://github.com/luizdepra/hugo-coder/blob/af7360e89ab0220c8c1e1da2ab28cfab3410b809/assets/scss/_base.scss#L72-L80

**Comment by luizdepra** [comment]
I'm open to contributions with this issue.

We should use Page's values as default for headings.

**Comment by AbdAllahAbdElFattah13** [comment]
@luizdepra 
Correct me if I'm mistaken, but this looks like a simple pr to me, just overriding the value in defaults, no? 

If so, I can have it pr-ed in the same day. Since I'm using the theme into my own website (still under dev) this is the least I can do. : ))

**Comment by luizdepra** [comment]
Yup. It is already fixed.
I forgot to close this issues, but thanks for pointing it to me.
