### ISSUE TITLE
Issue with HTML when viewing page source

### ISSUE THREAD

**Issue by ben-christian** [luizdepra/hugo-coder#616]
Hi there,

I am not sure if this is an issue with the theme, netlify or something I have done...

When viewing my page source, the html is written out in a couple long lines rather than being neatly organised as you would expect. I have line wrap off and I have also checked on a number of browsers, all having the same problem. Interestingly this isn't the case when using hugo serve to view my blog, only once it has been deployed using Netlify. If you right click and click 'view page source' on one of my web pages, you will see what I mean. Blog: www.benchristian.com.au

P.S I am very new to website building, especially using hugo. I made an effort to google for the solution first though it was to no avail.

Any help with this issue would be greatly appreciated:)

**Comment by luizdepra** [comment]
Yeah, this is an issue that bothers me too. It is hard to work with templates and complete avoid creating messy HTML code. If you look into another themes, they should have the same problem.
I think the easy way to avoid that is to use a `beautifier` tool after building the site.
