### ISSUE TITLE
Adding Open Graph image metadata to hugo-coder

### ISSUE THREAD

**Issue by iamrajiv** [luizdepra/hugo-coder#617]
## Description

When I share https://iamrajiv.github.io/ over social media, it should generate an Open Graph image for the link and should have useful information.

## References

- Use https://developers.facebook.com/tools/debug/ to validate results for Facebook.
- Use https://www.linkedin.com/post-inspector/ to validate results for LinkedIn.
- Use https://cards-dev.twitter.com/validator to validate results for Twitter.

**Comment by iamrajiv** [comment]
@luizdepra I want to work on this.

**Comment by luizdepra** [comment]
Doesn't Hugo already provide these features?

**Comment by iamrajiv** [comment]
@luizdepra I don't think so when I shared my website to Twitter meta card is not showing. We have to update `layouts/_default/baseof.html` and add meta code for og-image.

**Comment by luizdepra** [comment]
We add OG and Twitter Cards internal templates [here](https://github.com/luizdepra/hugo-coder/blob/master/layouts/_default/baseof.html#L18-L19). So, you should only need to configure your site or post frontmatter with the image you want. See [here](https://gohugo.io/templates/internal/#twitter-cards) or [here](https://gohugo.io/templates/internal/#configure-open-graph).

**Comment by luizdepra** [comment]
Nop. You will need to add `images = ['some-image.jpg']` into `[params]`. See [here](https://gohugo.io/templates/internal/#configure-open-graph).
