### ISSUE TITLE
Some questions about certain settings and options

### ISSUE THREAD

**Issue by sander1095** [luizdepra/hugo-coder#621]
Hello! I am pretty new to hugo, ssg and this theme and have some questions that I cant find answers for.. 

Hopefully you can help me out!

- in the example config I see things like pygmentsstyle and other options related to it. Changing them doesnt result in a visual difference. What are these properties for and can you link me to a site so I can read more about it?
- in the readme there is an example of the theme with a black and white background. My site only has a black background. How could I make it black/white? How could I style this myself?
- I have also seen examples where some blog posts are featured on the homepage. I love this! How can I implement this?

Thanks!

**Comment by luizdepra** [comment]
> in the example config I see things like pygmentsstyle and other options related to it. Changing them doesnt result in a visual difference. What are these properties for and can you link me to a site so I can read more about it?

`pygmentsstyle` is a former but still functional way to change the syntax highlighting of your code blocks. See [here](https://xyproto.github.io/splash/docs/all.html) for more styles. Or, you can also use the new syntax highlighter, [chroma](https://gohugo.io/content-management/syntax-highlighting/).

> in the readme there is an example of the theme with a black and white background. My site only has a black background. How could I make it black/white? How could I style this myself?

You can specify which color scheme you want to use with the `colorScheme` configuration. See the [exampleSite `config.toml`](https://github.com/luizdepra/hugo-coder/blob/master/exampleSite/config.toml#L27-L32). You can configure it to be default `light` or `dark`, or use `auto` to pick the preferred color scheme from the use browser/system.

> I have also seen examples where some blog posts are featured on the homepage. I love this! How can I implement this?

Hugo Coder does not support this feature, but you can easily do it by just overriding the [home template](https://github.com/luizdepra/hugo-coder/blob/master/layouts/partials/home.html).
