### ISSUE TITLE
Some md files not rendering

### ISSUE THREAD

**Issue by dvanic** [luizdepra/hugo-coder#622]
Hi! I think I have a very silly problem: some of the markdown files from my projects folder are not being rendered into html, and I'm not entirely sure how to fix it.

Specifically, `content/project/omia.md` ([link](https://github.com/dvanic/blogdown/blob/master/content/project/omia.md)) and `content/project/corpus.md` ([link](https://github.com/dvanic/blogdown/blob/master/content/project/corpus.md)), which I expect to appear at https://daryavanichkina.com/project/omia and https://daryavanichkina.com/project/corpus

Other markdowns from the project folder work and are rendered, for example: https://daryavanichkina.com/project/protehome/ , source [link](https://github.com/dvanic/blogdown/blob/master/content/project/protehome.md)

Repo for site: https://github.com/dvanic/blogdown (note: I'm not actually using blogdown, just pure hugo for the build - I need to rename the repo)

Ideas I have for what I might be doing wrong, but I just can't seem to get working:

- I haven't create a project/_index.md file with the correct (?) layout specified?
- I need to create some layouts?
- ?

Thanks in advance,
Darya

**Comment by luizdepra** [comment]
I couldn't find anything wrong in your content files. I tried to generate your site with the flag `--debug` flag and the log says the pages were generated, but still, there is nothing there.

So, I don't think this is a theme problem, maybe a Hugo's bug. Have you sought help in Hugo's Discourse? I think they can help you more than me.

If you find the problem, please ping me. I'm curious now.

**Comment by dvanic** [comment]
LOL. I'm so sorry, and thank you so much for taking the time to answer and test. 
The dates for the pages were set to the future 🤣 : As I said, guaranteed to be a silly mistake 🤦‍♀️ .

**Comment by luizdepra** [comment]
Well, this is an interesting feature. ahahaha
