### ISSUE TITLE
images not rendering on localhost

### ISSUE THREAD

**Issue by ebelabrie** [luizdepra/hugo-coder#623]
hello, i am running into an error while trying to demo my website on localhost. my image url is specified correctly in my config.toml

```
[params]
author = "lorem ipsum"
description = "lorem ipsum's personal website"
keywords = "lorem ipsum"
# info = ["xyz", "lorem ipsum"]
avatarURL = "images/avatar.jpg"
```
i also tried using the file path of the image from the example site, but am running into the same issue
```
[params]
author = "lorem ipsum"
description = "lorem ipsum's personal website"
keywords = "lorem ipsum"
# info = ["xyz", "lorem ipsum"]
avatarURL = "exampleSite/static/images/avatar.jpg"
```

here is what the site looks like when loaded: 

![image](https://user-images.githubusercontent.com/42724995/142784732-b58e2633-37c1-45f3-abd1-ca770fdd2838.png)

 have you seen this before? i'm still new to hugo so maybe i'm missing something.

**Comment by tarunjana** [comment]
The image path should be relative to the `static` folder. For your case, the avatar image must reside at `static/images/avatar.jpg`

**Comment by ebelabrie** [comment]
thank you for your response. my `images` folder is at the top-level directory. both urls are specified correctly and i'm running into the same error for both code segments.

**Comment by ebelabrie** [comment]
this issue is consistent on both safari and chrome. not sure whether it is relevant, but i just updated my OS from big sur to monterey 12.0.1.

**Comment by tarunjana** [comment]
Hugo will copy everything as it is from the `static` folder to the build directory. So you have to place your static assets(like images etc.) in the `static` folder.

For the avatar to work, you must put the image in the `static` directory. You may create sub-directories in the `static` directory and organize your static files.

The links to these static files must be relative to `static` directory.

P.S. - A top-level `images` directory (as you've said) will not work in this case.

**Comment by ebelabrie** [comment]
tried adding the `images` folder to the `static` folder

see my updated `config.toml`:

```
[params]
author = "lorem ipsum"
description = "lorem ipsum's personal website"
keywords = "lorem ipsum"
# info = ["xyz", "lorem ipsum"]
avatarURL = "static/images/avatar.png"
```
my folder structure:

![image](https://user-images.githubusercontent.com/42724995/142800006-3a656cef-564a-4e62-8aeb-0a871569751c.png)

still hitting this same rendering error

![image](https://user-images.githubusercontent.com/42724995/142800185-1d0f396d-7abb-491b-9382-e52cf305e271.png)

**Comment by tarunjana** [comment]
Your configuration should work. I'm not sure what's going wrong! :(

**Comment by luizdepra** [comment]
Your avatar config should be like this:

```avatarURL = "images/avatar.png"```

Hmm.. There is something weird here. Are you trying to build your site on top of this repository? If so, you shouldn't. Create a new project with Hugo and add this theme as a submodule or copy its content. See [here in the README](https://github.com/luizdepra/hugo-coder#quick-start). But, if you only want to test the theme, run `make demo`. You will need to have `make` and probably other GNU tools installed.

**Comment by ebelabrie** [comment]
ohh that's my problem. i had been building my site on a forked version of `hugo-coder` lol
