### ISSUE TITLE
Image inside a post

### ISSUE THREAD

**Issue by csor-dev** [luizdepra/hugo-coder#628]
I've built my site with this hugo theme. I've made a few posts and all is well, except that I'm not sure what the path should be for adding images inside posts.

I've tried placing the images in static but that only works for *avatarURL*. Within a Post, I'm not sure how to place an image. can someone let me know what's the path I should be using for displaying images inside Posts.

So far I've tried placing the images in static/ & Posts folder itself. I've tried with multiple formats. Nothing worked.

By images I mean to display images somewhere within the Post. I'm not talking about *featuredImage*. I'm having the same issue with *featuredImage* also. I'd like to use both if available. Is there anyway to solve this? I'm not even sure if images inside posts are supported.

**Comment by luizdepra** [comment]
Hey!

The right place for the images and any other static content is the `static` folder. See [my static folder](https://github.com/luizdepra/luizdepra.dev/tree/master/static/) for example. Notice that any folder or file inside your `static` folder will be moved to the root folder after build. So, you need to properly set the path in your md files. You can use subfolders as you wish. See this [content example with images](https://github.com/luizdepra/luizdepra.dev/blob/master/content/posts/sn-50-my-new-audacious-project.en.md).

- file at `static/something.jpg` => url inside md will be `something.jpg`
- file at `static/images/that.png` => url inside md will be `images/that.png`
- file at `static/images/hello/hey.gif` => url inside md will be `images/hello/hey.gif`

**Comment by csor-dev** [comment]
Thanks @luizdepra for the quick response.
I've been using the regular markdown method of displaying messages. i.e., `![ ](image_location)`. It works with the format you mentioned. But the issue with featuredImage still persists.

`featuredImage = ["pic.jpg"]` where location of the pic is `static/pic.jpg`.

I'm not sure if I'm doing something wrong as I'm new to Hugo. I won't be using featuredImage anyway but I just thought I should let you know in case this is something to fix. 

Thanks again :)

**Comment by luizdepra** [comment]
I'm going to take a look on that issue. Thanks for reporting it. :)

**Comment by csor-dev** [comment]
Actually it's working fine. It's just that we have to specify root like `/images/smt.png` instead of `images/smt.png`. I was trying without the slash previously. In my case it's `featuredImage = ["/pic.jpg"]`
