### ISSUE TITLE
Code snippets do not render to dark mode colors

### ISSUE THREAD

**Issue by danerwilliams** [luizdepra/hugo-coder#629]
When using the dark theming, if you include a code snippet with ```  it doesn't render particularly dark.

I would be interested in potentially submitting a PR to change this, does anyone have input in terms of how they would like this to look?

This is how it currently renders:
![Screen Shot 2021-12-10 at 12 25 10 AM](https://user-images.githubusercontent.com/22798229/145521872-c6e870c8-e4f2-4f56-b7bb-8ced00525d93.png)

**Comment by miatemma** [comment]
Hi, I noticed the same topic yesterday too. In my opinion it would be great if it rendered to the same style as the in-line ``<code>`` snippets (dark grey background, light text color).

**Comment by luizdepra** [comment]
See #603 and #596.
The default syntax highlight option (`bw` in the exampleSite) doesn't look well with the dark color scheme. You can try to find other styles that match with both color schemes or use custom CSS code to change the colors.

**Comment by alfunx** [comment]
Just made a PR (#630) that should fix this finally.

Alternatively we could set some proper syntax highlighting color scheme that explicitly sets the foreground color (like `monokai` for example) in the example config. Though people may run into this issue anyways. Besides that, I think `bw` is a good unopinionated theme.
