### ISSUE TITLE
Problems reproducing the initial steps and displaying it on localhost

### ISSUE THREAD

**Issue by juanby** [luizdepra/hugo-coder#631]
Hi. Sorry for these doubts if they are simple. I am new to using Hugo. Before installing the template, I have run "git init" in the site directory.
I followed the "Quick Start" steps, and after running "hugo server" the end of the 01_file was the message. After that I have copied the content of "examplesite" to the root directory and this message appear (02_file).

Could you help me?

[01_file.txt](https://github.com/luizdepra/hugo-coder/files/7715661/01_file.txt)
[02_file.txt](https://github.com/luizdepra/hugo-coder/files/7715663/02_file.txt)
[dis.zip](https://github.com/luizdepra/hugo-coder/files/7715850/dis.zip)

Thank you!

**Comment by juanby** [comment]
(hugo new site > cd dgit submodule add .... (error!) > git init > cd dgit submodule add .... > hugo server -D)
--> message: 
Building sites … ERROR 2021/12/15 00:21:15 render of "taxonomyTerm" failed: "C:\Users\juan_\webs\dis\themes\hugo-coder\layouts\_default\baseof.html:66:47": execute of template failed: template: _default/terms.html:66:47: executing "_default/terms.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
ERROR 2021/12/15 00:21:15 render of "taxonomyTerm" failed: "C:\Users\juan_\webs\dis\themes\hugo-coder\layouts\_default\baseof.html:66:47": execute of template failed: template: _default/terms.html:66:47: executing "_default/terms.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
ERROR 2021/12/15 00:21:15 render of "taxonomyTerm" failed: "C:\Users\juan_\webs\dis\themes\hugo-coder\layouts\_default\baseof.html:66:47": execute of template failed: template: _default/terms.html:66:47: executing "_default/terms.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
ERROR 2021/12/15 00:21:15 render of "home" failed: "C:\Users\juan_\webs\dis\themes\hugo-coder\layouts\_default\baseof.html:66:47": execute of template failed: template: index.html:66:47: executing "index.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
Built in 114 ms
Error: Error building site: failed to render pages: render of "taxonomyTerm" failed: "C:\Users\juan_\webs\dis\themes\hugo-coder\layouts\_default\baseof.html:66:47": execute of template failed: template: _default/terms.html:66:47: executing "_default/terms.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink

After that I have copied the content of "examplesite" to the root directory and this message appear (02_file).
(hugo server -D)
Message:
PS C:\Users\juan_\webs\dis> hugo server
Building sites … ERROR 2021/12/15 00:39:58 render of "page" failed: "C:\Users\juan_\webs\dis\themes\hugo-coder\layouts\_default\baseof.html:66:47": execute of template failed: template: _default/single.html:66:47: executing "_default/single.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
ERROR 2021/12/15 00:39:58 render of "page" failed: "C:\Users\juan_\webs\dis\themes\hugo-coder\layouts\_default\baseof.html:66:47": execute of template failed: template: posts/single.html:66:47: executing "posts/single.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
ERROR 2021/12/15 00:39:58 render of "page" failed: "C:\Users\juan_\webs\dis\themes\hugo-coder\layouts\_default\baseof.html:66:47": execute of template failed: template: posts/single.html:66:47: executing "posts/single.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
ERROR 2021/12/15 00:39:58 render of "page" failed: "C:\Users\juan_\webs\dis\themes\hugo-coder\layouts\_default\baseof.html:66:47": execute of template failed: template: _default/single.html:66:47: executing "_default/single.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
Built in 1359 ms
Error: Error building site: failed to render pages: render of "page" failed: "C:\Users\juan_\webs\dis\themes\hugo-coder\layouts\_default\baseof.html:66:47": execute of template failed: template: _default/single.html:66:47: executing "_default/single.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink

Could you help me?
Thank you.

**Comment by luizdepra** [comment]
Hey Juan!

I don't know for sure what the problem is, so I need some more information.

- **Which version of Hugo are you using?** This theme requires the `hugo-extended` variation.
- **Have you created a new Hugo project, or are you using this repository as a base?** You should always start a new and empty project and after that add this theme. Hugo's [quick start](https://gohugo.io/getting-started/quick-start/) explains how to start a new project and add theme, both with a submodule or just with copy-and-paste. Also, you need to configure the `theme` options in `config.toml` with the correct value, or just copy the same file to the root directory of your site project.
- **Have you uploaded your site to a public repository?** I could test and debug your site if so.

You can take [my own site](https://github.com/luizdepra/luizdepra.dev) as example too.

**Comment by juanby** [comment]
Hi Luiz. I have been testing and finally, I read your comment and uninstalled hugo (1 year old version), installed it again and followed the steps. 
Now it works correctly. I just need to do the necessary customization.
Thank you very much for your help.
Best regards.

**Comment by luizdepra** [comment]
Nice. :)
I'm glad I could help.
