### ISSUE TITLE
trouble with configuration

### ISSUE THREAD

**Issue by ebelabrie** [luizdepra/hugo-coder#634]
hello

i initialized a new hugo project as per the [hugo docs](https://gohugo.io/getting-started/quick-start/)

then i followed the quick start guide for installing the hugo-coder theme according to the [readme on this repo](https://github.com/luizdepra/hugo-coder).

specifically, i ran `git submodule add https://github.com/luizdepra/hugo-coder.git themes/hugo-coder`

then i copied the [minimal configuration](https://github.com/luizdepra/hugo-coder/wiki/Configurations#complete-example) to my config.toml file at the top level of my directory.

when i run hugo server, this is the error message i am getting:

```
 % hugo server
Start building sites … 
hugo v0.87.0+extended darwin/amd64 BuildDate=unknown
ERROR 2021/12/21 14:37:16 render of "taxonomy" failed: "/Users/allisonlowe/source/portfolio/themes/hugo-coder/layouts/_default/baseof.html:66:47": execute of template failed: template: _default/terms.html:66:47: executing "_default/terms.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
ERROR 2021/12/21 14:37:16 render of "taxonomy" failed: "/Users/allisonlowe/source/portfolio/themes/hugo-coder/layouts/_default/baseof.html:66:47": execute of template failed: template: _default/terms.html:66:47: executing "_default/terms.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
ERROR 2021/12/21 14:37:16 render of "home" failed: "/Users/allisonlowe/source/portfolio/themes/hugo-coder/layouts/_default/baseof.html:66:47": execute of template failed: template: index.html:66:47: executing "index.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
ERROR 2021/12/21 14:37:16 render of "taxonomy" failed: "/Users/allisonlowe/source/portfolio/themes/hugo-coder/layouts/_default/baseof.html:66:47": execute of template failed: template: _default/terms.html:66:47: executing "_default/terms.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
Error: Error building site: failed to render pages: render of "taxonomy" failed: "/Users/allisonlowe/source/portfolio/themes/hugo-coder/layouts/_default/baseof.html:66:47": execute of template failed: template: _default/terms.html:66:47: executing "_default/terms.html" at <$styles.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink
```

**Comment by carvalholeo** [comment]
Hey, how are you?

Recently, I get this error too. Please, look at your files and confirm that into root directory there is an `asset` directory. Into there, you'll put your CSS, JS and SCSS files.

On config file, you need to change anything. So, try this and give us feedback.

**Comment by ebelabrie** [comment]
thank you for your response

i added a `asset` folder to the project's root directory. can you clarify which css, js, and scss files i should add to the `asset` folder? i tried cutting and pasting the files that were under `/resources/_gen/assets` to the `/asset` folder. when i do this i run into the same error.

here is what my directory looks like:

![image](https://user-images.githubusercontent.com/42724995/147050568-14cc607c-3e3c-4f9a-8625-b4a1b8fd705b.png)

i moved the files back to their original location so that the source is as rudimentary as possible

**Comment by ebelabrie** [comment]
i tried both `asset` and `assets` as the folder name

**Comment by ebelabrie** [comment]
i copied the contents of the example site to my root directory and it's working without error. i think the config file from the example site is what did it

**Comment by larshaendler** [comment]
Got the same issue and found these three parameters from the example configuration to be the cause:
``` 
customCSS = ["css/custom.css"]
customSCSS = ["scss/custom.scss"]   
customJS = ["js/custom.js"]   
```
I have of course none of these files in my initial page. I just cleared the arrays for later use
```  
customCSS = []   
customSCSS = []   
customJS = []   
```

Et voila, no more erros.
