### ISSUE TITLE
Images fail to load using R's blogdown package

### ISSUE THREAD

**Issue by adrian-pascual** [luizdepra/hugo-coder#638]
Tried using this theme via R blogdown (same method in #243), everything looks fantastic except the images won't load. Inspected the element, says that it's a CSP issue. Basically the image sources aren't associated with the main site for some reason, even though they're all stored in `static/images/`.

![Screen Shot 2022-01-23 at 8 37 29 PM](https://user-images.githubusercontent.com/34633402/150708536-1c49adc6-e0a0-4651-8f42-ccace218ce9f.png)

**Comment by luizdepra** [comment]
Try verifying if the `imgsrc` is properly configured. You also could completely remove the `[params.csp]` section from the configuration.

**Comment by adrian-pascual** [comment]
Removing the CSP allowed the images to load! For some reason Blogdown is loading all the `[params.csp]` with three `'` instead of `' "`. I tried changing the quotes / apostrophes, but it didn't fix the images. For now I'll just leave the CSP out, obrigado! 

```r
 csp:
    childsrc: '''self'''
    connectsrc:
      - '''self'''
      - https://www.google-analytics.com
    fontsrc:
      - '''self'''
      - https://fonts.gstatic.com
      - https://cdn.jsdelivr.net/
    formaction: '''self'''
    framesrc: '''self'''
    imgsrc: "'self'"
    objectsrc: '''none'''
    prefetchsrc: '''self'''
    scriptsrc:
      - '''self'''
      - '''unsafe-inline'''
      - https://www.google-analytics.com
      - https://cdn.jsdelivr.net/
    stylesrc:
      - '''self'''
      - '''unsafe-inline'''
      - https://fonts.googleapis.com/
      - https://cdn.jsdelivr.net/
```
