### ISSUE TITLE
Git Commit In Footer

### ISSUE THREAD

**Issue by dalenoe** [luizdepra/hugo-coder#64]
This is a feature request to add the git commit in the footer.

**Use case:** It would be useful for a site that has multiple contributors.

It would also be nice to have it disabled (hidden), as not everyone will want/need it. I have seen some examples in other themes, so I am going to reference them here as well.

Links:
- https://github.com/halogenica/beautifulhugo#commit-sha-on-the-footer
- https://github.com/halogenica/beautifulhugo/blob/master/layouts/partials/footer.html#L53

There could be more too it that I am not aware of. I am still learning Hugo and its themes, so I apologize. I have been testing this on my personal site, I don't quite have it working yet. Assuming I can get it working, I could contribute the changes.

**Comment by dalenoe** [comment]
This was briefly discussed in a different issue: #50

**Comment by dalenoe** [comment]
I haven't had much time, or luck. lol

I think I am getting close, but still isn't working. The [] where the hash should be, is still showing as blank.

**Comment by khos2ow** [comment]
You can commit and push and open a PR of what you have as is, and someone might be able to help you or point something out on the feature.

**Comment by dalenoe** [comment]
I will work on submitting what I have this coming weekend.

**Comment by dalenoe** [comment]
I've forked the project, and have created a new branch with my changes. Hope to have a pr submitted by the end of this weekend.

**Comment by dalenoe** [comment]
woohoo, I got it working on my personal site. I was forgetting to set the environment variable on the CI.. I will get the PR submitted for sure.

**Comment by khos2ow** [comment]
@luizdepra this can be closed.
