### ISSUE TITLE
Problem with deploying website using hugo-coder theme on Github

### ISSUE THREAD

**Issue by nowhash** [luizdepra/hugo-coder#640]
My blog site using Hugo-coder theme can not render properly on Github pages.
Here is the link to my blog: nowhash.github.io
Is there any specific way to deploy this theme on GitHub?
Thank you.

**Comment by ccviolett** [comment]
Can you deploy it on your own computer? If it is able to render properly on your computer when you use `hugo server`, it won't be any problem.

**Comment by nowhash** [comment]
It works fine locally. 
Most probably I messed up with the baseURL. The problem was solved after replacing the base URL- nowhash.github.io with https://nowhash.github.io.
