### ISSUE TITLE
error: footer.html parse error

### ISSUE THREAD

**Issue by abrahamalen** [luizdepra/hugo-coder#645]
**hugo serve** command is not running due to a parsing issue in the **footer.html** file, don't know why this error is coming. I tried with footer code in the template as well but resulted in the same error.  Code is in my repo
![image](https://user-images.githubusercontent.com/53680255/151703707-0831a3ae-6d29-4261-8343-00a36917b765.png)

**Comment by luizdepra** [comment]
Are you using an HTML formatter in your editor? It looks like something is formatting all the template tags wrong. Look at the [original file](https://github.com/luizdepra/hugo-coder/blob/main/layouts/partials/footer.html), see that in your file there are some template tags closing in a next line. And this is not valid.

**Comment by abrahamalen** [comment]
> Are you using an HTML formatter in your editor? It looks like something is formatting all the template tags wrong. Look at the [original file](https://github.com/luizdepra/hugo-coder/blob/main/layouts/partials/footer.html), see that in your file there are some template tags closing in a next line. And this is not valid.

Oh yes, I am using the prettier extension as a code formatter, let me remove and check it out

**Comment by abrahamalen** [comment]
Hey @luizdepra **thanks** for the response, it worked. I removed the code formatter and tried. :heart:
