### ISSUE TITLE
How can I extend this theme by adding my blog posts to the homepage?

### ISSUE THREAD

**Issue by sander1095** [luizdepra/hugo-coder#647]
Hello!

I am super new to hugo, but I love this theme A LOT.

[My site](https://stenbrinke.nl/) uses it, and I would like to extend it by making (Featured) blog posts show up on the title screen. Starting out with some title, link and the post date I suppose. 
I also like to add some links to posts where I will be speaking at conferences

Here is a crude example.
![image](https://user-images.githubusercontent.com/7312681/153276823-7396b3db-38b6-48e8-8058-503a53ff8b60.png)

I would love some pointers on how I could achieve this myself. What code do I need to extend to for example grab the 3 most recent posts etc...

**Comment by sander1095** [comment]
Related to https://github.com/luizdepra/hugo-coder/issues/320, but I can't really get that to work yet. Overriding a file by creating my own `/layouts/FILE_HERE`  doesn't override the theme for me..

**Comment by luizdepra** [comment]
I saw you comment at #320. It looks like you did everything right. But, have you uploaded your project to GitHub, so I could take a look?

**Comment by clement-pannetier** [comment]
@sander1095 
Here is why the 404 page is not rendering : 
https://gohugo.io/templates/404/#automatic-loading
> hugo server will not automatically load your custom 404.html file, but you can test the appearance of your custom “not found” page by navigating your browser to /404.html.

**Comment by sander1095** [comment]
Thanks so much! All cleared up. The only issue I still have is CSS and making it look pretty, but that is not related to this issue ;)
