### ISSUE TITLE
How to disable the multi language support

### ISSUE THREAD

**Issue by tcprks** [luizdepra/hugo-coder#650]
I want to disable the Multilanguage support provided for coder this. I have done with # on config file. Is there any more place i need to make the chnages.

**Comment by luizdepra** [comment]
You need to remove everything related to language from you `config.toml`, such as every section named like `[language.XYZ]`.
Taking the exampleSite config as example, you could remove [all these marked lines](https://github.com/luizdepra/hugo-coder/blob/main/exampleSite/config.toml#L140-L191).
