### ISSUE TITLE
Google analytics support not working

### ISSUE THREAD

**Issue by tcprks** [luizdepra/hugo-coder#653]
I have added the google analytic G id in my config file like this. Also removed the # for 2 fields below to make the feature active.. However it does not pull the data on google analytics dashboard. 
Is there any other config filed in the coder theme, i need to add this to activate the feature.
![image](https://user-images.githubusercontent.com/88808473/155247623-93c199d0-15d0-446e-9c5c-16cd65abe9c5.png)

**Comment by luizdepra** [comment]
It looks like you are trying to use a Google Analytics id with the Google Tag Manager configuration. They are not the same thing.
Hugo has a native integration with Google Analytics. See [here](https://gohugo.io/templates/internal/#configure-google-analytics).
You only need to add `googleAnalytics` in the root section of your `config.toml`.

**Comment by tcprks** [comment]
I added something like this in config toml file , is it fine or any template needs to be added
![image](https://user-images.githubusercontent.com/88808473/155535696-0bee2fec-a78c-4ac2-80eb-0b744cfb081f.png)

**Comment by tcprks** [comment]
I added something like this in config toml
any other chnages required. What is template mentioned there in the above link.
![image](https://user-images.githubusercontent.com/88808473/155535925-070971fb-eab9-4552-a4ce-12e97eb932db.png)

**Comment by luizdepra** [comment]
The template thing is a tag that themes should include to make the GA integration work. Don't worry about that, hugo-coder already uses this template tag.

Just a question. Are you trying to receive data in GA by running your site locally with `hugo server` or something like that? Because I think this will not work. I think GA ignore events that are not coming from the configured domain. You will need to host your site first.

But, I think the real problem is that the `googleAnalytics` is still inside the `[params]` section. Move it to before the `[params]` line, next to `title`, `baseUrl`, `enableEmoji` and others config values.

**Comment by tcprks** [comment]
Even i am buidling site locally I am using the ftp/rsync to make it available internet. to answer to your question site is available over public internet with url. I have moved the google analytics like this now
![image](https://user-images.githubusercontent.com/88808473/155625983-2409e50f-460d-4ad8-9dd0-94adfed5efba.png)

**Comment by luizdepra** [comment]
Could you share the URL? So, I could see if the page is loading the GA script.
If you inspect your page, is any error coming up?

**Comment by tcprks** [comment]
www.rchitect.in is my page

**Comment by luizdepra** [comment]
Here is the problem. Press F12 in your browser and reload the page to see it.
```
Content Security Policy: The page’s settings blocked the loading of a resource at https://www.googletagmanager.com/gtag/js?id=G-7GVZLCM58Y (“script-src”).
```
You could either remove the entire `[params.csp]` section or add `https://www.googletagmanager.com` into `scriptsrc`.

**Comment by tcprks** [comment]
I have done now. Do you think its fine?
![image](https://user-images.githubusercontent.com/88808473/155862868-1c7b047c-488d-41ea-ad67-885a783ba019.png)

**Comment by luizdepra** [comment]
Your config looks right.

About the issues, these are warnings coming from GA script. Everything should work normally.

**Comment by huang06** [comment]
@luizdepra

Thanks to this solution <https://github.com/luizdepra/hugo-coder/issues/653#issuecomment-1051072852>.

I can't see any website data on GA until `adding https://www.googletagmanager.com into scriptsrc`.

Maybe it's good to update CSP templates in both  
<https://github.com/luizdepra/hugo-coder/blob/main/docs/configurations.md#csp>  
and  
<https://github.com/luizdepra/hugo-coder/blob/main/exampleSite/config.toml#L77> ?
