### ISSUE TITLE
Post dates not being translated to default language

### ISSUE THREAD

**Issue by Feggah** [luizdepra/hugo-coder#655]
## What is happening?

I have a `config.toml` configured with:

```
languagecode = "pt-br"
defaultcontentlanguage = "pt-br"
```

And this is working fine for the majority of translations, but when I'm adding new posts, the month string generated from my `date` metadata is in english.

This is my post .md file metadata:
```
+++ 
draft = true
date = 2022-02-25
title = "Visão geral de redes quando uma requisição HTTP é feita entre cliente e servidor"
description = ""
slug = "visao-geral-de-redes-quando-uma-requisicao-http-e-feita-entre-cliente-e-servidor"
authors = ["Gabriel Ferreira"]
tags = ["networking"]
categories = []
externalLink = ""
series = []
+++
```

### Expected
The date should be generated in portuguese, in this example, this should be: `25 de Fevereiro`

### What happened
![image](https://user-images.githubusercontent.com/11353912/155684112-388c4075-a307-45fe-8687-2c3204c74f22.png)

**Comment by luizdepra** [comment]
I just found [this new function](https://gohugo.io/functions/dateformat/).
`time.Format` works fine if you set your lang as `pt` but not with `pt-br`. I'm going to open an Issue in Hugo's repo and ask about it.

Also, I just pushed the changes to use the new function. Update your fork, copy or submodule.
You can use `pt` as a workaround for now. Check for the desired format at the link a mentioned and set the `dateFormat` config properly.
