### ISSUE TITLE
Multilingual page settings does not work when clicking on top menu items.

### ISSUE THREAD

**Issue by harunsasmaz** [luizdepra/hugo-coder#656]
I am using two languages with english as the default language. When I switch to the other language and click on, let's say contact, language switches back to english.

Scenario:

The top menu includes an element Contact.
There are two languages English and Turkish, default is English.
I switch to Turkish.
Then click on "Iletisim" which is Contact in Turkish.

Url is /tr/contact as I defined, however language icon and all contents switch back to english.

in config.toml, I am using:
```
[languages.tr]
languageName = ":tr:"
```
Possible problem can be spot at https://github.com/luizdepra/hugo-coder/blob/680c7ab860e70f29e3eba332dd67f0ba590f88c4/layouts/partials/header.html#L15

**Comment by luizdepra** [comment]
This is a configuration issue. Are you setting an absolute URL on the menu item, a URL starting with `/`? You need to use a relative URL there.

I use this feature in [my blog](https://luizdepra.dev/en/), and it works as intended. I also use a different slug for each language. See my [`config.toml`](https://github.com/luizdepra/luizdepra.dev/blob/main/config.toml) for reference.
