### ISSUE TITLE
How to disable comments on a post?

### ISSUE THREAD

**Issue by mrhappyma** [luizdepra/hugo-coder#658]
Hello! I saw that apparently I can disable comments for a page by "adding the disableComments font-mater". I have this at the top of my post
```
---
title: "test post thing"
draft: false
disableComments: true
---
```

however there is still a comments section. I'm assuming I'm just misunderstanding this, how can I remove comments from a post?

**Comment by luizdepra** [comment]
Are you using utterances comments? There was a typo on the disable attribute. I just fixed it, so update the theme in your project.

**Comment by mrhappyma** [comment]
nice, thanks!

**Comment by piotrek-k** [comment]
Can comments be disabled globally in entire Section without modifying every post in that Section?

**Comment by luizdepra** [comment]
> Can comments be disabled globally in entire Section without modifying every post in that Section?

What do you mean by section? A folder containing multiple MD files?

If so, I don't know. xD
Maybe Hugo provides a way to set a default value for a folder. I would recommend you to ask the same question in the Hugo's Forum. Perhaps there is a something built-in to do that.
