### ISSUE TITLE
Contact page redirect

### ISSUE THREAD

**Issue by tcprks** [luizdepra/hugo-coder#660]
There is contact page ( conatct.md). It displays the email or twitter account. How can i make a redirection to send an email or discord account if someone click on  the contact icon on coder theme.
![image](https://user-images.githubusercontent.com/88808473/155880969-27808fe9-8bbf-4026-9e03-25212d43e732.png)

**Comment by carvalholeo** [comment]
Hello there!

Does it markdown structure to links failing to generate a link for your contact points? What did you try?

**Comment by mrhappyma** [comment]
You can always link to `mailto:youremail@example.com`

if you just want the post to redirect to a url add `externalLink` like so
```md
+++
title = "Contact"
slug = "contact"
externalLink = "https://url.or.mailto.link.here"
```

**Comment by mrhappyma** [comment]
I also noticed you mentioned linking to a Discord account, `discord.com/users/[USER ID]` will open the discord app at the said user. You can get the user ID by following [this guide](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-).
