### ISSUE TITLE
How to update the theme automatically

### ISSUE THREAD

**Issue by tcprks** [luizdepra/hugo-coder#667]
When hugo coder theme provide new update . How does it update automatically on the hugo site which i am building locally.
I am using hugo site and coder theme. I create locally When hugo coder theme provide new update . How does it update automatically on the hugo site which i am building locally.

**Comment by tcprks** [comment]
I build website locally and use rsync to push to webserver , are you suggesting to use "git submodules update --init" before each buidl and rsync command for updating the theme.

**Comment by luizdepra** [comment]
Yup. But this will only work if you're using submodules.
