### ISSUE TITLE
Execution of template failed

### ISSUE THREAD

**Issue by abrahamalen** [luizdepra/hugo-coder#674]
I cloned my repo and try to run `hugo server` and this issue arised @luizdepra 
![image](https://user-images.githubusercontent.com/53680255/164884145-763dd924-288e-432e-b857-c8b303bc7754.png)

**Comment by Shbu** [comment]
It's possible that some of the resources are missing, either due to wrong path, or may be due to Hugo version miss match. Do you want to check this post on the hugo's gitlab page. There seems to be some discussions on the possible resolutions. 

[6128](https://github.com/gohugoio/hugo/issues/6128)

**Comment by abrahamalen** [comment]
> It's possible that some of the resources are missing, either due to wrong path, or may be due to Hugo version miss match. Do you want to check this post on the hugo's gitlab page. There seems to be some discussions on the possible resolutions.
> 
> [6128](https://github.com/gohugoio/hugo/issues/6128)

No.
That was a git submodule issue. I fixed the issue by ruuning these commands 
```
git submodule init
git submodule update
```  

Thanks for the support @Shbu
