### ISSUE TITLE
Timeline Feature

### ISSUE THREAD

**Issue by 13hannes11** [luizdepra/hugo-coder#686]
I created a fork of hugo-coder that is called hugo-coder-timeline. I was wondering if there is interest on adding the features I added to this project?

You can see a demo of the fork [here](https://hanneskuchelmeister.de/) and the repository can be found [here](https://github.com/13hannes11/hugo-coder-timeline).

**Comment by luizdepra** [comment]
I'm glad you want to contribute to the project. Thank you.

This is a feature that has already been requested a few times. But I prefer the homepage as it currently is.

Probably someone would argue that the timeline/post list could be set to be hidden with a configuration option, but this is the kind of functionality I want to avoid. I don't want to make this theme more configuration heavy than it already is. So, if someone would like to modify the homepage, they can do it themselves or use your fork. :smiley:

**Comment by 13hannes11** [comment]
Okay thanks for the reply and I understand that you want to keep it separate to not make it more complex.
