### ISSUE TITLE
Error to navigation menu top right

### ISSUE THREAD

**Issue by Lukas2112** [luizdepra/hugo-coder#689]
### Summary

I wanted to deploy a static website with this theme including the top right navigation bar - the section dealing with this in the config.toml file seems unstable / incorrect to me.

### Steps to reproduce
0. git init homepage 
1. hugo new site . 
2. git submodule add https://github.com/luizdepra/hugo-coder.git themes/hugo-coder
3. cp -R themes/hugo-coder/exampleSite/* . # in homepage root dict 
4. hugo server 

### Expected behaviour

- Error messages are generated in the log (see screenshot). 

### Actual behaviour

- It should run without problems and display the navigation bar in the top right-hand corner.

### Relevant  screenshots

![error-hugo-coder](https://user-images.githubusercontent.com/47597136/174206881-84149f6e-edd5-4f3b-a54b-7e0722995548.png)

**Comment by luizdepra** [comment]
Take a lot at the 3rd line of the image. The WARN line.
It says that you are using an old Hugo's version that is incompatible with the theme. Which version are you using? Try using the newest `extended binary` one.

**Comment by Lukas2112** [comment]
Oh, I should just read more carefully... Sorry, sorry for this inconvenience.

I had used the Hugo version v0.68.3-1 from the official package sources of Ubuntu 20.4.4 LTS. 

Even though I don't like snap, I installed version v0.96.0 via snap - then it works without problems.

**Comment by luizdepra** [comment]
No problem.

You could use a version manager like [asdf](https://asdf-vm.com/) too.
