### ISSUE TITLE
Unable to center text, images and gifs.

### ISSUE THREAD

**Issue by jonasskanoy** [luizdepra/hugo-coder#695]
I am having trouble centering both text, image and gifs in my markdown files. I am new to hugo and have tried some different solution purposed on the hugo forum:

1. https://discourse.gohugo.io/t/how-to-set-image-center/20103/2
2. https://discourse.gohugo.io/t/how-to-center-text/22070

Is there a way to this by default in this theme?

**Comment by luizdepra** [comment]
Sadly, no, there isn't.

What I'm doing is using the [figure shortcode](https://gohugo.io/content-management/shortcodes/#figure) with a custom CSS class. See [here](https://github.com/luizdepra/luizdepra.dev/blob/main/content/about.en.md?plain=1#L7) and [here](https://github.com/luizdepra/luizdepra.dev/blob/main/assets/css/custom.css#L1-L10).

For text alignment, I would go with a custom shortcode.

**Comment by jonasskanoy** [comment]
Sweet, that worked! Thank you.

**Comment by jonasskanoy** [comment]
Can you do the same for markdown tables?

**Comment by luizdepra** [comment]
Yep. It is feasible.
Or you could just override [this rules](https://github.com/luizdepra/hugo-coder/blob/main/assets/scss/_base.scss#L178-L208) on a custom (S)CSS file.
