### ISSUE TITLE
How to change font?

### ISSUE THREAD

**Issue by fevermonk** [luizdepra/hugo-coder#696]
I want to change font for my site using this theme,
[Here](https://github.com/fevermonk/bug) is link to my repo.

I have checked [this issue](https://github.com/luizdepra/hugo-coder/issues/61) and [this issue](https://github.com/luizdepra/hugo-coder/pull/77)

and created a `_variables.scss` under assets/scss folder, like [this](https://github.com/luizdepra/luizdepra.dev/blob/5aacaf70c082c8f3ce8c79ab767e8d857f710346/assets/scss/_variables.scss)

and also, I am confirmed using extended version of hugo,
`hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio`

And I have this in config.toml

```toml
customCSS = []
customSCSS = ["scss/_variables.scss"]
customJS = []
```

And I am yet getting this error -

```bash
Start building sites … 
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
ERROR 2022/07/06 23:59:12 TOCSS: failed to transform "style.coder-dark.css" (text/x-scss): "/home/chandan/blog/themes/hugo-coder/assets/scss/_base_dark.scss:2:10": Undefined variable: "$fg-color-dark".
Error: Error building site: TOCSS: failed to transform "style.coder.css" (text/x-scss): "/home/chandan/blog/themes/hugo-coder/assets/scss/_base.scss:15:16": Undefined variable: "$font-family".
Built in 126 ms
```

**Comment by luizdepra** [comment]
Hey!

It looks like Hugo's Asset Pipeline couldn't find some variables.

Try redefining all variables from the original file. [See here](https://github.com/luizdepra/hugo-coder/blob/main/assets/scss/_variables.scss). Hugo will complete override the entire file, so you need to redefine everything. Also, you don't need to add this file in the `customSCSS`. Use this feature only when you do not want to override a theme file.

(I think my site is misconfigured and using an outdated version of this theme. It should have broke with an error like yours, but it didn't, and I don't know why. I'm going to check it later.)

**Comment by fevermonk** [comment]
Hello,

Thank you @luizdepra 
Following your advice it's working now.

Notes for any random person reading this issue -

If you want to change font, you have to create a file under assets/scss/_variables.scss,
And you have to have exactly all the variables defined as in the original file in the theme, and mention your desired font in now created _variables.scss file.
(It overrides not inherits)
Also, as @luizdepra mentioned you don't need to have _variables.scss added to customSCSS .

Thanks again @luizdepra , for creating this amazing theme!
