### ISSUE TITLE
Disable minifying for a file?

### ISSUE THREAD

**Issue by mrhappyma** [luizdepra/hugo-coder#698]
Hello!
I am using the customJs thing it looks like my script is being... minifyed? I'm defenetially spelling things wrong or using made up words. 
Is there a way to disable this?

**Comment by luizdepra** [comment]
It is not possible without customizing [these lines](https://github.com/luizdepra/hugo-coder/blob/abc1133c7e077d484e4c97f75cee8460a3004397/layouts/_default/baseof.html#L32-L40).

But, I'm curious. Why minifying is a problem?

**Comment by mrhappyma** [comment]
I'm not sure if it is necessarily the problem, but a script from [blockadblock.com](blockadblock.com) is not functioning properly. [The FAQ](https://blockadblock.com/adblocking/frequently-asked-questions) recommends not to minify the script.
