### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by djraval** [luizdepra/hugo-coder#7]
How can i generate "Project" pages simillar to "Blog" pages?
I want them to be exactly same as Blog posts in terms of frontmatter and listing.
Can you briefly guide on how to do it?

**Comment by djraval** [comment]
Here's my repo link [https://github.com/djraval/djraval.git](url) and the Website [djraval.netlify.com](url)

**Comment by luizdepra** [comment]
Hey!
You just need to create a 'projects' folder in your `content` folder, and puts your projects pages inside. The command `hugo new projects/project-name.md` should work to.

Then, you can see the projects at `your-site.com/projects/`.

**Comment by djraval** [comment]
Just got it working by how you described, thanks.
