### ISSUE TITLE
How to change /posts page title?

### ISSUE THREAD

**Issue by vitalyavolyn** [luizdepra/hugo-coder#70]
Hi! How can i change Title "Posts" on /posts page? I want to translate it into my native language.

Also, can i make dates on same page look like DD.MM.YYYY? Thanks.

**Comment by vitalyavolyn** [comment]
Just found out that i can override partials by copying them in layouts/partials/ 
I guess i need to do it this way, right?

**Comment by luizdepra** [comment]
Yep. It should work this way.
You will need to do same with the date, I think. I don't remember if it is possible to override the date format with configuration.

**Comment by vitalyavolyn** [comment]
I was able to change date format, thanks. But heading? 

layouts/partials/list.html
```html
<h1 class="title">{{ .Title }}</h1>
```

Where does `.Title` come from?

**Comment by luizdepra** [comment]
It comes from the archetype `posts`.

To accomplish that probably you need to put all your post inside a folder with the desired name.
Maybe, you will need make a copy of the post related files with the desired name too.

**Comment by vitalyavolyn** [comment]
Thanks for your help!

**Comment by kshitij10496** [comment]
An alternate way to just capitalize the heading from "Posts" to "POSTS" would be to create a `_index.md` file within the `content/posts` directory using `hugo new posts/_index.md`.
We can now manually edit the `title` page variable as we like.
