### ISSUE TITLE
How to show posts with date beyond today?

### ISSUE THREAD

**Issue by KaiyangZhou** [luizdepra/hugo-coder#706]
Hi, great project!

I'm wondering if it is possible to display posts (like these at https://hugo-coder.netlify.app/posts/) with dates beyond today. For example, if I create a post using `hugo new posts/post.md` and change the date in `post.md` to 01-03-2030 (which is far beyond today's date), the post won't appear in the posts page. If the date is `01-03-2020`, then it will be displayed without a problem.

**Comment by luizdepra** [comment]
Thanks.

Yes, there are `-F` or `--buildFuture` flags to do that.
See [here](https://gohugo.io/getting-started/usage/).

**Comment by KaiyangZhou** [comment]
Nice. Thank you!
