### ISSUE TITLE
Opacity percentages not supported in all browsers

### ISSUE THREAD

**Issue by simonhollingshead** [luizdepra/hugo-coder#707]
https://developer.mozilla.org/en-US/docs/Web/CSS/opacity#browser_compatibility
https://caniuse.com/mdn-css_properties_opacity_percentages

Please consider using decimal opacity values.  I see at least three instances of percentage opacity values in _float.scss.  I would make the PR myself but I'm not sure what the build pipeline is for SCSS changes.

**Comment by luizdepra** [comment]
Sure. It is quite simple to build the SCSS files. Just make your changes and run `make release`, then open the PR.
Let me know if you want to try and open a PR. :)
