### ISSUE TITLE
3762d3a is breaking title generation

### ISSUE THREAD

**Issue by truemped** [luizdepra/hugo-coder#708]
Hi, reporting an issue for now and trying to dig deeper to fix it.

Since commit 3762d3a the title is not generated correctly anymore. Instead of rendering the page title followed by the blog title, only the blog title is getting rendered.

/cc @fj

**Comment by truemped** [comment]
Steps to reproduce:

1. `git checkout 3762d3a~1`
2. `cd exampleSite`
3. `hugo --themesDir ../../ --cleanDestinationDir`

All pages in the example site have the pattern "{{ .Title }} · {{ .Site.Title }}". Doing the same with revision 3762d3a will result in the title pattern "{{ .Site.Title }}".

**Comment by truemped** [comment]
As soon as I move the contents of `{{ partial "head.html" . }}` back into `layouts/_default/baseof.html` it seems to work again. Tried some googling and could not find anything too related. Code search on Github did not reveal widespread usage of this.

I have a feeling template blocks inside partials are not supported?! I'll create a PR to "fix" this in a least intrusive way. Let me know what you think.

**Comment by fj** [comment]
Thanks for the heads up. I think this may be an error in Hugo; the documentation seems to suggest that blocks should be supported this way, but a quick review of the top 10 themes shows that none of them do this so it's possible this is the first time that's ever been actually tested.

In the meantime, I have an alternate fix here that does this and also fixes an additional error: https://github.com/luizdepra/hugo-coder/pull/710

**Comment by truemped** [comment]
Yeah, I don't care what will be merged! Just want the titles back :). Let's merge yours as soon as possible!

**Comment by fj** [comment]
Update: I did find this old (~5y ago) thread from ***@***.***` suggesting that
blocks aren't supported in partials:

https://github.com/gohugoio/hugo/issues/4121#issuecomment-347011315

best,
~ jf
--
*John Feminella*
🐦 *Twitter:* @jxxf <https://twitter.com/jxxf>
👨‍💻 *profile:* https://linkedin.com/in/johnxf
📅 *book a meeting:* https://savvycal.com/jxf/
<https://savvycal.com/jxf/virtual-chat>
