### ISSUE TITLE
getting "resources" not defined error 

### ISSUE THREAD

**Issue by chrishna1** [luizdepra/hugo-coder#71]
ERROR: 2018/08/26 15:26:29 template.go:350: template: theme/_default/baseof.html:23: function "resources" not defined
ERROR: 2018/08/26 15:26:29 template.go:350: template: theme/partials/header.html:3: function "absLangURL" not defined
ERROR: 2018/08/26 15:26:29 template.go:350: template: theme/partials/post.html:38: function "default" not defined
0 draft content
0 future content
0 pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
in 122 ms
Watching for changes in /home/insol/balkrishnajha.github.io/{data,content,layouts,static,themes}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

Change detected, rebuilding site
2018-08-26 16:12 +0530
Template changed /home/insol/balkrishnajha.github.io/themes/hugo-coder/layouts/_default/baseof.html
ERROR: 2018/08/26 16:12:32 template.go:350: template: theme/partials/header.html:3: function "absLangURL" not defined
ERROR: 2018/08/26 16:12:32 template.go:350: template: theme/partials/post.html:38: function "default" not defined
0 draft content
0 future content
0 pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
in 670 ms
^C  

I'm new to Hugo. I've tried a few others themes , they also give similar error. Can anyone please help.

**Comment by luizdepra** [comment]
Which version of Hugo are you using?
Coder needs v0.43 Extended (meaning, w/ Asset Pipeline support) or later.

**Comment by chrishna1** [comment]
Thank You very much @luizdepra 
That was the problem. I was using 0.16 version lol. 
This was my last time using sudo apt-get install. It always gives me headache.
Once again thank you.

**Comment by khos2ow** [comment]
@chrishna1 you can give [hugo-wrapper](https://github.com/khos2ow/hugo-wrapper) a try.
@luizdepra what do you think to add this in the `exampleSite` or event the whole repo too?
