### ISSUE TITLE
hugo-coder breaks Web Content Accessibility Guidelines for links

### ISSUE THREAD

**Issue by simonhollingshead** [luizdepra/hugo-coder#712]
Currently, hugo-coder breaks Web Content Accessibility Guidelines by having two instances of links with no readable content inside them.  They are the links that produce the heading URLs in render-heading.html and series.html.

This breaks https://www.w3.org/TR/WCAG-TECHS/F89.html

There is a fix for this provided by Font Awesome (and forkawesome) which I will propose in a PR.

**Comment by luizdepra** [comment]
Hey, thanks for contributing.
Accessibility is very important, and I really want to make hugo-coder more accessible. :)

**Comment by luizdepra** [comment]
I just merged #713. So, closing this one.
