### ISSUE TITLE
Disqus renders horribly

### ISSUE THREAD

**Issue by kalpik** [luizdepra/hugo-coder#722]
Hello!

I tried enabling Disqus, and it renders horribly. The Disqus theme is set to "auto".

<img width="694" alt="image" src="https://user-images.githubusercontent.com/481869/193040732-52edbeff-5f8a-4379-9264-7d3291fcdfa4.png">

Any pointers?

Thanks

**Comment by luizdepra** [comment]
Hey!

Disqus should pick the correct color scheme automatically. See [here](https://help.disqus.com/en/articles/1717201-disqus-appearance-customizations). They say:

```
How is the color scheme determined?

- The light scheme is loaded when the text color Disqus inherits from your site has >= 50% gray contrast: between color: #000000; and color: #787878;
- The dark scheme is loaded in all other instances. 
```

Maybe something has changed in their side. Perhaps now they are using `prefers-color-scheme`.
However, you could change Disqus styling by overriding their CSS rules.

**Comment by xiaotianxt** [comment]
I'm having the same issue, it seems that the background color of the discus board is on light mode, but the text are on dark mode.

**Comment by luizdepra** [comment]
@xiaotianxt this could be caused by a CSS rule conflict, maybe with a common class.

**Comment by xiaotianxt** [comment]
> @xiaotianxt this could be caused by a CSS rule conflict, maybe with a common class.

I've fixed it, I will present you a PR soon.
