### ISSUE TITLE
How to make the list in "post" left-aligned instead of center-aligned

### ISSUE THREAD

**Issue by KaiyangZhou** [luizdepra/hugo-coder#723]
Hi, I'm wondering if it is possible to make the list in a "post" page left-aligned instead of center-aligned? For instance, in https://theaitalks.org/talks/, I'd like to make the centered list left-aligned (i.e., the dates and titles are moved to the left). Please share some hints on how to do that. Thanks :-)

**Comment by luizdepra** [comment]
Hi!

You can do it by removing or overriding [this styling rules](https://github.com/luizdepra/hugo-coder/blob/main/assets/scss/_content.scss#L152-L159).

**Comment by KaiyangZhou** [comment]
great! thx
