### ISSUE TITLE
please add an option to make the avatar image bigger and remove the circle cutout

### ISSUE THREAD

**Issue by linuzzx** [luizdepra/hugo-coder#724]

**Comment by luizdepra** [comment]
Hey!

You could simply override or change the values from the [avatar styling rules](https://github.com/luizdepra/hugo-coder/blob/main/assets/scss/_content.scss#L101-L109).

**Comment by shaked8634** [comment]
I'm unable to override the .css.
When I changed the theme's [_contents.scss](https://github.com/luizdepra/hugo-coder/blob/41da7db7015a7d84ab15b74fae9db9c5dd8f27fd/assets/scss/_content.scss#L104) file it works but copying and changing the file in _<site>/assets/scss/__content.scss_.

Is this the right location?

**Comment by luizdepra** [comment]
It will depend on how you are importing the theme into your project and where are the files.
I'll assume you added this theme as a submodule at `themes/coder`. So, you will need to add a `assets` folder in the root of your project. The file will need to be at `assets/scss/_content.scss`.

Another thing, are you using the extended version of Hugo? Only this version can build SCSS files.

And, there is another option. You can simply add a custom CSS file, with the config `customCSS`, overriding the desired CSS classes.

**Comment by shaked8634** [comment]
Many thanks. Overriding in `assets/scss/_content.scss` solved it for me.
