### ISSUE TITLE
How can I add Strava to social media platforms?

### ISSUE THREAD

**Issue by gvu0110** [luizdepra/hugo-coder#742]
I'm using the following configuration for my Strava, but the Strava icon is not showing.
```
[[params.social]]
name = "Strava"
icon = "fa fa-2x fa-strava"
weight = 5
url = "https://example.com"
```
How can I make this work?

**Comment by luizdepra** [comment]
Hey.

We are using Fork Awesome fonts, and it seems they don't have the Strava icon.
You could manually add new icons from other icon packs, or even replace Fork Awesome with other packs.

**Comment by gvu0110** [comment]
Thank you 👍

**Comment by maxkratz** [comment]
> You could manually add new icons from other icon packs

@luizdepra how can this be done?

**Comment by luizdepra** [comment]
@maxkratz it depends on how the icon you want to use should be included. If it is something like fork|font-awesome, that you have a CSS file to link to, you just need to add it to the header section by overriding its template. Or, if the CSS file doesn't have any dependencies, you could the `customCSS` configuration.

I think I helped someone with something like this problem in the past here. I don't know.
