### ISSUE TITLE
Add giscus as an alternative to utterances

### ISSUE THREAD

**Issue by jankatins** [luizdepra/hugo-coder#747]
## Describe the enhancement

[Giscus](https://giscus.app/) uses github discussion to handle comments, is open source and you can self host the app. It looks like a nice addition as a comment system and a nice alternative to [utterances](https://github.com/utterance/utterances) which uses github issues to handle comments. Using github discussions has the advantage of allowing threads.

I can probably implement the change, if this looks interesting.

**Comment by nourkagha** [comment]
I was thinking about this recently. Would be a much nicer addition compared to utterances.

**Comment by luizdepra** [comment]
Sure. This is nice to have.

I'm kind of busy with other projects right now, but I can take a look.
Meanwhile, someone could try and add this feature.

**Comment by nourkagha** [comment]
I've looked into it before and considered opening a PR and can look into it again when I have some time, unless @jankatins or anyone wants to go for it before then.

Implementation is mostly similar to utterances and there are some new variables.

**Comment by jankatins** [comment]
@nourkagha please go for it, I'm unsure when i have time... :⁠-⁠\

**Comment by jankatins** [comment]
Woohoo, thank you, @nourkagha and @luizdepra !
