### ISSUE TITLE
Getting an error when attempting to deploy my site

### ISSUE THREAD

**Issue by pboling** [luizdepra/hugo-coder#75]
I am using `hugo_0.48_Linux-64bit.deb`
```
remote: Building sites … ERROR 2018/09/04 05:33:39 error: failed to transform resource: TOCSS: failed to transform "style.coder.css" (text/x-scss): this feature is not available in your current Hugo version
remote: Total in 29 ms
remote: Error: Error building site: logged 1 error(s)
```

Is this theme no longer compatible with current hugo?

**Comment by pboling** [comment]
Oh, it seems that I require an npm package to run the transform, and as I am deploying to a shared host where I can't (easily) install npm, I think I am stuck.

**Comment by luizdepra** [comment]
Nope.
This theme uses the Asset Pipeline that is available only in the extended versions of Hugo.
For v0.48, use this one [`hugo_extended_0.48_Linux-64bit.deb`](https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_extended_0.48_Linux-64bit.deb).

**Comment by pboling** [comment]
Oh, thanks!  I'll try that out.

**Comment by pboling** [comment]
I was able to install the `.deb`, but I can't run `hugo` extended.  Hosting provider is Dreamhost, by the way.
```
remote: /home/pbolingdev/root/usr/local/bin/hugo: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/pbolingdev/root/usr/local/bin/hugo)
remote: /home/pbolingdev/root/usr/local/bin/hugo: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pbolingdev/root/usr/local/bin/hugo)
```
Looks like I will have to try something else.

**Comment by luizdepra** [comment]
Well, I think you have 2 options.
1) Install Hugo Extended dependencies in your host.
2) Generate your site in your local machine with Hugo Extended, and commit/save the `resources` folder (which contains all generated CSS files). In other words, if already have all generated CSS files within your project, you can use the default Hugo version to build it.

**Comment by khos2ow** [comment]
@pboling 1. you can use the hugo-wrapper instead of actually installing/downloading the Hugo binary (https://github.com/khos2ow/hugo-wrapper)

2. If it's your hosting provider and you have the control to install `deb` package on it then it's only the matter of installing correct `glibc` library on that machine.

3. Since this is hosting provider, I would suggest you don't need hugo at all, it's better you have a CI of some sort, and generate your site and push/deploy to the hosting provider (which can have only nginx)

**Comment by pboling** [comment]
I can do local .deb installs, but not for things like node, npm, or glibc.  Dreamhost is selective there, and you can get banned from shared hosting if you are naughty.
I will try the resources option, but I am also having trouble getting hugo to actually build the whole site.  It only builds files I've touched, so I have to go through and touch every post (so many!) in order for them to get built.
I must be missing something, because there is no way a toll like that is useful...  Also, not your problem, so thanks for the help!

**Comment by luizdepra** [comment]
Have you tried to use Netlify to host your site?
I'm using it.  It is quite simple and free for static sites.

**Comment by pboling** [comment]
No, I'll give it a look.

**Comment by khos2ow** [comment]
Although with Netlify you will still have the issue of missing `glibc` library and you will need to check in `resources` folder. But other than that it's a really cool service.
