### ISSUE TITLE
How to add strava icon?

### ISSUE THREAD

**Issue by vvrnv** [luizdepra/hugo-coder#778]
How to add Strava icon?
I know that fork-awesome doesn't have strava icon.
Tried to add css/scss font-awesome files to my repo, but after saving getting a error:
```
ERROR 2023/02/27 14:44:37 Rebuild failed: failed to render pages: render of "home" failed: "/Users/voronov2/github/vvrnv.github.io/themes/hugo-coder/layouts/_default/baseof.html:5:7": execute of template failed at <partial "head.html" .>: error calling partial: "/Users/voronov2/github/vvrnv.github.io/themes/hugo-coder/layouts/partials/head.html:11:3": execute of template failed at <partialCached "head/custom-styles.html" .>: error calling partialCached: "/Users/voronov2/github/vvrnv.github.io/themes/hugo-coder/layouts/partials/head/custom-styles.html:15:36": execute of template failed at <toCSS $cssOpts>: error calling toCSS: no Resource provided in transformation
```

also checked this issues https://github.com/luizdepra/hugo-coder/issues/259, https://github.com/luizdepra/hugo-coder/pull/158, but still can't add a custom icon.

**Comment by luizdepra** [comment]
Do you have an open repository that I could take a look?
But, I suspect that you are putting your custom (S)CSS file in the wrong place. Are you putting them inside the `assets` folder? See how I do [here ](https://github.com/luizdepra/luizdepra.dev/tree/main/assets/css) and [here](https://github.com/luizdepra/luizdepra.dev/blob/main/config.toml#L36).

**Comment by vvrnv** [comment]
https://github.com/vvrnv/vvrnv.github.io

thanks for the answer, I'll try the solution from your repository

**Comment by luizdepra** [comment]
Heym @vvrnv.

I think I solved your problem.

1. Move the `fonts` and `css` folders from inside `assets` to `static`. We only put a file inside `assets` if we want Hugo to pre-process it with the Assets Pipeline. It is not the case here.
2. You should delete the `scss` folder. You don't need them because you already have the final CSS ones.
3. Change your `config.toml` to have the following `customCSS` value. I added the `brands` CSS file because the brand icon font is loaded inside it. I used the minified version, but you could use the normal ones too.

```
customCSS = ["css/brands.min.css", "css/fontawesome.min.css"]
```

**Comment by vvrnv** [comment]
Moved fonts and css to statis — doesn't work.
Keep inside assets, config changed: _added customCSS = ["css/brands.min.css", "css/fontawesome.min.css"]_ and change icons to _icon = "fab fa-foo fa-2x"_
Thanks!

**Comment by vvrnv** [comment]
Strange things are happening.
If I follow [the example above](https://github.com/luizdepra/hugo-coder/issues/778#issuecomment-1461468862), then the icons are not rendered
![Screenshot 2023-03-09 at 10 44 27](https://user-images.githubusercontent.com/40491079/223954315-99269375-4fdc-49a8-8f62-cabe2a138487.png)

If i move css and fonts to static/ folder, getting error and move css and fonts to assets again, changed to fab fa-foo fa-2x — it works.

**Comment by luizdepra** [comment]
Sorry, I was wrong about moving the CSS files to `static` folder. You only need to move the `fonts`.
I forked your project and just submitted a PR with the working configuration. See if it works. I'm using `hugo v0.102.3-extended`. You must use the extended version when using the Assets Pipeline, so be sure you have it.

**Comment by vvrnv** [comment]
hell yeah! thanks!

**Comment by Olshansk** [comment]
@luizdepra If I were to put together a PR showing `how to add strava` in some sort of "example" or "FAQ" like-fashion, would you be open to reviewing it?

I had this exact same question and fortunate enough to have found it in previous issues.

**Comment by luizdepra** [comment]
> @luizdepra If I were to put together a PR showing `how to add strava` in some sort of "example" or "FAQ" like-fashion, would you be open to reviewing it?
> 
> I had this exact same question and fortunate enough to have found it in previous issues.

Sure, no problem.

We could starting using [the faq file](https://github.com/luizdepra/hugo-coder/blob/main/docs/faq.md) to do things like that.
