### ISSUE TITLE
Is `{{% note %}}` admonition supported?

### ISSUE THREAD

**Issue by dharmit** [luizdepra/hugo-coder#786]
## Your question

When I try to use the [`{{% note %}}` admonition](https://gohugo.io/contribute/documentation/#note-admonition), `hugo server -D` fails with:

```shell
$ hugo server -D
Start building sites …
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
Error: Error building site: "/path/to/post.md:31:1": failed to extract shortcode: template for shortcode "note" not found
Built in 15 ms
```

**Comment by luizdepra** [comment]
Yes, we have. See [here](https://github.com/luizdepra/hugo-coder/blob/main/exampleSite/content/posts/more-rich-content.pt-br.md?plain=1).

I think the `note` short code you're trying to use is only available in Hugo's Documentation theme.

**Comment by dharmit** [comment]
Thanks for pointing that. The link I returned was the first result I got when searching the Hugo docs from the site itself as well as search engine. 😕
