### ISSUE TITLE
Site icon working in local but not on production

### ISSUE THREAD

**Issue by siddharth1729** [luizdepra/hugo-coder#797]
## Your question

_Ask the question you have not been able to find an answer in the Documentation_
Mt hugo site icon is working on local but not on production 
base url - https://thelegion.tech/

**Comment by luizdepra** [comment]
Is it a roman soldier's helmet? If so, it is working fine for me.
Maybe it is your browser's cache.

![Screenshot from 2023-04-13 10-03-05](https://user-images.githubusercontent.com/1427376/231767624-ae6ef94c-11f2-40cc-b1d1-d7c76e819e54.png)

![Screenshot from 2023-04-13 10-03-22](https://user-images.githubusercontent.com/1427376/231767649-09d2e1ce-f9d3-4b16-a0fe-35178d16db77.png)

![Screenshot from 2023-04-13 10-03-34](https://user-images.githubusercontent.com/1427376/231767661-5d0157a7-c08f-4e04-a9aa-d2597bc28a22.png)

**Comment by siddharth1729** [comment]
yeah very thank you
