### ISSUE TITLE
Posts with `type` in front matter do not render in posts list

### ISSUE THREAD

**Issue by leonroy** [luizdepra/hugo-coder#800]
## Describe the problem:

Navigating to `/posts` shows no posts at all when a post has a `type` value set:
<img width="940" alt="image" src="https://user-images.githubusercontent.com/325602/232921868-2478eb5e-c245-4d0b-8412-3697a9207f48.png">

Example of such a post:

Path: `my-hugo-site/content/posts/2009/2009-05-07-hello-world/2009-05-07-hello-world.md`

Content of file:

```
---
title: Hello world!
author: leonroy
type: post
date: 2009-05-07T19:54:06+00:00
url: /2009/05/hello-world/
featured_image: /posts/2009/2009-05-07-hello-world/DSCN1436_s.jpg
categories:
  - General

---
Lorem ipsum...
```

### Steps to reproduce:

1. Install coder theme
2. Add content under `my-hugo-site/content/posts/2009/2009-05-07-hello-world/2009-05-07-hello-world.md`
3. Add `type: post` to front matter

### Observed Results:

-   What happened?

Page does not appear in `/posts`

-   What did you expect to happen?

Page to appear in `/posts`

### Relevant code exceptions or logs

Issue in code appears to be related to this file:
https://github.com/luizdepra/hugo-coder/blob/main/layouts/posts/list.html#L16

Something to do with the `.Render` method. If I replace the line above with the contents of `li.html` then all posts display:
<img width="925" alt="image" src="https://user-images.githubusercontent.com/325602/232922667-ef572db8-1fb5-499b-91c7-30b29334de18.png">

**Comment by luizdepra** [comment]
Hey.

This is happening because the correct archetype name is `posts`.
Moreover, you shouldn't need to specify the type on the front matter. Hugo will get the archetype from the page root folder, which is `posts` in this case.

**Comment by leonroy** [comment]
my bad - changing them to `posts` did indeed resolve the issue but yep, I can also remove the values too

thanks for the assist and for the excellent theme 🙏
