### ISSUE TITLE
Background color of single line code section is hard to differentiate

### ISSUE THREAD

**Issue by aeb-dev** [luizdepra/hugo-coder#806]
## Describe the problem:

Background color of single line code section(\`\`) is hard to differentiate

### Steps to reproduce:

1. Go to https://hugo-coder.netlify.app/posts/math-typesetting/
2. There are multiple single line code sections like `math: true` but it is hard to see

Note: Please copy/paste text of the messages, no screenshots of logs please.
light mode:
![image](https://user-images.githubusercontent.com/11612804/236677562-2dc6b8ca-5043-4ea9-9f87-f7cdee0ffabb.png)

dark mode:
![image](https://user-images.githubusercontent.com/11612804/236677577-5b9c4dd2-a4ff-4138-b417-faa54ef628d6.png)

Tried multiple browsers aswell(firefox, chrome)

**Comment by aeb-dev** [comment]
Is there anything I can help you with this issue?

**Comment by luizdepra** [comment]
Hey. Something should have broken the styling for the inline code.
I think it will be easy to fix, but I'm busy right now. Maybe, I will have a bit of time to resolve that problem this weekend.

Meanwhile, if someone is willing to help, please you are welcome.

**Comment by aeb-dev** [comment]
I would like to help but I am not sure I can because I have no experience with styling :) If you can direct me to a file maybe I can find my way from there
