### ISSUE TITLE
How can I change favicon?

### ISSUE THREAD

**Issue by astrokk** [luizdepra/hugo-coder#814]
I have changed the images in "/static/images" and I'm trying to add favicon_16 = "/img/favicon-16x16.png", favicon_32 = "/img/favicon-32x32.png" to config.toml, but It isn't working.

**Comment by quanghieu31** [comment]
favicon format should have the extension ".ico". I think the first thing you should do is to convert your image (png) to (ico). Then place your favicon.ico file to the directory: your-site-dir/public/images/favico.ico. At the same time, in your config.toml file, under [params], put this command: favicon_32 = "images/favicon.ico". The favicon will appear when you publish the website online.

Let us know if it works for you

**Comment by astrokk** [comment]
That worked! Thank you very much!
