### ISSUE TITLE
The problem with displaying the section used in series.html (archetypes series in posts.md)

### ISSUE THREAD

**Issue by ponfertato** [luizdepra/hugo-coder#818]
## Describe the problem:

_When creating archetypes for posts, they are not displayed in languages other than English (maybe not all)_

### Steps to reproduce:

1. Create a file _example.md_ and _example.ru.md_
2. Add the archetype **series** in different languages
3. Now you will have a different footer section in your post in different languages

### Observed Results:

-  There is an empty section in the footer section `<section class="see-also"></section>`

### Relevant code exceptions or logs

```markdown
series = [
    "Tips and tricks for working with submodules",
]
```

```markdown
series = [
    "Советы и рекомендации по работе с подмодулями",
]
```

**Comment by luizdepra** [comment]
Hey.

I see that there is a situation like this one in this theme demo. But, in that case, it is not a bug. See [this page](https://hugo-coder.netlify.app/posts/markdown-syntax/).
There is [a rule](https://github.com/luizdepra/hugo-coder/blob/main/layouts/partials/posts/series.html#L7) to not display the 'See also' content when the series has only one page. In `en` there are two, but in `pt-br` there is only one. So, the section content is not displayed in `pt-br`. But, the section tag is included either way, and this could be fixed.

Check if this is your case. Maybe there is a minor difference in the section name or something like that.
