### ISSUE TITLE
SVG favicon config option

### ISSUE THREAD

**Issue by Baa14453** [luizdepra/hugo-coder#819]
## Describe the enhancement

I know we can specify 16x16 and 32x16 favicon sizes, but it looks like there's a [new standard in town](https://stackoverflow.com/a/48646940/6530181). Supported by all browsers [except Safari](https://caniuse.com/?search=svg%20favicon), specify a path to one svg file and it will handle all resizing.

Simply, a config option to specify the path to the SVG file, inserting the following onto the site:
`<link rel="icon" href="<path to favicon>" type="image/svg+xml" sizes="any">`

Please and thank you :heart:

**Comment by luizdepra** [comment]
Done! #822
Ty. :)
