### ISSUE TITLE
Theme Demo on Hugo Themes Site is missing its assets.

### ISSUE THREAD

**Issue by onedrawingperday** [luizdepra/hugo-coder#82]
Please review the Hugo Theme's updated [README Common Permalink Issues](https://github.com/gohugoio/hugoThemes#common-permalink-issues) because your demo is affected.

You need to use `.RelPermalink` for Hugo Pipes Assets.

---

CC / @digitalcraftsman

**Comment by luizdepra** [comment]
Fixed.
