### ISSUE TITLE
Enabling code block line numbers creates a styling issue.

### ISSUE THREAD

**Issue by Baa14453** [luizdepra/hugo-coder#820]
## Describe the problem:

_Explain the problem you have encountered_

### Steps to reproduce:

1. Add [`linenos = true`](https://gohugo.io/content-management/syntax-highlighting/) under the `markup.highlight` section in `hugo.toml`
2. Create a multi-line codeblock and specify a language type:

\```rust
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
meowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeowmeow
\```

4. Observe it escaping the codeblock border:
![image](https://github.com/luizdepra/hugo-coder/assets/9057997/191714ab-9c5c-4f11-8076-97583bbebfdf)

### Observed Results:

-  The codeblock escaped the codeblock border.
-  The border to extend to contain the code.

**Comment by luizdepra** [comment]
Hmm. It seems a problem with width when the pre/code tags are inside a table.

I'm busy with work recently, so if anyone is interested in with this issue, feel free to send a PR.

Also, I think #821 somewhat related.

**Comment by pduchnovsky** [comment]
Just to let you know, this PR 'breaks' normal paragraphs somewhat (at least on my page)

The reason is, that there is following added to the whole paragraph section `p {}`, rather than just adding it to code block
```
  white-space: pre-wrap;
  white-space: -moz-pre-wrap;
  white-space: -pre-wrap;
  white-space: -o-pre-wrap;
```

To fix it I had to overwrite this like:

```
p {
    white-space: inherit !important;
}
```

I think the PR creator only wanted this to be reflected for code blocks, so this piece of code should probably be moved there.

**Comment by cep21** [comment]
@pduchnovsky Thanks!  I ran into the same bug.
