### ISSUE TITLE
How to make post page in MD in the format of the example site and how to link to posts?

### ISSUE THREAD

**Issue by forrestywang** [luizdepra/hugo-coder#824]
I was looking through the files for the example site, but I couldn't find a `posts.md` file nor documentation for how create the table below.

Could someone provide documentation for how to create the `posts.md` file and make the table?

<img width="340" alt="image" src="https://github.com/luizdepra/hugo-coder/assets/95055762/93144e98-8eea-43cd-898d-0470fbc4e1e6">

***

Original posts page:

<img width="1120" alt="image" src="https://github.com/luizdepra/hugo-coder/assets/95055762/b87d44e4-62f1-443b-94fc-c4c981cb3009">

**Comment by tbx1b** [comment]
That page is automatically generated when you have posts. It takes the title and date of your blog post .md file, and displays it there.

In the[example site](https://github.com/luizdepra/hugo-coder/tree/main/exampleSite) configuration, you can see this. In the "content" folder, there is a "posts" folder, which contains the actual post .md files.

If you don't have any posts, it returns a 404.

**Comment by forrestywang** [comment]
Great, I fixed the issue.

Thanks! ❤️
