### ISSUE TITLE
Reopened Issue with UTF-8 character handling in 'see_also' feature

### ISSUE THREAD

**Issue by andgar2010** [luizdepra/hugo-coder#829]
Hello @luizdepra,

Despite changing from urlize to anchorize, the "see_also" functionality in Hugo is still disrupted by the use of Spanish characters (e.g., "lenguaje-de-programación"). Replacing these with their English counterparts works, but this isn't a long-term solution.

Attached are screenshots showing the issue.

![image](https://github.com/luizdepra/hugo-coder/assets/19521054/7bbad5e8-f020-4c3e-a12a-ecc8ddd2795b)

![image](https://github.com/luizdepra/hugo-coder/assets/19521054/b6babdeb-4698-42a5-9eb3-9e9b43a84e2b)

I would appreciate any further guidance or bug fix updates.

Thank you.

Best,

_Originally posted by @andgar2010 in https://github.com/luizdepra/hugo-coder/issues/823#issuecomment-1633007701_

**Comment by luizdepra** [comment]
Hello again.

I just pushed some changes into the main branch to check the problem, and I was unable to reproduce. But, I saw something. I think you are trying to access the `series` with a `category` URL. These taxonomies are not the same. Going to `http://localhost:1313/es/series`, do you see any content?

As I said, I modified some content from the demo site. I add accents and other non-english characters in the `pt-br` content, and it looks fine. See those links:

- https://hugo-coder.netlify.app/pt-br/series/
- https://hugo-coder.netlify.app/pt-br/series/demonstra%C3%A7%C3%A3o-do-tema/
- https://hugo-coder.netlify.app/pt-br/categories/
- https://hugo-coder.netlify.app/pt-br/categories/demonstra%C3%A7%C3%A3o-do-tema/
- https://hugo-coder.netlify.app/pt-br/authors/
- https://hugo-coder.netlify.app/pt-br/authors/programador-solit%C3%A1rio/

Am I missing something?

**Comment by andgar2010** [comment]
Thank you for your response and for the effort to fix the issue. My sincere apologies for the confusion, upon further investigation, I found out it was a cache issue on my end which has been resolved now. Your assistance is greatly appreciated.
