### ISSUE TITLE
Unordered list bullets

### ISSUE THREAD

**Issue by lutenica** [luizdepra/hugo-coder#838]
Hello, I love the theme so far, great work! 

I noticed something, however, that I want to clarify and I apologize in advance but since my css knowledge is not that in-depth there might be some lack of understanding on my part!

When creating an unordered list it seems to get compiled in to proper html:

![html](https://github.com/luizdepra/hugo-coder/assets/49449730/6502c6eb-2d34-46de-a31d-a5a1488cb74a)

as it has the \<ul> tag and every item has the \<li> tag.

The actual rendered page, however, seems to be missing bullets or any other way for denoting the list items, due to the css:
![List_on_page](https://github.com/luizdepra/hugo-coder/assets/49449730/7f228168-e915-479f-9f3c-90d6cd21d808)
Where as default html with no CSS:

```
<!DOCTYPE html>
<html>
<body>
<p>Test list:</p>
<ul>
  <li>This</li>
  <li>Should</li>
  <li>Work</li>
</ul>

</body>
</html>
```
Renders with the bulletpoints:

![default_html](https://github.com/luizdepra/hugo-coder/assets/49449730/710f5c70-2b8c-444b-a953-8943b3e1a4d0)

So I went digging through the [assets](https://github.com/luizdepra/hugo-coder/tree/main/assets)/[scss](https://github.com/luizdepra/hugo-coder/tree/main/assets/scss) directory and found that [list-style](https://github.com/luizdepra/hugo-coder/blob/c3df12d0bbc2dda164df904f6a487580a82da746/assets/scss/_content.scss#L122C5-L122C15) "none" is specified in the content.scss. When I change it to circle or square or the unicode for the bullet ``\2022`` that does nothing, where doing such a change for the [navbar](https://github.com/luizdepra/hugo-coder/blob/c3df12d0bbc2dda164df904f6a487580a82da746/assets/scss/_navigation.scss#L29) works and the menu items in the nav bar show bullet points.

In order to get bullet points or any sort of seperators for unordered lists I had to add the following code on line 159 of the _content.scss:

```
   ul li::before {
      content: "\2022";  
      /* Various style tags for the bullet
  }
```
And now they actually show up:

![Working_bullets](https://github.com/luizdepra/hugo-coder/assets/49449730/eca58502-dfb3-409d-87fa-40c80ea50776)

Ordered lists work as expected meanwhile.

What I am trying to figure out is, is this intentional so that the end user can stylize their own list bullets? Given that base html renders some bullet I would expect the default to actually be some sort of denotion of items in an un-ordered list. If not then can you advise if adding the changes to the css file I mentioned is the best path forward (again I am not proficient with this stuff yet and am hesitant to submit PRs with poor code).

Else, what would a good place to document this be as it caught me off guard so I guess I want to avoid anybody from spending too much time looking into this (though I guess my asking here will also document it for future generations)? 

Again I apologize for any naivety on my part and thenk you once again for the great theme!

**Comment by simonhollingshead** [comment]
The demo app has a section demonstrating bulleted lists (and nested lists) working as expected with no CSS hackery (https://hugo-coder.netlify.app/posts/markdown-syntax/#list-types).

The CSS you pointed at wouldn't have had effect on articles because that's for ".list ul".  ".list" is used in the list of posts (e.g. https://hugo-coder.netlify.app/posts/) so that no bullet points appear there.  A post has class ".post" instead which doesn't apply such changes.

I am unsure what you have done, but it's not an inherent part of the design of this template.
