### ISSUE TITLE
Unable to hide color scheme toggle

### ISSUE THREAD

**Issue by emavgl** [luizdepra/hugo-coder#845]
Hi, as explained in the title, I am unable to hide the color scheme toggle (the one showing in the footer).
I have tried adding the option

hideColorSchemeToggle = true

but it seems not working for me https://github.com/emavgl/emavgl.github.io/blob/master/config.toml#L16

Thank you!

**Comment by emavgl** [comment]
I solved by overwriting the file `/layouts/partials/float.html`. I leave the issue open since the option did not work for me.

**Comment by luizdepra** [comment]
Hey!

An honest mistake. You need to put the `hideColorSchemeToggle` inside the `[params]` section. All theme configuration must be added inside that configuration section.

**Comment by emavgl** [comment]
My bad, I am still new with Hugo :') - I take the opportunity to thank you your work on this project!
