### ISSUE TITLE
Fork-Awesome is deprecated, please consider alternatives

### ISSUE THREAD

**Issue by paride** [luizdepra/hugo-coder#858]
## Describe the problem:

I've been watching Fork-Awesome for a while, a bit frustrated by bugs, missing icons and the lack of new releases. I even recompiled it myself to use a newer version of it, only to discover [more bugs](https://github.com/ForkAwesome/Fork-Awesome/issues/421).

Turns out the Fork-Awesome consider the project deprecated (or even "failed" in some ways), and plan to archive it in 2024. See https://github.com/ForkAwesome/Fork-Awesome/blob/master/README.md and https://github.com/ForkAwesome/Fork-Awesome/blob/master/posts/2023-04-10_forkawesomeIntrospection/forkawesomeIntrospection.md.

I think hugo-coder should start looking for alternatives, which may include switching back to Font Awesome.

**Comment by luizdepra** [comment]
Hey.

Well, we could change. No problem.
But, returning to Font Awesome is not an option because of its license.

**Comment by paride** [comment]
Hey @luizdepra, AIUI the problem with Font Awesome is not really the license, but the fact that the build system is not public, and that the project does not accept community contributions. At least this is what I get paragraph right before "Forkawesome 1.x" in https://github.com/ForkAwesome/Fork-Awesome/blob/master/posts/2023-04-10_forkawesomeIntrospection/forkawesomeIntrospection.md:

> [Fontawesome 5.0.6](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.0.6), the initial release of the 5.x series, was released on the 6th of February 2018 by Rob Madole. (The very first release of series 5.x, 5.0.0-alpha1, was released on the 23rd of June 2017, but is no longer available.) On the 4th of February 2018 Julian Deswaef raised the https://github.com/FortAwesome/Font-Awesome/issues/12199#issuecomment-362919956 that the build system for the website and CSS, LESS & SASS was no longer shared, and that community pull requests were continuing to be refused. Madole confirmed these developments were intentional https://github.com/FortAwesome/Font-Awesome/issues/12199#issuecomment-363168281.

This said, I am totally in favor of using a "true" FLOSS project (without a working build system the sources are not of much use), but unfortunately I don't see many alternatives at the moment :(

**Comment by simonhollingshead** [comment]
For what it's worth, I got sufficiently frustrated with the missing parts of Fork Awesome that I actually carry a patch on my own repo to swap back to Font Awesome, which thankfully was relatively minimal in size.

(For anyone reading this, don't directly use my patch, though, I've deliberately dropped the v4 shims in favour of swapping to v5+ syntax, so it is not a drop in replacement for an existing codebase)

**Comment by b-reich** [comment]
Whats the plan? Using FontAwsome (instead of the Forked one) or a totally new icon set?

**Comment by luizdepra** [comment]
No plans yet. I need to check if there are any license related problems if we redistribute FontAwesome within the theme. If so, maybe we could point to its CDN. Or, find another icon set.

**Comment by simonhollingshead** [comment]
https://fontawesome.com/license/free

As far as I can tell:

Icons - CC BY 4.0 License - Not relevant if you're using the WOFF2 and the SCSS, only if you're using the SVG/JS icons.

Fonts - SIL OFL 1.1 License - https://openfontlicense.org/how-to-use-ofl-fonts/ - there are no issues in redistributing with proper attribution.
Code - MIT License - https://opensource.org/license/mit/ - there are no issues in redistributing with proper attribution.

**Comment by luizdepra** [comment]
Right. I was looking for other options, but everything interesting that I found is SVG-based. It would be a lot of work to change to.

So, I'm accepting help with the migration.

**Comment by simonhollingshead** [comment]
IMO, my existing change is a good starting point but I'd need to make a couple of changes.  Specifically, it really would have to inject v4-shims because people use those fontawesome classes in their homepage - it's not something where a refactor of hugo-coder covers all uses such that everything could be mass-migrated to the v6 syntax. 

Maybe I can see if I can propose a couple of PRs at the weekend, one to move to v6 in compatibility mode, and then one to modernize how the existing codebase calls FA.

**Comment by luizdepra** [comment]
Would be less complicated to migrate to FA v5?
As far as I read, we can't self-host v6 kits without pro license. I don't know if they provide a default kit or something like.

**Comment by simonhollingshead** [comment]
You don't need kits.  A kit is a pro-level feature for auto-subsetting a font.  The reason there's no free equivalent is because that's a paid-for feature that isn't necessary for our use-case.

The standard free download contains WOFF files which can be redistributed.
