### ISSUE TITLE
Remove prefetch-src from layouts/partials/csp.html.

### ISSUE THREAD

**Issue by sammy44nts** [luizdepra/hugo-coder#881]
## Describe the problem:

[prefetch-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/prefetch-src) CSP is deprecated.

### Steps to reproduce:

1. Open the developer console in a recent web browser and you'll find the error message: **Unrecognized Content-Security-Policy directive 'prefetch-src'.**

### How to fix this issue

Remove `(delimit .Site.Params.csp.prefetchsrc " ") ` from layouts/partials/csp.html.

**Comment by luizdepra** [comment]
Nice. Easy fixing.

If anyone is willing to help with this one, please send a PR.
