### ISSUE TITLE
How can I stop my tags from being auto capitalized?

### ISSUE THREAD

**Issue by ScottPierce** [luizdepra/hugo-coder#905]
I've noticed that other people using this template have their tags all lowercase, but my tags seem to be auto capitalized, even when defined lowercase in my post header.

This header:
```
+++ 
draft = true
date = 2024-04-15T22:31:46-04:00
title = "This is an example"
description = ""
tags = [
    "android",
    "jetpack-compose",
    "kotlin",
]
categories = []
series = []
+++
```

Renders:
<img width="458" alt="image" src="https://github.com/luizdepra/hugo-coder/assets/871169/8923f931-112b-41cf-be7c-9790231d5b18">

**Comment by luizdepra** [comment]
Hey.
I think there's no configuration to change the capitalization. Have you added any CSS or template customization?

**Comment by ScottPierce** [comment]
No. I'm using the example base configuration too.

**Comment by luizdepra** [comment]
Which version of Hugo are you using? It is the extended binary?
Is your site's source code open? Can I take a look?

**Comment by ScottPierce** [comment]
```
hugo version
hugo v0.125.2-4e483f5d4abae136c4312d397a55e9e1d39148df+extended darwin/arm64 BuildDate=2024-04-20T15:29:44Z VendorInfo=brew
```

I just invited you to the repository. Thanks!

**Comment by luizdepra** [comment]
Got it. Something changed in one of the latest versions of Hugo. Now it capitalizes taxonomy titles.
You can change this behavior by setting `capitalizeListTitles = false`.

**Comment by ScottPierce** [comment]
Works! Thank you!

**Comment by ScottPierce** [comment]
@luizdepra Thank you for maintaining this. I really this blog template. Very useful!
