### ISSUE TITLE
Turn off `hyphens: auto` in the css?

### ISSUE THREAD

**Issue by ScottPierce** [luizdepra/hugo-coder#915]
## How can I turn off `hyphens: auto` in the CSS?

i.e.
```
.content article p {
    text-align: justify;
    text-justify: auto;
    hyphens: auto;
}
```

It's creating strange word wraps that seems like an odd default. This seems like it would be a setting somewhere that I can turn off, but I haven't ben able to find the setting in the documentation. Is it possible?

**Comment by luizdepra** [comment]
Hey there.
Nop, there is no configuration to change that. You will need to override the SCSS containing this rule.

**Comment by ScottPierce** [comment]
For anyone else who finds this, I was able to get around this by adding this to my `hugo.toml`:

```
customCSS = ["css/blog-custom.css"]
```

The contents of blog-custom.css are:
```
.content article p {
    hyphens: none;
}
```
