### ISSUE TITLE
Responsive menu?

### ISSUE THREAD

**Issue by jemostrom** [luizdepra/hugo-coder#93]
I've been playing with the theme and to me it looks like the menu doesn't display as an "hamburger menu" for narrow screens. Is this the intended design or am I missing something? (yep Hugo newbie)

**Comment by luizdepra** [comment]
Yes, we have and mobile menu. It should display in 768px or less screens.

**Comment by jemostrom** [comment]
Hmmm, I must be missing something ... it looks like this for me.
<img width="523" alt="screen shot 2018-10-09 at 21 42 56" src="https://user-images.githubusercontent.com/1286228/46694228-6fabbd00-cc0c-11e8-88e8-63ced3b7e68e.png">

**Comment by khos2ow** [comment]
@jemostrom how did you test this? I mean is this a local clone of this theme? Are you sure you have the updated theme in your site?
For the sake of comparison you can take a look at https://deploy-preview-90--hugo-coder.netlify.com/ which is based of _almost_ the latest of the `master` HEAD.

**Comment by jemostrom** [comment]
Yep, I downloaded a zip yesterday (I'm just playing around at the moment) and use it locally. But I see the same thing on the preview site. Here are screenshots from Safari and Firefox 

<img width="550" alt="screen shot 2018-10-09 at 22 10 35" src="https://user-images.githubusercontent.com/1286228/46695720-99ff7980-cc10-11e8-9770-af18a8c29902.png">

<img width="379" alt="screen shot 2018-10-09 at 22 11 01" src="https://user-images.githubusercontent.com/1286228/46695729-9f5cc400-cc10-11e8-9dda-69e6324b3a58.png">

**Comment by jemostrom** [comment]
I'm probably too stupid to do things correctly (I'm not doing any web design so ...) but on Safari I enter the responsive mode and select one of the available iPhones ... and it looks like this

<img width="724" alt="screen shot 2018-10-09 at 22 34 52" src="https://user-images.githubusercontent.com/1286228/46696909-acc77d80-cc13-11e8-90a9-59ef1b9a784e.png">

Am I doing something wrong here. Also, if I make my window narrow on my laptop shouldn't I also get the responsive menu? My thinking is that I might have several windows open and have made windows narrow so they can be viewed at the same time.

**Comment by jemostrom** [comment]
Firefox seem to do it correctly

**Comment by jemostrom** [comment]
FWIW - I did change `max-device-width` to `max-width` and it displays as I first expected. But I don't know if I'm doing things correctly. Is there some description somewhere how I should work to make changes to CSS/SCSS (I have no previous experience of SCSS)?

**Comment by luizdepra** [comment]
Wierd. Can you give me the version of your Safari? Maybe we need to add an extra rule or something to make it work on Safari. Need some research.

> Is there some description somewhere how I should work to make changes to CSS/SCSS (I have no previous experience of SCSS)?

Not yet. I need to write something. But you will need to use Hugo Extended v0.43 or more to compile the SCSS into CSS. The command `make release` will to this job for you. And, about changing the SCSS, it is very straightforward I think.

**Comment by jemostrom** [comment]
Yes, it's basically how to build the css files I need help with, the scss files looks almost like normal css files so I think handle that part.

Safari: Version 12.0 (14606.1.36.1.9)

**Comment by josephting** [comment]
I did some quick research and it seems like `device-width` have been deprecated.

> To query for the size of the viewport (or the page box on page media), the width, height and aspect-ratio media features should be used, rather than device-width, device-height and device-aspect-ratio, which refer to the physical size of the the device regardless of how much space is available for the document being laid out.

Ref: [W3C](https://www.w3.org/TR/mediaqueries-4/#mf-deprecated) | [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/device-width)

With that said, all `max-device-width` should be replaced with `max-width`.

- [W3C Viewport/Page Dimensions `width` Media Feature](https://www.w3.org/TR/mediaqueries-4/#width)
- [MDN `width` CSS Media Feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/width)

I can create a PR for this if you're OK with the proposed change.

**Comment by luizdepra** [comment]
@josephting sure. I would appreciate it.

**Comment by vongohren** [comment]
@luizdepra is there a reason this is not merged into the master branch yet? Or should I depend on something else than master?
