### ISSUE TITLE
Hierarchical menus?

### ISSUE THREAD

**Issue by jemostrom** [luizdepra/hugo-coder#94]
I've been trying to get hierarchical menus to work but I don't know if I'm doing something wrong or if coder doesn't support them. So my question is: does coder hierarchical menus? If so, is there an example somewhere of how to do?

**Comment by luizdepra** [comment]
Yep, hugo-coder don't support it yet.

We should avoid JS to do this job. So look for CSS-only options, like this one: https://medialoot.com/blog/how-to-create-a-responsive-navigation-menu-using-only-css/

**Comment by jemostrom** [comment]
Thanks. I need to play a bit when I get back home and see what happens.
