### ISSUE TITLE
Deployed site not loading CSS files

### ISSUE THREAD

**Issue by systemallica** [luizdepra/hugo-coder#98]
Hi, I'm using Hugo(**v0.49**) with your theme(https://github.com/luizdepra/hugo-coder/commit/9dc5dc0fd02f2fe219bdad480e1f8d244396218a).

When navigating the website using `hugo server` everything is fine, but if I try to use the production website built by  `hugo` the CSS is not loaded and the following error message is shown:
![image](https://user-images.githubusercontent.com/4086951/46907855-7cd0f080-cf19-11e8-80cb-6f3915f5c422.png)

Is this a `Hugo` problem or a theme problem?

You can take a look at my configuration here: https://gitlab.com/systemallica/systemallica.gitlab.io

Cheers

**Comment by luizdepra** [comment]
Will you access the site from `https://systemallica.gitlab.io/` address?
If so, the problem should be the `baseURL` that is different from the address you are using in the configuration.

**Comment by systemallica** [comment]
No, I will access it from `https://andres.reveronmolina.me`. Anyway, the problem occurs if I access it from `https://andres.reveronmolina.me`, from `https://systemallica.gitlab.io` or even if I try to open the `index.html` locally.

**Comment by luizdepra** [comment]
Understood. The problem is the `base` tag from `baseof.html`.

It seems your use case (more than one address) is kind of common. So, could you please make a PR to fix this problem?

**Comment by systemallica** [comment]
I'm sorry, but I don't see what the solution is. What changes should I make?

**Comment by jaredtconnor** [comment]
Hey, I believe I'm getting the same issue when trying to deploy using [Netlify](https://www.netlify.com). I'm currently running Hugo v 0.55.6, and have that specified in my _netlify.toml_ to ensure the builds are the same. CSS appears to deploy on a local preview (e.g. `hugo server`), but any deploy on the site appears to not load a specified CSS. 

My specifications for the base URL are as followed: 
`baseurl = "http://www.jaredtconnor.com/"` 

So I don't believe it should be a domain routing issue for the CSS. I've followed [this](https://alison.rbind.io/post/2019-03-04-hugo-troubleshooting/) trouble shooting and can't seem to locate the issue. I've seen comments that it could be Netlify's issue with loading SCSS.

Any thoughts? 

Repo is [here](https://github.com/jaredtconnor/Personal-Site)

**Comment by luizdepra** [comment]
Debug your site I got this:

![Screenshot from 2019-06-17 14-39-12](https://user-images.githubusercontent.com/1427376/59624683-c78cb300-910d-11e9-9510-d2e194235f22.png)

It seems you're serving over `https` but your site is configured with `http`.
I think fixing `baseurl` to `https` will do the trick. You can also override the `baseurl` via `netlify.toml`, like I'm doing [here](https://github.com/luizdepra/hugo-coder/blob/master/netlify.toml#L3).

**Comment by jaredtconnor** [comment]
Yeah that worked, thank you. Rebuilt the netlify.toml to specify `https`. Build's correctly now.
