### ISSUE TITLE
Regenerating SCSS

### ISSUE THREAD

**Issue by mkjmdski** [luizdepra/hugo-coder#99]
Hey!
First of all I would like to thank you for this amazing theme! I forked your repository and changed coder.scss file to import new style I have added to the theme, but unfortunately files in the resources directory aren't regenerating. I'm wondering is it lack of my knowledge or is this a bug? I've taken a look into the baseof.html file and it should be using Hugo Pipes but somehow assets are still the same. I have disabled cache, opened a private mode etc... but still my CSS is the same. I'm really sorry if it is just lack of my knowledge and not the bug.

P.S. I don't want to add custom css option, because I want to override some colors. ;)

Edit: I have deleted generated css files from resources directory and now I've got this error: Building sites … ERROR 2018/10/14 19:32:19 error: failed to transform resource: TOCSS: failed to transform "style.coder.css" (text/x-scss): this feature is not available in your current Hugo version

Maybe that is more hugo bug itself?

**Comment by mkjmdski** [comment]
Ok I have found out that I need to use extended hugo version. Sorry for mess :)

**Comment by khos2ow** [comment]
Yes, you need Hugo extended version, or you can simply use the existing targets in `Makefile` (e.g. `prepare`, `build`, etc). In your particular case you need to run `release` target. It will regenerate the content of `resources` folder:

```$: cd /path/to/the/repo && make release```
